generatorName: typescript-fetch
inputSpec: https://openapi.schematichq.com/prod/api/apikeypublishable.yml
enablePostProcessFile: true
outputDir: ./src/types/api/
globalProperties:
  models: ""
  supportingFiles: runtime.ts,index.ts
  modelTests: false
  modelDocs: false
  skipFormModel: false
skipValidateSpec: true
generateAliasAsModel: true
