/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CheckoutFieldValue
 */
export interface CheckoutFieldValue {
  /**
   *
   * @type {string}
   * @memberof CheckoutFieldValue
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof CheckoutFieldValue
   */
  value: string;
}

/**
 * Check if a given object implements the CheckoutFieldValue interface.
 */
export function instanceOfCheckoutFieldValue(
  value: object,
): value is CheckoutFieldValue {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("value" in value) || value["value"] === undefined) return false;
  return true;
}

export function CheckoutFieldValueFromJSON(json: any): CheckoutFieldValue {
  return CheckoutFieldValueFromJSONTyped(json, false);
}

export function CheckoutFieldValueFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CheckoutFieldValue {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"],
    value: json["value"],
  };
}

export function CheckoutFieldValueToJSON(json: any): CheckoutFieldValue {
  return CheckoutFieldValueToJSONTyped(json, false);
}

export function CheckoutFieldValueToJSONTyped(
  value?: CheckoutFieldValue | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    value: value["value"],
  };
}
