/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const EntitlementType = {
  CompanyOverride: "company_override",
  PlanEntitlement: "plan_entitlement",
  Unknown: "unknown",
} as const;
export type EntitlementType =
  (typeof EntitlementType)[keyof typeof EntitlementType];

export function instanceOfEntitlementType(value: any): boolean {
  for (const key in EntitlementType) {
    if (Object.prototype.hasOwnProperty.call(EntitlementType, key)) {
      if (EntitlementType[key as keyof typeof EntitlementType] === value) {
        return true;
      }
    }
  }
  return false;
}

export function EntitlementTypeFromJSON(json: any): EntitlementType {
  return EntitlementTypeFromJSONTyped(json, false);
}

export function EntitlementTypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): EntitlementType {
  return json as EntitlementType;
}

export function EntitlementTypeToJSON(value?: EntitlementType | null): any {
  return value as any;
}

export function EntitlementTypeToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean,
): EntitlementType {
  return value as EntitlementType;
}
