/**
 * The catalog contract lives in schematic-js; re-exported here so the hooks
 * and components share one set of types.
 */
export {
  type AnyCatalog,
  type AutoTopupAvailability,
  type Catalog,
  type CatalogCapabilities,
  type CatalogData,
  type CatalogPlan,
  type CatalogResourceName,
  type CatalogResources,
  type CheckoutBehavior,
  type CompanyCatalog,
  type CompanyCatalogPlan,
  type CompanyContext,
  type CompanyPlan,
  type CreditAutoTopup,
  type CreditBalanceEntry,
  type CreditBundle,
  type CreditExpiryType,
  type CreditExpiryUnit,
  type CreditGrant,
  type CreditGrantReason,
  type CreditGrantRow,
  type CreditGrantScaling,
  type CreditRef,
  type CreditResetCadence,
  type CustomBilling,
  type CustomPlanCta,
  type Discount,
  type DiscountDuration,
  type Entitlement,
  type EntitlementCredit,
  type EntitlementDisplay,
  type EntitlementMetricPeriod,
  type EntitlementMonthReset,
  type EntitlementSource,
  type EntitlementValueKind,
  type FeatureKind,
  type FeatureRef,
  type FeatureUsageRow,
  type Invoice,
  type InvoicePage,
  type InvoiceStatus,
  type PlanChargeType,
  type PlanInvalidReason,
  type PlanRef,
  type Price,
  type PriceBehavior,
  type PriceCadence,
  type PriceInterval,
  type PriceScheme,
  type PriceTier,
  type ResourceState,
  type ScheduledDowngrade,
  type Subscription,
  type SubscriptionStatus,
  type TiersMode,
  type UpcomingInvoice,
  type UsageViolation,
  isCompanyCatalog,
} from "@schematichq/schematic-js";
