/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { BillingProductPriceResponseData } from "./BillingProductPriceResponseData";
import {
  BillingProductPriceResponseDataFromJSON,
  BillingProductPriceResponseDataFromJSONTyped,
  BillingProductPriceResponseDataToJSON,
} from "./BillingProductPriceResponseData";

/**
 *
 * @export
 * @interface BillingCreditBundleView
 */
export interface BillingCreditBundleView {
  /**
   *
   * @type {string}
   * @memberof BillingCreditBundleView
   */
  bundleType: string;
  /**
   *
   * @type {Date}
   * @memberof BillingCreditBundleView
   */
  createdAt: Date;
  /**
   *
   * @type {string}
   * @memberof BillingCreditBundleView
   */
  creditId: string;
  /**
   *
   * @type {string}
   * @memberof BillingCreditBundleView
   */
  expiryType: string;
  /**
   *
   * @type {string}
   * @memberof BillingCreditBundleView
   */
  expiryUnit: string;
  /**
   *
   * @type {number}
   * @memberof BillingCreditBundleView
   */
  expiryUnitCount?: number | null;
  /**
   *
   * @type {string}
   * @memberof BillingCreditBundleView
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof BillingCreditBundleView
   */
  name: string;
  /**
   *
   * @type {BillingProductPriceResponseData}
   * @memberof BillingCreditBundleView
   */
  price?: BillingProductPriceResponseData;
  /**
   *
   * @type {number}
   * @memberof BillingCreditBundleView
   */
  quantity?: number | null;
  /**
   *
   * @type {string}
   * @memberof BillingCreditBundleView
   */
  status: string;
  /**
   *
   * @type {Date}
   * @memberof BillingCreditBundleView
   */
  updatedAt: Date;
}

/**
 * Check if a given object implements the BillingCreditBundleView interface.
 */
export function instanceOfBillingCreditBundleView(
  value: object,
): value is BillingCreditBundleView {
  if (!("bundleType" in value) || value["bundleType"] === undefined)
    return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("creditId" in value) || value["creditId"] === undefined) return false;
  if (!("expiryType" in value) || value["expiryType"] === undefined)
    return false;
  if (!("expiryUnit" in value) || value["expiryUnit"] === undefined)
    return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("status" in value) || value["status"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  return true;
}

export function BillingCreditBundleViewFromJSON(
  json: any,
): BillingCreditBundleView {
  return BillingCreditBundleViewFromJSONTyped(json, false);
}

export function BillingCreditBundleViewFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BillingCreditBundleView {
  if (json == null) {
    return json;
  }
  return {
    bundleType: json["bundle_type"],
    createdAt: new Date(json["created_at"]),
    creditId: json["credit_id"],
    expiryType: json["expiry_type"],
    expiryUnit: json["expiry_unit"],
    expiryUnitCount:
      json["expiry_unit_count"] == null ? undefined : json["expiry_unit_count"],
    id: json["id"],
    name: json["name"],
    price:
      json["price"] == null
        ? undefined
        : BillingProductPriceResponseDataFromJSON(json["price"]),
    quantity: json["quantity"] == null ? undefined : json["quantity"],
    status: json["status"],
    updatedAt: new Date(json["updated_at"]),
  };
}

export function BillingCreditBundleViewToJSON(
  value?: BillingCreditBundleView | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    bundle_type: value["bundleType"],
    created_at: value["createdAt"].toISOString(),
    credit_id: value["creditId"],
    expiry_type: value["expiryType"],
    expiry_unit: value["expiryUnit"],
    expiry_unit_count: value["expiryUnitCount"],
    id: value["id"],
    name: value["name"],
    price: BillingProductPriceResponseDataToJSON(value["price"]),
    quantity: value["quantity"],
    status: value["status"],
    updated_at: value["updatedAt"].toISOString(),
  };
}
