/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const BillingCreditRolloverPolicy = {
  Expire: "expire",
  None: "none",
  Rollover: "rollover",
} as const;
export type BillingCreditRolloverPolicy =
  (typeof BillingCreditRolloverPolicy)[keyof typeof BillingCreditRolloverPolicy];

export function instanceOfBillingCreditRolloverPolicy(value: any): boolean {
  for (const key in BillingCreditRolloverPolicy) {
    if (
      Object.prototype.hasOwnProperty.call(BillingCreditRolloverPolicy, key)
    ) {
      if (
        (
          BillingCreditRolloverPolicy as Record<
            string,
            BillingCreditRolloverPolicy
          >
        )[key] === value
      ) {
        return true;
      }
    }
  }
  return false;
}

export function BillingCreditRolloverPolicyFromJSON(
  json: any,
): BillingCreditRolloverPolicy {
  return BillingCreditRolloverPolicyFromJSONTyped(json, false);
}

export function BillingCreditRolloverPolicyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BillingCreditRolloverPolicy {
  return json as BillingCreditRolloverPolicy;
}

export function BillingCreditRolloverPolicyToJSON(
  value?: BillingCreditRolloverPolicy | null,
): any {
  return value as any;
}
