/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const BillingCreditGrantZeroedOutReason = {
  Expired: "expired",
  Manual: "manual",
  PlanChange: "plan_change",
  PlanPeriodReset: "plan_period_reset",
} as const;
export type BillingCreditGrantZeroedOutReason =
  (typeof BillingCreditGrantZeroedOutReason)[keyof typeof BillingCreditGrantZeroedOutReason];

export function instanceOfBillingCreditGrantZeroedOutReason(
  value: any,
): boolean {
  for (const key in BillingCreditGrantZeroedOutReason) {
    if (
      Object.prototype.hasOwnProperty.call(
        BillingCreditGrantZeroedOutReason,
        key,
      )
    ) {
      if (
        (
          BillingCreditGrantZeroedOutReason as Record<
            string,
            BillingCreditGrantZeroedOutReason
          >
        )[key] === value
      ) {
        return true;
      }
    }
  }
  return false;
}

export function BillingCreditGrantZeroedOutReasonFromJSON(
  json: any,
): BillingCreditGrantZeroedOutReason {
  return BillingCreditGrantZeroedOutReasonFromJSONTyped(json, false);
}

export function BillingCreditGrantZeroedOutReasonFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BillingCreditGrantZeroedOutReason {
  return json as BillingCreditGrantZeroedOutReason;
}

export function BillingCreditGrantZeroedOutReasonToJSON(
  value?: BillingCreditGrantZeroedOutReason | null,
): any {
  return value as any;
}
