/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { BillingCreditBundleType } from "./BillingCreditBundleType";
import {
  BillingCreditBundleTypeFromJSON,
  BillingCreditBundleTypeFromJSONTyped,
  BillingCreditBundleTypeToJSON,
} from "./BillingCreditBundleType";
import type { BillingCreditExpiryType } from "./BillingCreditExpiryType";
import {
  BillingCreditExpiryTypeFromJSON,
  BillingCreditExpiryTypeFromJSONTyped,
  BillingCreditExpiryTypeToJSON,
} from "./BillingCreditExpiryType";
import type { BillingCreditBundleStatus } from "./BillingCreditBundleStatus";
import {
  BillingCreditBundleStatusFromJSON,
  BillingCreditBundleStatusFromJSONTyped,
  BillingCreditBundleStatusToJSON,
} from "./BillingCreditBundleStatus";
import type { BillingProductPriceResponseData } from "./BillingProductPriceResponseData";
import {
  BillingProductPriceResponseDataFromJSON,
  BillingProductPriceResponseDataFromJSONTyped,
  BillingProductPriceResponseDataToJSON,
} from "./BillingProductPriceResponseData";
import type { BillingCreditExpiryUnit } from "./BillingCreditExpiryUnit";
import {
  BillingCreditExpiryUnitFromJSON,
  BillingCreditExpiryUnitFromJSONTyped,
  BillingCreditExpiryUnitToJSON,
} from "./BillingCreditExpiryUnit";

/**
 *
 * @export
 * @interface BillingCreditBundleView
 */
export interface BillingCreditBundleView {
  /**
   *
   * @type {string}
   * @memberof BillingCreditBundleView
   */
  billingInvoiceId?: string | null;
  /**
   *
   * @type {BillingCreditBundleType}
   * @memberof BillingCreditBundleView
   */
  bundleType: BillingCreditBundleType;
  /**
   *
   * @type {Date}
   * @memberof BillingCreditBundleView
   */
  createdAt: Date;
  /**
   *
   * @type {string}
   * @memberof BillingCreditBundleView
   */
  creditDescription?: string;
  /**
   *
   * @type {string}
   * @memberof BillingCreditBundleView
   */
  creditIcon?: string | null;
  /**
   *
   * @type {string}
   * @memberof BillingCreditBundleView
   */
  creditId: string;
  /**
   *
   * @type {string}
   * @memberof BillingCreditBundleView
   */
  creditName: string;
  /**
   *
   * @type {BillingCreditExpiryType}
   * @memberof BillingCreditBundleView
   */
  expiryType: BillingCreditExpiryType;
  /**
   *
   * @type {BillingCreditExpiryUnit}
   * @memberof BillingCreditBundleView
   */
  expiryUnit: BillingCreditExpiryUnit;
  /**
   *
   * @type {number}
   * @memberof BillingCreditBundleView
   */
  expiryUnitCount?: number | null;
  /**
   *
   * @type {boolean}
   * @memberof BillingCreditBundleView
   */
  hasGrants: boolean;
  /**
   *
   * @type {string}
   * @memberof BillingCreditBundleView
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof BillingCreditBundleView
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof BillingCreditBundleView
   */
  pluralName?: string | null;
  /**
   *
   * @type {BillingProductPriceResponseData}
   * @memberof BillingCreditBundleView
   */
  price?: BillingProductPriceResponseData;
  /**
   *
   * @type {number}
   * @memberof BillingCreditBundleView
   */
  quantity?: number | null;
  /**
   *
   * @type {string}
   * @memberof BillingCreditBundleView
   */
  singularName?: string | null;
  /**
   *
   * @type {BillingCreditBundleStatus}
   * @memberof BillingCreditBundleView
   */
  status: BillingCreditBundleStatus;
  /**
   *
   * @type {BillingProductPriceResponseData}
   * @memberof BillingCreditBundleView
   */
  unitPrice?: BillingProductPriceResponseData;
  /**
   *
   * @type {Date}
   * @memberof BillingCreditBundleView
   */
  updatedAt: Date;
}

/**
 * Check if a given object implements the BillingCreditBundleView interface.
 */
export function instanceOfBillingCreditBundleView(
  value: object,
): value is BillingCreditBundleView {
  if (!("bundleType" in value) || value["bundleType"] === undefined)
    return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("creditId" in value) || value["creditId"] === undefined) return false;
  if (!("creditName" in value) || value["creditName"] === undefined)
    return false;
  if (!("expiryType" in value) || value["expiryType"] === undefined)
    return false;
  if (!("expiryUnit" in value) || value["expiryUnit"] === undefined)
    return false;
  if (!("hasGrants" in value) || value["hasGrants"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("status" in value) || value["status"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  return true;
}

export function BillingCreditBundleViewFromJSON(
  json: any,
): BillingCreditBundleView {
  return BillingCreditBundleViewFromJSONTyped(json, false);
}

export function BillingCreditBundleViewFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BillingCreditBundleView {
  if (json == null) {
    return json;
  }
  return {
    billingInvoiceId:
      json["billing_invoice_id"] == null
        ? undefined
        : json["billing_invoice_id"],
    bundleType: BillingCreditBundleTypeFromJSON(json["bundle_type"]),
    createdAt: new Date(json["created_at"]),
    creditDescription:
      json["credit_description"] == null
        ? undefined
        : json["credit_description"],
    creditIcon: json["credit_icon"] == null ? undefined : json["credit_icon"],
    creditId: json["credit_id"],
    creditName: json["credit_name"],
    expiryType: BillingCreditExpiryTypeFromJSON(json["expiry_type"]),
    expiryUnit: BillingCreditExpiryUnitFromJSON(json["expiry_unit"]),
    expiryUnitCount:
      json["expiry_unit_count"] == null ? undefined : json["expiry_unit_count"],
    hasGrants: json["has_grants"],
    id: json["id"],
    name: json["name"],
    pluralName: json["plural_name"] == null ? undefined : json["plural_name"],
    price:
      json["price"] == null
        ? undefined
        : BillingProductPriceResponseDataFromJSON(json["price"]),
    quantity: json["quantity"] == null ? undefined : json["quantity"],
    singularName:
      json["singular_name"] == null ? undefined : json["singular_name"],
    status: BillingCreditBundleStatusFromJSON(json["status"]),
    unitPrice:
      json["unit_price"] == null
        ? undefined
        : BillingProductPriceResponseDataFromJSON(json["unit_price"]),
    updatedAt: new Date(json["updated_at"]),
  };
}

export function BillingCreditBundleViewToJSON(
  value?: BillingCreditBundleView | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    billing_invoice_id: value["billingInvoiceId"],
    bundle_type: BillingCreditBundleTypeToJSON(value["bundleType"]),
    created_at: value["createdAt"].toISOString(),
    credit_description: value["creditDescription"],
    credit_icon: value["creditIcon"],
    credit_id: value["creditId"],
    credit_name: value["creditName"],
    expiry_type: BillingCreditExpiryTypeToJSON(value["expiryType"]),
    expiry_unit: BillingCreditExpiryUnitToJSON(value["expiryUnit"]),
    expiry_unit_count: value["expiryUnitCount"],
    has_grants: value["hasGrants"],
    id: value["id"],
    name: value["name"],
    plural_name: value["pluralName"],
    price: BillingProductPriceResponseDataToJSON(value["price"]),
    quantity: value["quantity"],
    singular_name: value["singularName"],
    status: BillingCreditBundleStatusToJSON(value["status"]),
    unit_price: BillingProductPriceResponseDataToJSON(value["unitPrice"]),
    updated_at: value["updatedAt"].toISOString(),
  };
}
