/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const BillingCreditBundleStatus = {
  Active: "active",
  Inactive: "inactive",
} as const;
export type BillingCreditBundleStatus =
  (typeof BillingCreditBundleStatus)[keyof typeof BillingCreditBundleStatus];

export function instanceOfBillingCreditBundleStatus(value: any): boolean {
  for (const key in BillingCreditBundleStatus) {
    if (Object.prototype.hasOwnProperty.call(BillingCreditBundleStatus, key)) {
      if (
        (
          BillingCreditBundleStatus as Record<string, BillingCreditBundleStatus>
        )[key] === value
      ) {
        return true;
      }
    }
  }
  return false;
}

export function BillingCreditBundleStatusFromJSON(
  json: any,
): BillingCreditBundleStatus {
  return BillingCreditBundleStatusFromJSONTyped(json, false);
}

export function BillingCreditBundleStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BillingCreditBundleStatus {
  return json as BillingCreditBundleStatus;
}

export function BillingCreditBundleStatusToJSON(
  value?: BillingCreditBundleStatus | null,
): any {
  return value as any;
}
