/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CheckoutPriceSnapshot
 */
export interface CheckoutPriceSnapshot {
  /**
   *
   * @type {number}
   * @memberof CheckoutPriceSnapshot
   */
  amountOff: number;
  /**
   *
   * @type {number}
   * @memberof CheckoutPriceSnapshot
   */
  dueNow: number;
  /**
   *
   * @type {boolean}
   * @memberof CheckoutPriceSnapshot
   */
  isScheduledDowngrade: boolean;
  /**
   *
   * @type {number}
   * @memberof CheckoutPriceSnapshot
   */
  newCharges: number;
  /**
   *
   * @type {boolean}
   * @memberof CheckoutPriceSnapshot
   */
  optInRequired: boolean;
  /**
   *
   * @type {boolean}
   * @memberof CheckoutPriceSnapshot
   */
  paymentMethodRequired: boolean;
  /**
   *
   * @type {number}
   * @memberof CheckoutPriceSnapshot
   */
  percentOff: number;
  /**
   *
   * @type {Date}
   * @memberof CheckoutPriceSnapshot
   */
  periodStart: Date;
  /**
   *
   * @type {Date}
   * @memberof CheckoutPriceSnapshot
   */
  pricedAt: Date;
  /**
   *
   * @type {boolean}
   * @memberof CheckoutPriceSnapshot
   */
  promoCodeApplied: boolean;
  /**
   *
   * @type {number}
   * @memberof CheckoutPriceSnapshot
   */
  proration: number;
  /**
   *
   * @type {Date}
   * @memberof CheckoutPriceSnapshot
   */
  scheduledChangeTime?: Date | null;
  /**
   *
   * @type {number}
   * @memberof CheckoutPriceSnapshot
   */
  taxAmount?: number | null;
  /**
   *
   * @type {number}
   * @memberof CheckoutPriceSnapshot
   */
  totalPerBillingPeriod: number;
  /**
   *
   * @type {Date}
   * @memberof CheckoutPriceSnapshot
   */
  trialEnd?: Date | null;
}

/**
 * Check if a given object implements the CheckoutPriceSnapshot interface.
 */
export function instanceOfCheckoutPriceSnapshot(
  value: object,
): value is CheckoutPriceSnapshot {
  if (!("amountOff" in value) || value["amountOff"] === undefined) return false;
  if (!("dueNow" in value) || value["dueNow"] === undefined) return false;
  if (
    !("isScheduledDowngrade" in value) ||
    value["isScheduledDowngrade"] === undefined
  )
    return false;
  if (!("newCharges" in value) || value["newCharges"] === undefined)
    return false;
  if (!("optInRequired" in value) || value["optInRequired"] === undefined)
    return false;
  if (
    !("paymentMethodRequired" in value) ||
    value["paymentMethodRequired"] === undefined
  )
    return false;
  if (!("percentOff" in value) || value["percentOff"] === undefined)
    return false;
  if (!("periodStart" in value) || value["periodStart"] === undefined)
    return false;
  if (!("pricedAt" in value) || value["pricedAt"] === undefined) return false;
  if (!("promoCodeApplied" in value) || value["promoCodeApplied"] === undefined)
    return false;
  if (!("proration" in value) || value["proration"] === undefined) return false;
  if (
    !("totalPerBillingPeriod" in value) ||
    value["totalPerBillingPeriod"] === undefined
  )
    return false;
  return true;
}

export function CheckoutPriceSnapshotFromJSON(
  json: any,
): CheckoutPriceSnapshot {
  return CheckoutPriceSnapshotFromJSONTyped(json, false);
}

export function CheckoutPriceSnapshotFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CheckoutPriceSnapshot {
  if (json == null) {
    return json;
  }
  return {
    amountOff: json["amount_off"],
    dueNow: json["due_now"],
    isScheduledDowngrade: json["is_scheduled_downgrade"],
    newCharges: json["new_charges"],
    optInRequired: json["opt_in_required"],
    paymentMethodRequired: json["payment_method_required"],
    percentOff: json["percent_off"],
    periodStart: new Date(json["period_start"]),
    pricedAt: new Date(json["priced_at"]),
    promoCodeApplied: json["promo_code_applied"],
    proration: json["proration"],
    scheduledChangeTime:
      json["scheduled_change_time"] == null
        ? undefined
        : new Date(json["scheduled_change_time"]),
    taxAmount: json["tax_amount"] == null ? undefined : json["tax_amount"],
    totalPerBillingPeriod: json["total_per_billing_period"],
    trialEnd:
      json["trial_end"] == null ? undefined : new Date(json["trial_end"]),
  };
}

export function CheckoutPriceSnapshotToJSON(json: any): CheckoutPriceSnapshot {
  return CheckoutPriceSnapshotToJSONTyped(json, false);
}

export function CheckoutPriceSnapshotToJSONTyped(
  value?: CheckoutPriceSnapshot | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    amount_off: value["amountOff"],
    due_now: value["dueNow"],
    is_scheduled_downgrade: value["isScheduledDowngrade"],
    new_charges: value["newCharges"],
    opt_in_required: value["optInRequired"],
    payment_method_required: value["paymentMethodRequired"],
    percent_off: value["percentOff"],
    period_start: value["periodStart"].toISOString(),
    priced_at: value["pricedAt"].toISOString(),
    promo_code_applied: value["promoCodeApplied"],
    proration: value["proration"],
    scheduled_change_time:
      value["scheduledChangeTime"] == null
        ? undefined
        : (value["scheduledChangeTime"] as any).toISOString(),
    tax_amount: value["taxAmount"],
    total_per_billing_period: value["totalPerBillingPeriod"],
    trial_end:
      value["trialEnd"] == null
        ? undefined
        : (value["trialEnd"] as any).toISOString(),
  };
}
