/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CheckoutPriceSnapshot } from "./CheckoutPriceSnapshot";
import {
  CheckoutPriceSnapshotFromJSON,
  CheckoutPriceSnapshotFromJSONTyped,
  CheckoutPriceSnapshotToJSON,
  CheckoutPriceSnapshotToJSONTyped,
} from "./CheckoutPriceSnapshot";
import type { CheckoutStatus } from "./CheckoutStatus";
import {
  CheckoutStatusFromJSON,
  CheckoutStatusFromJSONTyped,
  CheckoutStatusToJSON,
  CheckoutStatusToJSONTyped,
} from "./CheckoutStatus";
import type { CheckoutSelectionsResponseData } from "./CheckoutSelectionsResponseData";
import {
  CheckoutSelectionsResponseDataFromJSON,
  CheckoutSelectionsResponseDataFromJSONTyped,
  CheckoutSelectionsResponseDataToJSON,
  CheckoutSelectionsResponseDataToJSONTyped,
} from "./CheckoutSelectionsResponseData";
import type { Problem } from "./Problem";
import {
  ProblemFromJSON,
  ProblemFromJSONTyped,
  ProblemToJSON,
  ProblemToJSONTyped,
} from "./Problem";

/**
 *
 * @export
 * @interface CheckoutDraftResponseData
 */
export interface CheckoutDraftResponseData {
  /**
   *
   * @type {string}
   * @memberof CheckoutDraftResponseData
   */
  companyId: string;
  /**
   *
   * @type {Date}
   * @memberof CheckoutDraftResponseData
   */
  completedAt?: Date | null;
  /**
   *
   * @type {Date}
   * @memberof CheckoutDraftResponseData
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof CheckoutDraftResponseData
   */
  expiresAt?: Date | null;
  /**
   *
   * @type {string}
   * @memberof CheckoutDraftResponseData
   */
  id: string;
  /**
   *
   * @type {Date}
   * @memberof CheckoutDraftResponseData
   */
  lastActivityAt: Date;
  /**
   *
   * @type {CheckoutPriceSnapshot}
   * @memberof CheckoutDraftResponseData
   */
  priceSnapshot?: CheckoutPriceSnapshot;
  /**
   *
   * @type {Date}
   * @memberof CheckoutDraftResponseData
   */
  pricedAt?: Date | null;
  /**
   *
   * @type {Array<Problem>}
   * @memberof CheckoutDraftResponseData
   */
  problems: Array<Problem>;
  /**
   *
   * @type {CheckoutSelectionsResponseData}
   * @memberof CheckoutDraftResponseData
   */
  selections: CheckoutSelectionsResponseData;
  /**
   *
   * @type {string}
   * @memberof CheckoutDraftResponseData
   */
  shareToken?: string | null;
  /**
   *
   * @type {CheckoutStatus}
   * @memberof CheckoutDraftResponseData
   */
  status: CheckoutStatus;
  /**
   *
   * @type {Date}
   * @memberof CheckoutDraftResponseData
   */
  updatedAt: Date;
  /**
   *
   * @type {number}
   * @memberof CheckoutDraftResponseData
   */
  version: number;
}

/**
 * Check if a given object implements the CheckoutDraftResponseData interface.
 */
export function instanceOfCheckoutDraftResponseData(
  value: object,
): value is CheckoutDraftResponseData {
  if (!("companyId" in value) || value["companyId"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("lastActivityAt" in value) || value["lastActivityAt"] === undefined)
    return false;
  if (!("problems" in value) || value["problems"] === undefined) return false;
  if (!("selections" in value) || value["selections"] === undefined)
    return false;
  if (!("status" in value) || value["status"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  if (!("version" in value) || value["version"] === undefined) return false;
  return true;
}

export function CheckoutDraftResponseDataFromJSON(
  json: any,
): CheckoutDraftResponseData {
  return CheckoutDraftResponseDataFromJSONTyped(json, false);
}

export function CheckoutDraftResponseDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CheckoutDraftResponseData {
  if (json == null) {
    return json;
  }
  return {
    companyId: json["company_id"],
    completedAt:
      json["completed_at"] == null ? undefined : new Date(json["completed_at"]),
    createdAt: new Date(json["created_at"]),
    expiresAt:
      json["expires_at"] == null ? undefined : new Date(json["expires_at"]),
    id: json["id"],
    lastActivityAt: new Date(json["last_activity_at"]),
    priceSnapshot:
      json["price_snapshot"] == null
        ? undefined
        : CheckoutPriceSnapshotFromJSON(json["price_snapshot"]),
    pricedAt:
      json["priced_at"] == null ? undefined : new Date(json["priced_at"]),
    problems: (json["problems"] as Array<any>).map(ProblemFromJSON),
    selections: CheckoutSelectionsResponseDataFromJSON(json["selections"]),
    shareToken: json["share_token"] == null ? undefined : json["share_token"],
    status: CheckoutStatusFromJSON(json["status"]),
    updatedAt: new Date(json["updated_at"]),
    version: json["version"],
  };
}

export function CheckoutDraftResponseDataToJSON(
  json: any,
): CheckoutDraftResponseData {
  return CheckoutDraftResponseDataToJSONTyped(json, false);
}

export function CheckoutDraftResponseDataToJSONTyped(
  value?: CheckoutDraftResponseData | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    company_id: value["companyId"],
    completed_at:
      value["completedAt"] == null
        ? undefined
        : (value["completedAt"] as any).toISOString(),
    created_at: value["createdAt"].toISOString(),
    expires_at:
      value["expiresAt"] == null
        ? undefined
        : (value["expiresAt"] as any).toISOString(),
    id: value["id"],
    last_activity_at: value["lastActivityAt"].toISOString(),
    price_snapshot: CheckoutPriceSnapshotToJSON(value["priceSnapshot"]),
    priced_at:
      value["pricedAt"] == null
        ? undefined
        : (value["pricedAt"] as any).toISOString(),
    problems: (value["problems"] as Array<any>).map(ProblemToJSON),
    selections: CheckoutSelectionsResponseDataToJSON(value["selections"]),
    share_token: value["shareToken"],
    status: CheckoutStatusToJSON(value["status"]),
    updated_at: value["updatedAt"].toISOString(),
    version: value["version"],
  };
}
