/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { BillingCollectionMethod } from "./BillingCollectionMethod";
import {
  BillingCollectionMethodFromJSON,
  BillingCollectionMethodFromJSONTyped,
  BillingCollectionMethodToJSON,
  BillingCollectionMethodToJSONTyped,
} from "./BillingCollectionMethod";
import type { ProrationBehavior } from "./ProrationBehavior";
import {
  ProrationBehaviorFromJSON,
  ProrationBehaviorFromJSONTyped,
  ProrationBehaviorToJSON,
  ProrationBehaviorToJSONTyped,
} from "./ProrationBehavior";
import type { BillingProviderType } from "./BillingProviderType";
import {
  BillingProviderTypeFromJSON,
  BillingProviderTypeFromJSONTyped,
  BillingProviderTypeToJSON,
  BillingProviderTypeToJSONTyped,
} from "./BillingProviderType";

/**
 *
 * @export
 * @interface CompanyBillingProfileResponseData
 */
export interface CompanyBillingProfileResponseData {
  /**
   *
   * @type {string}
   * @memberof CompanyBillingProfileResponseData
   */
  accountId: string;
  /**
   *
   * @type {string}
   * @memberof CompanyBillingProfileResponseData
   */
  billingCustomerId?: string | null;
  /**
   *
   * @type {BillingCollectionMethod}
   * @memberof CompanyBillingProfileResponseData
   */
  collectionMethod: BillingCollectionMethod;
  /**
   *
   * @type {string}
   * @memberof CompanyBillingProfileResponseData
   */
  companyId: string;
  /**
   *
   * @type {Date}
   * @memberof CompanyBillingProfileResponseData
   */
  createdAt: Date;
  /**
   *
   * @type {number}
   * @memberof CompanyBillingProfileResponseData
   */
  daysUntilDue?: number | null;
  /**
   *
   * @type {string}
   * @memberof CompanyBillingProfileResponseData
   */
  environmentId: string;
  /**
   *
   * @type {string}
   * @memberof CompanyBillingProfileResponseData
   */
  id: string;
  /**
   *
   * @type {boolean}
   * @memberof CompanyBillingProfileResponseData
   */
  isDefault: boolean;
  /**
   *
   * @type {string}
   * @memberof CompanyBillingProfileResponseData
   */
  name?: string | null;
  /**
   *
   * @type {string}
   * @memberof CompanyBillingProfileResponseData
   */
  paymentMethodId?: string | null;
  /**
   *
   * @type {ProrationBehavior}
   * @memberof CompanyBillingProfileResponseData
   */
  prorationBehavior?: ProrationBehavior | null;
  /**
   *
   * @type {BillingProviderType}
   * @memberof CompanyBillingProfileResponseData
   */
  providerType: BillingProviderType;
  /**
   *
   * @type {Date}
   * @memberof CompanyBillingProfileResponseData
   */
  updatedAt: Date;
}

/**
 * Check if a given object implements the CompanyBillingProfileResponseData interface.
 */
export function instanceOfCompanyBillingProfileResponseData(
  value: object,
): value is CompanyBillingProfileResponseData {
  if (!("accountId" in value) || value["accountId"] === undefined) return false;
  if (!("collectionMethod" in value) || value["collectionMethod"] === undefined)
    return false;
  if (!("companyId" in value) || value["companyId"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("environmentId" in value) || value["environmentId"] === undefined)
    return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("isDefault" in value) || value["isDefault"] === undefined) return false;
  if (!("providerType" in value) || value["providerType"] === undefined)
    return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  return true;
}

export function CompanyBillingProfileResponseDataFromJSON(
  json: any,
): CompanyBillingProfileResponseData {
  return CompanyBillingProfileResponseDataFromJSONTyped(json, false);
}

export function CompanyBillingProfileResponseDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CompanyBillingProfileResponseData {
  if (json == null) {
    return json;
  }
  return {
    accountId: json["account_id"],
    billingCustomerId:
      json["billing_customer_id"] == null
        ? undefined
        : json["billing_customer_id"],
    collectionMethod: BillingCollectionMethodFromJSON(
      json["collection_method"],
    ),
    companyId: json["company_id"],
    createdAt: new Date(json["created_at"]),
    daysUntilDue:
      json["days_until_due"] == null ? undefined : json["days_until_due"],
    environmentId: json["environment_id"],
    id: json["id"],
    isDefault: json["is_default"],
    name: json["name"] == null ? undefined : json["name"],
    paymentMethodId:
      json["payment_method_id"] == null ? undefined : json["payment_method_id"],
    prorationBehavior:
      json["proration_behavior"] == null
        ? undefined
        : ProrationBehaviorFromJSON(json["proration_behavior"]),
    providerType: BillingProviderTypeFromJSON(json["provider_type"]),
    updatedAt: new Date(json["updated_at"]),
  };
}

export function CompanyBillingProfileResponseDataToJSON(
  json: any,
): CompanyBillingProfileResponseData {
  return CompanyBillingProfileResponseDataToJSONTyped(json, false);
}

export function CompanyBillingProfileResponseDataToJSONTyped(
  value?: CompanyBillingProfileResponseData | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    account_id: value["accountId"],
    billing_customer_id: value["billingCustomerId"],
    collection_method: BillingCollectionMethodToJSON(value["collectionMethod"]),
    company_id: value["companyId"],
    created_at: value["createdAt"].toISOString(),
    days_until_due: value["daysUntilDue"],
    environment_id: value["environmentId"],
    id: value["id"],
    is_default: value["isDefault"],
    name: value["name"],
    payment_method_id: value["paymentMethodId"],
    proration_behavior: ProrationBehaviorToJSON(value["prorationBehavior"]),
    provider_type: BillingProviderTypeToJSON(value["providerType"]),
    updated_at: value["updatedAt"].toISOString(),
  };
}
