/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CompanyUserUsageResponseData } from "./CompanyUserUsageResponseData";
import {
  CompanyUserUsageResponseDataFromJSON,
  CompanyUserUsageResponseDataFromJSONTyped,
  CompanyUserUsageResponseDataToJSON,
  CompanyUserUsageResponseDataToJSONTyped,
} from "./CompanyUserUsageResponseData";

/**
 *
 * @export
 * @interface CompanyFeatureUserUsageResponseData
 */
export interface CompanyFeatureUserUsageResponseData {
  /**
   * How many of the company's users the breakdown lists across every page, including those without usage in the period; unattributed usage is not a user and is not counted.
   * @type {number}
   * @memberof CompanyFeatureUserUsageResponseData
   */
  count: number;
  /**
   * End of the feature's current metric period (exclusive).
   * @type {Date}
   * @memberof CompanyFeatureUserUsageResponseData
   */
  endTime: Date;
  /**
   * Start of the feature's current metric period.
   * @type {Date}
   * @memberof CompanyFeatureUserUsageResponseData
   */
  startTime: Date;
  /**
   * Usage across every user in the period, not just this page.
   * @type {number}
   * @memberof CompanyFeatureUserUsageResponseData
   */
  total: number;
  /**
   * Usage from events sent without a user; null when the period has none.
   * @type {number}
   * @memberof CompanyFeatureUserUsageResponseData
   */
  unattributed?: number | null;
  /**
   * This page of users, highest usage first.
   * @type {Array<CompanyUserUsageResponseData>}
   * @memberof CompanyFeatureUserUsageResponseData
   */
  users: Array<CompanyUserUsageResponseData>;
}

/**
 * Check if a given object implements the CompanyFeatureUserUsageResponseData interface.
 */
export function instanceOfCompanyFeatureUserUsageResponseData(
  value: object,
): value is CompanyFeatureUserUsageResponseData {
  if (!("count" in value) || value["count"] === undefined) return false;
  if (!("endTime" in value) || value["endTime"] === undefined) return false;
  if (!("startTime" in value) || value["startTime"] === undefined) return false;
  if (!("total" in value) || value["total"] === undefined) return false;
  if (!("users" in value) || value["users"] === undefined) return false;
  return true;
}

export function CompanyFeatureUserUsageResponseDataFromJSON(
  json: any,
): CompanyFeatureUserUsageResponseData {
  return CompanyFeatureUserUsageResponseDataFromJSONTyped(json, false);
}

export function CompanyFeatureUserUsageResponseDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CompanyFeatureUserUsageResponseData {
  if (json == null) {
    return json;
  }
  return {
    count: json["count"],
    endTime: new Date(json["end_time"]),
    startTime: new Date(json["start_time"]),
    total: json["total"],
    unattributed:
      json["unattributed"] == null ? undefined : json["unattributed"],
    users: (json["users"] as Array<any>).map(
      CompanyUserUsageResponseDataFromJSON,
    ),
  };
}

export function CompanyFeatureUserUsageResponseDataToJSON(
  json: any,
): CompanyFeatureUserUsageResponseData {
  return CompanyFeatureUserUsageResponseDataToJSONTyped(json, false);
}

export function CompanyFeatureUserUsageResponseDataToJSONTyped(
  value?: CompanyFeatureUserUsageResponseData | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    count: value["count"],
    end_time: value["endTime"].toISOString(),
    start_time: value["startTime"].toISOString(),
    total: value["total"],
    unattributed: value["unattributed"],
    users: (value["users"] as Array<any>).map(
      CompanyUserUsageResponseDataToJSON,
    ),
  };
}
