/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ComponentEntityType } from "./ComponentEntityType";
import {
  ComponentEntityTypeFromJSON,
  ComponentEntityTypeFromJSONTyped,
  ComponentEntityTypeToJSON,
} from "./ComponentEntityType";
import type { ComponentState } from "./ComponentState";
import {
  ComponentStateFromJSON,
  ComponentStateFromJSONTyped,
  ComponentStateToJSON,
} from "./ComponentState";

/**
 *
 * @export
 * @interface ComponentResponseData
 */
export interface ComponentResponseData {
  /**
   *
   * @type {{ [key: string]: number; }}
   * @memberof ComponentResponseData
   */
  ast?: { [key: string]: number };
  /**
   *
   * @type {Date}
   * @memberof ComponentResponseData
   */
  createdAt: Date;
  /**
   *
   * @type {string}
   * @memberof ComponentResponseData
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof ComponentResponseData
   */
  name: string;
  /**
   *
   * @type {ComponentState}
   * @memberof ComponentResponseData
   */
  state: ComponentState;
  /**
   *
   * @type {ComponentEntityType}
   * @memberof ComponentResponseData
   */
  type: ComponentEntityType;
  /**
   *
   * @type {Date}
   * @memberof ComponentResponseData
   */
  updatedAt: Date;
}

/**
 * Check if a given object implements the ComponentResponseData interface.
 */
export function instanceOfComponentResponseData(
  value: object,
): value is ComponentResponseData {
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("state" in value) || value["state"] === undefined) return false;
  if (!("type" in value) || value["type"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  return true;
}

export function ComponentResponseDataFromJSON(
  json: any,
): ComponentResponseData {
  return ComponentResponseDataFromJSONTyped(json, false);
}

export function ComponentResponseDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ComponentResponseData {
  if (json == null) {
    return json;
  }
  return {
    ast: json["ast"] == null ? undefined : json["ast"],
    createdAt: new Date(json["created_at"]),
    id: json["id"],
    name: json["name"],
    state: ComponentStateFromJSON(json["state"]),
    type: ComponentEntityTypeFromJSON(json["type"]),
    updatedAt: new Date(json["updated_at"]),
  };
}

export function ComponentResponseDataToJSON(
  value?: ComponentResponseData | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    ast: value["ast"],
    created_at: value["createdAt"].toISOString(),
    id: value["id"],
    name: value["name"],
    state: ComponentStateToJSON(value["state"]),
    type: ComponentEntityTypeToJSON(value["type"]),
    updated_at: value["updatedAt"].toISOString(),
  };
}
