/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const ComponentEntityType = {
  Billing: "billing",
  Entitlement: "entitlement",
} as const;
export type ComponentEntityType =
  (typeof ComponentEntityType)[keyof typeof ComponentEntityType];

export function instanceOfComponentEntityType(value: any): boolean {
  for (const key in ComponentEntityType) {
    if (Object.prototype.hasOwnProperty.call(ComponentEntityType, key)) {
      if (
        (ComponentEntityType as Record<string, ComponentEntityType>)[key] ===
        value
      ) {
        return true;
      }
    }
  }
  return false;
}

export function ComponentEntityTypeFromJSON(json: any): ComponentEntityType {
  return ComponentEntityTypeFromJSONTyped(json, false);
}

export function ComponentEntityTypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ComponentEntityType {
  return json as ComponentEntityType;
}

export function ComponentEntityTypeToJSON(
  value?: ComponentEntityType | null,
): any {
  return value as any;
}
