/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ComponentDisplaySettings
 */
export interface ComponentDisplaySettings {
  /**
   *
   * @type {boolean}
   * @memberof ComponentDisplaySettings
   */
  showAsMonthlyPrices: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ComponentDisplaySettings
   */
  showCredits: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ComponentDisplaySettings
   */
  showFeatureDescription: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ComponentDisplaySettings
   */
  showPeriodToggle: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ComponentDisplaySettings
   */
  showZeroPriceAsFree: boolean;
}

/**
 * Check if a given object implements the ComponentDisplaySettings interface.
 */
export function instanceOfComponentDisplaySettings(
  value: object,
): value is ComponentDisplaySettings {
  if (
    !("showAsMonthlyPrices" in value) ||
    value["showAsMonthlyPrices"] === undefined
  )
    return false;
  if (!("showCredits" in value) || value["showCredits"] === undefined)
    return false;
  if (
    !("showFeatureDescription" in value) ||
    value["showFeatureDescription"] === undefined
  )
    return false;
  if (!("showPeriodToggle" in value) || value["showPeriodToggle"] === undefined)
    return false;
  if (
    !("showZeroPriceAsFree" in value) ||
    value["showZeroPriceAsFree"] === undefined
  )
    return false;
  return true;
}

export function ComponentDisplaySettingsFromJSON(
  json: any,
): ComponentDisplaySettings {
  return ComponentDisplaySettingsFromJSONTyped(json, false);
}

export function ComponentDisplaySettingsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ComponentDisplaySettings {
  if (json == null) {
    return json;
  }
  return {
    showAsMonthlyPrices: json["show_as_monthly_prices"],
    showCredits: json["show_credits"],
    showFeatureDescription: json["show_feature_description"],
    showPeriodToggle: json["show_period_toggle"],
    showZeroPriceAsFree: json["show_zero_price_as_free"],
  };
}

export function ComponentDisplaySettingsToJSON(
  value?: ComponentDisplaySettings | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    show_as_monthly_prices: value["showAsMonthlyPrices"],
    show_credits: value["showCredits"],
    show_feature_description: value["showFeatureDescription"],
    show_period_toggle: value["showPeriodToggle"],
    show_zero_price_as_free: value["showZeroPriceAsFree"],
  };
}
