/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Confirm3DSRequestBody
 */
export interface Confirm3DSRequestBody {
  /**
   *
   * @type {string}
   * @memberof Confirm3DSRequestBody
   */
  paymentIntentId: string;
}

/**
 * Check if a given object implements the Confirm3DSRequestBody interface.
 */
export function instanceOfConfirm3DSRequestBody(
  value: object,
): value is Confirm3DSRequestBody {
  if (!("paymentIntentId" in value) || value["paymentIntentId"] === undefined)
    return false;
  return true;
}

export function Confirm3DSRequestBodyFromJSON(
  json: any,
): Confirm3DSRequestBody {
  return Confirm3DSRequestBodyFromJSONTyped(json, false);
}

export function Confirm3DSRequestBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Confirm3DSRequestBody {
  if (json == null) {
    return json;
  }
  return {
    paymentIntentId: json["payment_intent_id"],
  };
}

export function Confirm3DSRequestBodyToJSON(
  value?: Confirm3DSRequestBody | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    payment_intent_id: value["paymentIntentId"],
  };
}
