/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CheckoutDraftResponseData } from "./CheckoutDraftResponseData";
import {
  CheckoutDraftResponseDataFromJSON,
  CheckoutDraftResponseDataFromJSONTyped,
  CheckoutDraftResponseDataToJSON,
  CheckoutDraftResponseDataToJSONTyped,
} from "./CheckoutDraftResponseData";

/**
 *
 * @export
 * @interface CreateCheckoutResponse
 */
export interface CreateCheckoutResponse {
  /**
   *
   * @type {CheckoutDraftResponseData}
   * @memberof CreateCheckoutResponse
   */
  data: CheckoutDraftResponseData;
  /**
   * Input parameters
   * @type {object}
   * @memberof CreateCheckoutResponse
   */
  params: object;
}

/**
 * Check if a given object implements the CreateCheckoutResponse interface.
 */
export function instanceOfCreateCheckoutResponse(
  value: object,
): value is CreateCheckoutResponse {
  if (!("data" in value) || value["data"] === undefined) return false;
  if (!("params" in value) || value["params"] === undefined) return false;
  return true;
}

export function CreateCheckoutResponseFromJSON(
  json: any,
): CreateCheckoutResponse {
  return CreateCheckoutResponseFromJSONTyped(json, false);
}

export function CreateCheckoutResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateCheckoutResponse {
  if (json == null) {
    return json;
  }
  return {
    data: CheckoutDraftResponseDataFromJSON(json["data"]),
    params: json["params"],
  };
}

export function CreateCheckoutResponseToJSON(
  json: any,
): CreateCheckoutResponse {
  return CreateCheckoutResponseToJSONTyped(json, false);
}

export function CreateCheckoutResponseToJSONTyped(
  value?: CreateCheckoutResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data: CheckoutDraftResponseDataToJSON(value["data"]),
    params: value["params"],
  };
}
