/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { UpdatePayInAdvanceRequestBody } from "./UpdatePayInAdvanceRequestBody";
import {
  UpdatePayInAdvanceRequestBodyFromJSON,
  UpdatePayInAdvanceRequestBodyFromJSONTyped,
  UpdatePayInAdvanceRequestBodyToJSON,
  UpdatePayInAdvanceRequestBodyToJSONTyped,
} from "./UpdatePayInAdvanceRequestBody";
import type { UpdateCreditBundleRequestBody } from "./UpdateCreditBundleRequestBody";
import {
  UpdateCreditBundleRequestBodyFromJSON,
  UpdateCreditBundleRequestBodyFromJSONTyped,
  UpdateCreditBundleRequestBodyToJSON,
  UpdateCreditBundleRequestBodyToJSONTyped,
} from "./UpdateCreditBundleRequestBody";
import type { CheckoutFieldValue } from "./CheckoutFieldValue";
import {
  CheckoutFieldValueFromJSON,
  CheckoutFieldValueFromJSONTyped,
  CheckoutFieldValueToJSON,
  CheckoutFieldValueToJSONTyped,
} from "./CheckoutFieldValue";
import type { UpdateAddOnRequestBody } from "./UpdateAddOnRequestBody";
import {
  UpdateAddOnRequestBodyFromJSON,
  UpdateAddOnRequestBodyFromJSONTyped,
  UpdateAddOnRequestBodyToJSON,
  UpdateAddOnRequestBodyToJSONTyped,
} from "./UpdateAddOnRequestBody";
import type { UpdateAutoTopupOverrideRequestBody } from "./UpdateAutoTopupOverrideRequestBody";
import {
  UpdateAutoTopupOverrideRequestBodyFromJSON,
  UpdateAutoTopupOverrideRequestBodyFromJSONTyped,
  UpdateAutoTopupOverrideRequestBodyToJSON,
  UpdateAutoTopupOverrideRequestBodyToJSONTyped,
} from "./UpdateAutoTopupOverrideRequestBody";

/**
 *
 * @export
 * @interface CreateCheckoutRequest
 */
export interface CreateCheckoutRequest {
  /**
   *
   * @type {Array<UpdateAddOnRequestBody>}
   * @memberof CreateCheckoutRequest
   */
  addOnIds: Array<UpdateAddOnRequestBody>;
  /**
   *
   * @type {Array<UpdateAutoTopupOverrideRequestBody>}
   * @memberof CreateCheckoutRequest
   */
  autoTopupOverrides: Array<UpdateAutoTopupOverrideRequestBody>;
  /**
   *
   * @type {string}
   * @memberof CreateCheckoutRequest
   */
  billingEntityId?: string | null;
  /**
   *
   * @type {string}
   * @memberof CreateCheckoutRequest
   */
  companyId?: string | null;
  /**
   *
   * @type {string}
   * @memberof CreateCheckoutRequest
   */
  couponExternalId?: string | null;
  /**
   *
   * @type {Array<UpdateCreditBundleRequestBody>}
   * @memberof CreateCheckoutRequest
   */
  creditBundles: Array<UpdateCreditBundleRequestBody>;
  /**
   *
   * @type {Array<CheckoutFieldValue>}
   * @memberof CreateCheckoutRequest
   */
  customFieldValues: Array<CheckoutFieldValue>;
  /**
   *
   * @type {boolean}
   * @memberof CreateCheckoutRequest
   */
  generateShareLink: boolean;
  /**
   *
   * @type {string}
   * @memberof CreateCheckoutRequest
   */
  newPlanId: string;
  /**
   *
   * @type {string}
   * @memberof CreateCheckoutRequest
   */
  newPriceId: string;
  /**
   *
   * @type {boolean}
   * @memberof CreateCheckoutRequest
   */
  optInAccepted?: boolean | null;
  /**
   *
   * @type {Array<UpdatePayInAdvanceRequestBody>}
   * @memberof CreateCheckoutRequest
   */
  payInAdvance: Array<UpdatePayInAdvanceRequestBody>;
  /**
   *
   * @type {string}
   * @memberof CreateCheckoutRequest
   */
  paymentMethodId?: string | null;
  /**
   *
   * @type {string}
   * @memberof CreateCheckoutRequest
   */
  promoCode?: string | null;
  /**
   *
   * @type {boolean}
   * @memberof CreateCheckoutRequest
   */
  skipTrial: boolean;
}

/**
 * Check if a given object implements the CreateCheckoutRequest interface.
 */
export function instanceOfCreateCheckoutRequest(
  value: object,
): value is CreateCheckoutRequest {
  if (!("addOnIds" in value) || value["addOnIds"] === undefined) return false;
  if (
    !("autoTopupOverrides" in value) ||
    value["autoTopupOverrides"] === undefined
  )
    return false;
  if (!("creditBundles" in value) || value["creditBundles"] === undefined)
    return false;
  if (
    !("customFieldValues" in value) ||
    value["customFieldValues"] === undefined
  )
    return false;
  if (
    !("generateShareLink" in value) ||
    value["generateShareLink"] === undefined
  )
    return false;
  if (!("newPlanId" in value) || value["newPlanId"] === undefined) return false;
  if (!("newPriceId" in value) || value["newPriceId"] === undefined)
    return false;
  if (!("payInAdvance" in value) || value["payInAdvance"] === undefined)
    return false;
  if (!("skipTrial" in value) || value["skipTrial"] === undefined) return false;
  return true;
}

export function CreateCheckoutRequestFromJSON(
  json: any,
): CreateCheckoutRequest {
  return CreateCheckoutRequestFromJSONTyped(json, false);
}

export function CreateCheckoutRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateCheckoutRequest {
  if (json == null) {
    return json;
  }
  return {
    addOnIds: (json["add_on_ids"] as Array<any>).map(
      UpdateAddOnRequestBodyFromJSON,
    ),
    autoTopupOverrides: (json["auto_topup_overrides"] as Array<any>).map(
      UpdateAutoTopupOverrideRequestBodyFromJSON,
    ),
    billingEntityId:
      json["billing_entity_id"] == null ? undefined : json["billing_entity_id"],
    companyId: json["company_id"] == null ? undefined : json["company_id"],
    couponExternalId:
      json["coupon_external_id"] == null
        ? undefined
        : json["coupon_external_id"],
    creditBundles: (json["credit_bundles"] as Array<any>).map(
      UpdateCreditBundleRequestBodyFromJSON,
    ),
    customFieldValues: (json["custom_field_values"] as Array<any>).map(
      CheckoutFieldValueFromJSON,
    ),
    generateShareLink: json["generate_share_link"],
    newPlanId: json["new_plan_id"],
    newPriceId: json["new_price_id"],
    optInAccepted:
      json["opt_in_accepted"] == null ? undefined : json["opt_in_accepted"],
    payInAdvance: (json["pay_in_advance"] as Array<any>).map(
      UpdatePayInAdvanceRequestBodyFromJSON,
    ),
    paymentMethodId:
      json["payment_method_id"] == null ? undefined : json["payment_method_id"],
    promoCode: json["promo_code"] == null ? undefined : json["promo_code"],
    skipTrial: json["skip_trial"],
  };
}

export function CreateCheckoutRequestToJSON(json: any): CreateCheckoutRequest {
  return CreateCheckoutRequestToJSONTyped(json, false);
}

export function CreateCheckoutRequestToJSONTyped(
  value?: CreateCheckoutRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    add_on_ids: (value["addOnIds"] as Array<any>).map(
      UpdateAddOnRequestBodyToJSON,
    ),
    auto_topup_overrides: (value["autoTopupOverrides"] as Array<any>).map(
      UpdateAutoTopupOverrideRequestBodyToJSON,
    ),
    billing_entity_id: value["billingEntityId"],
    company_id: value["companyId"],
    coupon_external_id: value["couponExternalId"],
    credit_bundles: (value["creditBundles"] as Array<any>).map(
      UpdateCreditBundleRequestBodyToJSON,
    ),
    custom_field_values: (value["customFieldValues"] as Array<any>).map(
      CheckoutFieldValueToJSON,
    ),
    generate_share_link: value["generateShareLink"],
    new_plan_id: value["newPlanId"],
    new_price_id: value["newPriceId"],
    opt_in_accepted: value["optInAccepted"],
    pay_in_advance: (value["payInAdvance"] as Array<any>).map(
      UpdatePayInAdvanceRequestBodyToJSON,
    ),
    payment_method_id: value["paymentMethodId"],
    promo_code: value["promoCode"],
    skip_trial: value["skipTrial"],
  };
}
