/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { BillingPriceResponseData } from "./BillingPriceResponseData";
import {
  BillingPriceResponseDataFromJSON,
  BillingPriceResponseDataFromJSONTyped,
  BillingPriceResponseDataToJSON,
} from "./BillingPriceResponseData";

/**
 *
 * @export
 * @interface EntitlementCurrencyPricesResponseData
 */
export interface EntitlementCurrencyPricesResponseData {
  /**
   *
   * @type {string}
   * @memberof EntitlementCurrencyPricesResponseData
   */
  currency: string;
  /**
   *
   * @type {BillingPriceResponseData}
   * @memberof EntitlementCurrencyPricesResponseData
   */
  monthlyPrice?: BillingPriceResponseData;
  /**
   *
   * @type {BillingPriceResponseData}
   * @memberof EntitlementCurrencyPricesResponseData
   */
  yearlyPrice?: BillingPriceResponseData;
}

/**
 * Check if a given object implements the EntitlementCurrencyPricesResponseData interface.
 */
export function instanceOfEntitlementCurrencyPricesResponseData(
  value: object,
): value is EntitlementCurrencyPricesResponseData {
  if (!("currency" in value) || value["currency"] === undefined) return false;
  return true;
}

export function EntitlementCurrencyPricesResponseDataFromJSON(
  json: any,
): EntitlementCurrencyPricesResponseData {
  return EntitlementCurrencyPricesResponseDataFromJSONTyped(json, false);
}

export function EntitlementCurrencyPricesResponseDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): EntitlementCurrencyPricesResponseData {
  if (json == null) {
    return json;
  }
  return {
    currency: json["currency"],
    monthlyPrice:
      json["monthly_price"] == null
        ? undefined
        : BillingPriceResponseDataFromJSON(json["monthly_price"]),
    yearlyPrice:
      json["yearly_price"] == null
        ? undefined
        : BillingPriceResponseDataFromJSON(json["yearly_price"]),
  };
}

export function EntitlementCurrencyPricesResponseDataToJSON(
  value?: EntitlementCurrencyPricesResponseData | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    currency: value["currency"],
    monthly_price: BillingPriceResponseDataToJSON(value["monthlyPrice"]),
    yearly_price: BillingPriceResponseDataToJSON(value["yearlyPrice"]),
  };
}
