/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { PlanPriceCadence } from "./PlanPriceCadence";
import {
  PlanPriceCadenceFromJSON,
  PlanPriceCadenceFromJSONTyped,
  PlanPriceCadenceToJSON,
  PlanPriceCadenceToJSONTyped,
} from "./PlanPriceCadence";

/**
 *
 * @export
 * @interface EstimatedPlanTotal
 */
export interface EstimatedPlanTotal {
  /**
   *
   * @type {number}
   * @memberof EstimatedPlanTotal
   */
  amount: number;
  /**
   *
   * @type {string}
   * @memberof EstimatedPlanTotal
   */
  currency: string;
  /**
   *
   * @type {PlanPriceCadence}
   * @memberof EstimatedPlanTotal
   */
  period: PlanPriceCadence;
}

/**
 * Check if a given object implements the EstimatedPlanTotal interface.
 */
export function instanceOfEstimatedPlanTotal(
  value: object,
): value is EstimatedPlanTotal {
  if (!("amount" in value) || value["amount"] === undefined) return false;
  if (!("currency" in value) || value["currency"] === undefined) return false;
  if (!("period" in value) || value["period"] === undefined) return false;
  return true;
}

export function EstimatedPlanTotalFromJSON(json: any): EstimatedPlanTotal {
  return EstimatedPlanTotalFromJSONTyped(json, false);
}

export function EstimatedPlanTotalFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): EstimatedPlanTotal {
  if (json == null) {
    return json;
  }
  return {
    amount: json["amount"],
    currency: json["currency"],
    period: PlanPriceCadenceFromJSON(json["period"]),
  };
}

export function EstimatedPlanTotalToJSON(json: any): EstimatedPlanTotal {
  return EstimatedPlanTotalToJSONTyped(json, false);
}

export function EstimatedPlanTotalToJSONTyped(
  value?: EstimatedPlanTotal | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    amount: value["amount"],
    currency: value["currency"],
    period: PlanPriceCadenceToJSON(value["period"]),
  };
}
