/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CompanyPaymentMethodsResponseData } from "./CompanyPaymentMethodsResponseData";
import {
  CompanyPaymentMethodsResponseDataFromJSON,
  CompanyPaymentMethodsResponseDataFromJSONTyped,
  CompanyPaymentMethodsResponseDataToJSON,
  CompanyPaymentMethodsResponseDataToJSONTyped,
} from "./CompanyPaymentMethodsResponseData";

/**
 *
 * @export
 * @interface GetCompanyPaymentMethodsResponse
 */
export interface GetCompanyPaymentMethodsResponse {
  /**
   *
   * @type {CompanyPaymentMethodsResponseData}
   * @memberof GetCompanyPaymentMethodsResponse
   */
  data: CompanyPaymentMethodsResponseData;
  /**
   * Input parameters
   * @type {object}
   * @memberof GetCompanyPaymentMethodsResponse
   */
  params: object;
}

/**
 * Check if a given object implements the GetCompanyPaymentMethodsResponse interface.
 */
export function instanceOfGetCompanyPaymentMethodsResponse(
  value: object,
): value is GetCompanyPaymentMethodsResponse {
  if (!("data" in value) || value["data"] === undefined) return false;
  if (!("params" in value) || value["params"] === undefined) return false;
  return true;
}

export function GetCompanyPaymentMethodsResponseFromJSON(
  json: any,
): GetCompanyPaymentMethodsResponse {
  return GetCompanyPaymentMethodsResponseFromJSONTyped(json, false);
}

export function GetCompanyPaymentMethodsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetCompanyPaymentMethodsResponse {
  if (json == null) {
    return json;
  }
  return {
    data: CompanyPaymentMethodsResponseDataFromJSON(json["data"]),
    params: json["params"],
  };
}

export function GetCompanyPaymentMethodsResponseToJSON(
  json: any,
): GetCompanyPaymentMethodsResponse {
  return GetCompanyPaymentMethodsResponseToJSONTyped(json, false);
}

export function GetCompanyPaymentMethodsResponseToJSONTyped(
  value?: GetCompanyPaymentMethodsResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data: CompanyPaymentMethodsResponseDataToJSON(value["data"]),
    params: value["params"],
  };
}
