/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { GetFeatureUsageByUserParams } from "./GetFeatureUsageByUserParams";
import {
  GetFeatureUsageByUserParamsFromJSON,
  GetFeatureUsageByUserParamsFromJSONTyped,
  GetFeatureUsageByUserParamsToJSON,
  GetFeatureUsageByUserParamsToJSONTyped,
} from "./GetFeatureUsageByUserParams";
import type { FeatureUserUsageResponseData } from "./FeatureUserUsageResponseData";
import {
  FeatureUserUsageResponseDataFromJSON,
  FeatureUserUsageResponseDataFromJSONTyped,
  FeatureUserUsageResponseDataToJSON,
  FeatureUserUsageResponseDataToJSONTyped,
} from "./FeatureUserUsageResponseData";

/**
 *
 * @export
 * @interface GetFeatureUsageByUserResponse
 */
export interface GetFeatureUsageByUserResponse {
  /**
   *
   * @type {FeatureUserUsageResponseData}
   * @memberof GetFeatureUsageByUserResponse
   */
  data: FeatureUserUsageResponseData;
  /**
   *
   * @type {GetFeatureUsageByUserParams}
   * @memberof GetFeatureUsageByUserResponse
   */
  params: GetFeatureUsageByUserParams;
}

/**
 * Check if a given object implements the GetFeatureUsageByUserResponse interface.
 */
export function instanceOfGetFeatureUsageByUserResponse(
  value: object,
): value is GetFeatureUsageByUserResponse {
  if (!("data" in value) || value["data"] === undefined) return false;
  if (!("params" in value) || value["params"] === undefined) return false;
  return true;
}

export function GetFeatureUsageByUserResponseFromJSON(
  json: any,
): GetFeatureUsageByUserResponse {
  return GetFeatureUsageByUserResponseFromJSONTyped(json, false);
}

export function GetFeatureUsageByUserResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetFeatureUsageByUserResponse {
  if (json == null) {
    return json;
  }
  return {
    data: FeatureUserUsageResponseDataFromJSON(json["data"]),
    params: GetFeatureUsageByUserParamsFromJSON(json["params"]),
  };
}

export function GetFeatureUsageByUserResponseToJSON(
  json: any,
): GetFeatureUsageByUserResponse {
  return GetFeatureUsageByUserResponseToJSONTyped(json, false);
}

export function GetFeatureUsageByUserResponseToJSONTyped(
  value?: GetFeatureUsageByUserResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data: FeatureUserUsageResponseDataToJSON(value["data"]),
    params: GetFeatureUsageByUserParamsToJSON(value["params"]),
  };
}
