/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const MigrationProrationBehavior = {
  AlwaysInvoice: "always_invoice",
  CreateProrations: "create_prorations",
  None: "none",
} as const;
export type MigrationProrationBehavior =
  (typeof MigrationProrationBehavior)[keyof typeof MigrationProrationBehavior];

export function instanceOfMigrationProrationBehavior(value: any): boolean {
  for (const key in MigrationProrationBehavior) {
    if (Object.prototype.hasOwnProperty.call(MigrationProrationBehavior, key)) {
      if (
        MigrationProrationBehavior[
          key as keyof typeof MigrationProrationBehavior
        ] === value
      ) {
        return true;
      }
    }
  }
  return false;
}

export function MigrationProrationBehaviorFromJSON(
  json: any,
): MigrationProrationBehavior {
  return MigrationProrationBehaviorFromJSONTyped(json, false);
}

export function MigrationProrationBehaviorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MigrationProrationBehavior {
  return json as MigrationProrationBehavior;
}

export function MigrationProrationBehaviorToJSON(
  value?: MigrationProrationBehavior | null,
): any {
  return value as any;
}

export function MigrationProrationBehaviorToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean,
): MigrationProrationBehavior {
  return value as MigrationProrationBehavior;
}
