/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { PreviewSubscriptionUpcomingInvoiceLineItems } from "./PreviewSubscriptionUpcomingInvoiceLineItems";
import {
  PreviewSubscriptionUpcomingInvoiceLineItemsFromJSON,
  PreviewSubscriptionUpcomingInvoiceLineItemsFromJSONTyped,
  PreviewSubscriptionUpcomingInvoiceLineItemsToJSON,
} from "./PreviewSubscriptionUpcomingInvoiceLineItems";

/**
 *
 * @export
 * @interface PreviewSubscriptionFinanceResponseData
 */
export interface PreviewSubscriptionFinanceResponseData {
  /**
   *
   * @type {number}
   * @memberof PreviewSubscriptionFinanceResponseData
   */
  amountOff: number;
  /**
   *
   * @type {number}
   * @memberof PreviewSubscriptionFinanceResponseData
   */
  dueNow: number;
  /**
   *
   * @type {number}
   * @memberof PreviewSubscriptionFinanceResponseData
   */
  newCharges: number;
  /**
   *
   * @type {number}
   * @memberof PreviewSubscriptionFinanceResponseData
   */
  percentOff: number;
  /**
   *
   * @type {Date}
   * @memberof PreviewSubscriptionFinanceResponseData
   */
  periodStart: Date;
  /**
   *
   * @type {boolean}
   * @memberof PreviewSubscriptionFinanceResponseData
   */
  promoCodeApplied: boolean;
  /**
   *
   * @type {number}
   * @memberof PreviewSubscriptionFinanceResponseData
   */
  proration: number;
  /**
   *
   * @type {number}
   * @memberof PreviewSubscriptionFinanceResponseData
   */
  taxAmount?: number | null;
  /**
   *
   * @type {string}
   * @memberof PreviewSubscriptionFinanceResponseData
   */
  taxDisplayName?: string | null;
  /**
   *
   * @type {boolean}
   * @memberof PreviewSubscriptionFinanceResponseData
   */
  taxRequireBillingDetails: boolean;
  /**
   *
   * @type {Date}
   * @memberof PreviewSubscriptionFinanceResponseData
   */
  trialEnd?: Date | null;
  /**
   *
   * @type {Array<PreviewSubscriptionUpcomingInvoiceLineItems>}
   * @memberof PreviewSubscriptionFinanceResponseData
   */
  upcomingInvoiceLineItems: Array<PreviewSubscriptionUpcomingInvoiceLineItems>;
}

/**
 * Check if a given object implements the PreviewSubscriptionFinanceResponseData interface.
 */
export function instanceOfPreviewSubscriptionFinanceResponseData(
  value: object,
): value is PreviewSubscriptionFinanceResponseData {
  if (!("amountOff" in value) || value["amountOff"] === undefined) return false;
  if (!("dueNow" in value) || value["dueNow"] === undefined) return false;
  if (!("newCharges" in value) || value["newCharges"] === undefined)
    return false;
  if (!("percentOff" in value) || value["percentOff"] === undefined)
    return false;
  if (!("periodStart" in value) || value["periodStart"] === undefined)
    return false;
  if (!("promoCodeApplied" in value) || value["promoCodeApplied"] === undefined)
    return false;
  if (!("proration" in value) || value["proration"] === undefined) return false;
  if (
    !("taxRequireBillingDetails" in value) ||
    value["taxRequireBillingDetails"] === undefined
  )
    return false;
  if (
    !("upcomingInvoiceLineItems" in value) ||
    value["upcomingInvoiceLineItems"] === undefined
  )
    return false;
  return true;
}

export function PreviewSubscriptionFinanceResponseDataFromJSON(
  json: any,
): PreviewSubscriptionFinanceResponseData {
  return PreviewSubscriptionFinanceResponseDataFromJSONTyped(json, false);
}

export function PreviewSubscriptionFinanceResponseDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PreviewSubscriptionFinanceResponseData {
  if (json == null) {
    return json;
  }
  return {
    amountOff: json["amount_off"],
    dueNow: json["due_now"],
    newCharges: json["new_charges"],
    percentOff: json["percent_off"],
    periodStart: new Date(json["period_start"]),
    promoCodeApplied: json["promo_code_applied"],
    proration: json["proration"],
    taxAmount: json["tax_amount"] == null ? undefined : json["tax_amount"],
    taxDisplayName:
      json["tax_display_name"] == null ? undefined : json["tax_display_name"],
    taxRequireBillingDetails: json["tax_require_billing_details"],
    trialEnd:
      json["trial_end"] == null ? undefined : new Date(json["trial_end"]),
    upcomingInvoiceLineItems: (
      json["upcoming_invoice_line_items"] as Array<any>
    ).map(PreviewSubscriptionUpcomingInvoiceLineItemsFromJSON),
  };
}

export function PreviewSubscriptionFinanceResponseDataToJSON(
  value?: PreviewSubscriptionFinanceResponseData | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    amount_off: value["amountOff"],
    due_now: value["dueNow"],
    new_charges: value["newCharges"],
    percent_off: value["percentOff"],
    period_start: value["periodStart"].toISOString(),
    promo_code_applied: value["promoCodeApplied"],
    proration: value["proration"],
    tax_amount: value["taxAmount"],
    tax_display_name: value["taxDisplayName"],
    tax_require_billing_details: value["taxRequireBillingDetails"],
    trial_end:
      value["trialEnd"] == null
        ? undefined
        : (value["trialEnd"] as any).toISOString(),
    upcoming_invoice_line_items: (
      value["upcomingInvoiceLineItems"] as Array<any>
    ).map(PreviewSubscriptionUpcomingInvoiceLineItemsToJSON),
  };
}
