/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { PreviewSubscriptionChangeResponseData } from "./PreviewSubscriptionChangeResponseData";
import {
  PreviewSubscriptionChangeResponseDataFromJSON,
  PreviewSubscriptionChangeResponseDataFromJSONTyped,
  PreviewSubscriptionChangeResponseDataToJSON,
} from "./PreviewSubscriptionChangeResponseData";

/**
 *
 * @export
 * @interface PreviewCheckoutResponse
 */
export interface PreviewCheckoutResponse {
  /**
   *
   * @type {PreviewSubscriptionChangeResponseData}
   * @memberof PreviewCheckoutResponse
   */
  data: PreviewSubscriptionChangeResponseData;
  /**
   * Input parameters
   * @type {object}
   * @memberof PreviewCheckoutResponse
   */
  params: object;
}

/**
 * Check if a given object implements the PreviewCheckoutResponse interface.
 */
export function instanceOfPreviewCheckoutResponse(
  value: object,
): value is PreviewCheckoutResponse {
  if (!("data" in value) || value["data"] === undefined) return false;
  if (!("params" in value) || value["params"] === undefined) return false;
  return true;
}

export function PreviewCheckoutResponseFromJSON(
  json: any,
): PreviewCheckoutResponse {
  return PreviewCheckoutResponseFromJSONTyped(json, false);
}

export function PreviewCheckoutResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PreviewCheckoutResponse {
  if (json == null) {
    return json;
  }
  return {
    data: PreviewSubscriptionChangeResponseDataFromJSON(json["data"]),
    params: json["params"],
  };
}

export function PreviewCheckoutResponseToJSON(
  value?: PreviewCheckoutResponse | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    data: PreviewSubscriptionChangeResponseDataToJSON(value["data"]),
    params: value["params"],
  };
}
