/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CheckoutProblemSource } from "./CheckoutProblemSource";
import {
  CheckoutProblemSourceFromJSON,
  CheckoutProblemSourceFromJSONTyped,
  CheckoutProblemSourceToJSON,
  CheckoutProblemSourceToJSONTyped,
} from "./CheckoutProblemSource";
import type { CheckoutProblemCode } from "./CheckoutProblemCode";
import {
  CheckoutProblemCodeFromJSON,
  CheckoutProblemCodeFromJSONTyped,
  CheckoutProblemCodeToJSON,
  CheckoutProblemCodeToJSONTyped,
} from "./CheckoutProblemCode";

/**
 *
 * @export
 * @interface Problem
 */
export interface Problem {
  /**
   *
   * @type {boolean}
   * @memberof Problem
   */
  blocking: boolean;
  /**
   *
   * @type {string}
   * @memberof Problem
   */
  bundleId?: string | null;
  /**
   *
   * @type {CheckoutProblemCode}
   * @memberof Problem
   */
  code: CheckoutProblemCode;
  /**
   *
   * @type {string}
   * @memberof Problem
   */
  currency?: string;
  /**
   *
   * @type {string}
   * @memberof Problem
   */
  detail?: string;
  /**
   *
   * @type {string}
   * @memberof Problem
   */
  featureId?: string | null;
  /**
   *
   * @type {string}
   * @memberof Problem
   */
  fieldId?: string | null;
  /**
   *
   * @type {string}
   * @memberof Problem
   */
  message: string;
  /**
   *
   * @type {string}
   * @memberof Problem
   */
  paymentMethodId?: string | null;
  /**
   *
   * @type {string}
   * @memberof Problem
   */
  planId?: string | null;
  /**
   *
   * @type {string}
   * @memberof Problem
   */
  priceId?: string | null;
  /**
   *
   * @type {CheckoutProblemSource}
   * @memberof Problem
   */
  source: CheckoutProblemSource;
}

/**
 * Check if a given object implements the Problem interface.
 */
export function instanceOfProblem(value: object): value is Problem {
  if (!("blocking" in value) || value["blocking"] === undefined) return false;
  if (!("code" in value) || value["code"] === undefined) return false;
  if (!("message" in value) || value["message"] === undefined) return false;
  if (!("source" in value) || value["source"] === undefined) return false;
  return true;
}

export function ProblemFromJSON(json: any): Problem {
  return ProblemFromJSONTyped(json, false);
}

export function ProblemFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Problem {
  if (json == null) {
    return json;
  }
  return {
    blocking: json["blocking"],
    bundleId: json["bundle_id"] == null ? undefined : json["bundle_id"],
    code: CheckoutProblemCodeFromJSON(json["code"]),
    currency: json["currency"] == null ? undefined : json["currency"],
    detail: json["detail"] == null ? undefined : json["detail"],
    featureId: json["feature_id"] == null ? undefined : json["feature_id"],
    fieldId: json["field_id"] == null ? undefined : json["field_id"],
    message: json["message"],
    paymentMethodId:
      json["payment_method_id"] == null ? undefined : json["payment_method_id"],
    planId: json["plan_id"] == null ? undefined : json["plan_id"],
    priceId: json["price_id"] == null ? undefined : json["price_id"],
    source: CheckoutProblemSourceFromJSON(json["source"]),
  };
}

export function ProblemToJSON(json: any): Problem {
  return ProblemToJSONTyped(json, false);
}

export function ProblemToJSONTyped(
  value?: Problem | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    blocking: value["blocking"],
    bundle_id: value["bundleId"],
    code: CheckoutProblemCodeToJSON(value["code"]),
    currency: value["currency"],
    detail: value["detail"],
    feature_id: value["featureId"],
    field_id: value["fieldId"],
    message: value["message"],
    payment_method_id: value["paymentMethodId"],
    plan_id: value["planId"],
    price_id: value["priceId"],
    source: CheckoutProblemSourceToJSON(value["source"]),
  };
}
