/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateAddOnRequestBody
 */
export interface UpdateAddOnRequestBody {
  /**
   *
   * @type {string}
   * @memberof UpdateAddOnRequestBody
   */
  addOnId: string;
  /**
   *
   * @type {string}
   * @memberof UpdateAddOnRequestBody
   */
  priceId: string;
}

/**
 * Check if a given object implements the UpdateAddOnRequestBody interface.
 */
export function instanceOfUpdateAddOnRequestBody(
  value: object,
): value is UpdateAddOnRequestBody {
  if (!("addOnId" in value) || value["addOnId"] === undefined) return false;
  if (!("priceId" in value) || value["priceId"] === undefined) return false;
  return true;
}

export function UpdateAddOnRequestBodyFromJSON(
  json: any,
): UpdateAddOnRequestBody {
  return UpdateAddOnRequestBodyFromJSONTyped(json, false);
}

export function UpdateAddOnRequestBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateAddOnRequestBody {
  if (json == null) {
    return json;
  }
  return {
    addOnId: json["add_on_id"],
    priceId: json["price_id"],
  };
}

export function UpdateAddOnRequestBodyToJSON(
  value?: UpdateAddOnRequestBody | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    add_on_id: value["addOnId"],
    price_id: value["priceId"],
  };
}
