/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { TaxIDInput } from "./TaxIDInput";
import {
  TaxIDInputFromJSON,
  TaxIDInputFromJSONTyped,
  TaxIDInputToJSON,
  TaxIDInputToJSONTyped,
} from "./TaxIDInput";

/**
 *
 * @export
 * @interface UpdateCheckoutTaxIDRequestBody
 */
export interface UpdateCheckoutTaxIDRequestBody {
  /**
   *
   * @type {TaxIDInput}
   * @memberof UpdateCheckoutTaxIDRequestBody
   */
  taxId: TaxIDInput;
}

/**
 * Check if a given object implements the UpdateCheckoutTaxIDRequestBody interface.
 */
export function instanceOfUpdateCheckoutTaxIDRequestBody(
  value: object,
): value is UpdateCheckoutTaxIDRequestBody {
  if (!("taxId" in value) || value["taxId"] === undefined) return false;
  return true;
}

export function UpdateCheckoutTaxIDRequestBodyFromJSON(
  json: any,
): UpdateCheckoutTaxIDRequestBody {
  return UpdateCheckoutTaxIDRequestBodyFromJSONTyped(json, false);
}

export function UpdateCheckoutTaxIDRequestBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateCheckoutTaxIDRequestBody {
  if (json == null) {
    return json;
  }
  return {
    taxId: TaxIDInputFromJSON(json["tax_id"]),
  };
}

export function UpdateCheckoutTaxIDRequestBodyToJSON(
  json: any,
): UpdateCheckoutTaxIDRequestBody {
  return UpdateCheckoutTaxIDRequestBodyToJSONTyped(json, false);
}

export function UpdateCheckoutTaxIDRequestBodyToJSONTyped(
  value?: UpdateCheckoutTaxIDRequestBody | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    tax_id: TaxIDInputToJSON(value["taxId"]),
  };
}
