/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { UpdateCheckoutFieldValuesResponseData } from "./UpdateCheckoutFieldValuesResponseData";
import {
  UpdateCheckoutFieldValuesResponseDataFromJSON,
  UpdateCheckoutFieldValuesResponseDataFromJSONTyped,
  UpdateCheckoutFieldValuesResponseDataToJSON,
  UpdateCheckoutFieldValuesResponseDataToJSONTyped,
} from "./UpdateCheckoutFieldValuesResponseData";

/**
 *
 * @export
 * @interface UpdateCheckoutFieldValuesResponse
 */
export interface UpdateCheckoutFieldValuesResponse {
  /**
   *
   * @type {UpdateCheckoutFieldValuesResponseData}
   * @memberof UpdateCheckoutFieldValuesResponse
   */
  data: UpdateCheckoutFieldValuesResponseData;
  /**
   * Input parameters
   * @type {object}
   * @memberof UpdateCheckoutFieldValuesResponse
   */
  params: object;
}

/**
 * Check if a given object implements the UpdateCheckoutFieldValuesResponse interface.
 */
export function instanceOfUpdateCheckoutFieldValuesResponse(
  value: object,
): value is UpdateCheckoutFieldValuesResponse {
  if (!("data" in value) || value["data"] === undefined) return false;
  if (!("params" in value) || value["params"] === undefined) return false;
  return true;
}

export function UpdateCheckoutFieldValuesResponseFromJSON(
  json: any,
): UpdateCheckoutFieldValuesResponse {
  return UpdateCheckoutFieldValuesResponseFromJSONTyped(json, false);
}

export function UpdateCheckoutFieldValuesResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateCheckoutFieldValuesResponse {
  if (json == null) {
    return json;
  }
  return {
    data: UpdateCheckoutFieldValuesResponseDataFromJSON(json["data"]),
    params: json["params"],
  };
}

export function UpdateCheckoutFieldValuesResponseToJSON(
  json: any,
): UpdateCheckoutFieldValuesResponse {
  return UpdateCheckoutFieldValuesResponseToJSONTyped(json, false);
}

export function UpdateCheckoutFieldValuesResponseToJSONTyped(
  value?: UpdateCheckoutFieldValuesResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data: UpdateCheckoutFieldValuesResponseDataToJSON(value["data"]),
    params: value["params"],
  };
}
