import {
  useSchematic,
  SchematicProvider,
  type SchematicProviderProps,
} from "./context";
import * as helpers from "./helpers";

export { helpers };
import {
  useCatalog,
  useInvoices,
  useResource,
  useSchematicContext,
  useSchematicCreditBalance,
  useSchematicCustomerClient,
  useSchematicEntitlement,
  useSchematicEvents,
  useSchematicFlag,
  useSchematicIsPending,
  useSchematicPlan,
  useSubscription,
  type SchematicCreditBalance,
  type SchematicCustomerHookOpts,
  type SchematicHookOpts,
  type SchematicHookResult,
  type UseCatalogOptions,
  type UseInvoicesOptions,
  type UseSchematicFlagOpts,
  type UseSchematicPlanOpts,
  type UseSubscriptionOpts,
} from "./hooks";

export {
  useCatalog,
  useInvoices,
  useResource,
  useSchematic,
  useSchematicContext,
  useSchematicCreditBalance,
  useSchematicCustomerClient,
  useSchematicEntitlement,
  useSchematicEvents,
  useSchematicFlag,
  useSchematicIsPending,
  useSchematicPlan,
  useSubscription,
  SchematicProvider,
};

export type {
  SchematicCreditBalance,
  SchematicCustomerHookOpts,
  SchematicHookOpts,
  SchematicHookResult,
  SchematicProviderProps,
  UseCatalogOptions,
  UseInvoicesOptions,
  UseSchematicFlagOpts,
  UseSchematicPlanOpts,
  UseSubscriptionOpts,
};

export {
  checkoutexternal,
  componentspublic,
  toCatalogFromHydrate,
  toCatalogFromPublic,
  toSubscription,
  BillingCreditGrantReason,
  EntitlementPriceBehavior,
  FeatureType,
  InvoiceStatus,
  Resource,
  RuleType,
  Schematic,
  SchematicCustomerClient,
  TokenManager,
  TrialStatus,
  UsagePeriod,
} from "@schematichq/schematic-js";

export type {
  AccessTokenInput,
  AccessTokenProvider,
  AccessTokenResult,
  BillingPriceResponseData,
  Catalog,
  CatalogMode,
  CatalogPlan,
  CheckFlagReturn,
  CheckPlanReturn,
  CompanyCreditBalance,
  CompanyDetailResponseData,
  CompanyPlanDetailResponseData,
  CompanySubscriptionResponseData,
  ComponentDisplaySettings,
  ComponentHydrateResponseData,
  CreditBalance,
  CreditBalances,
  CreditCompanyGrantView,
  CustomerSubscription,
  Event,
  EventBody,
  EventBodyIdentify,
  EventBodyTrack,
  EventType,
  FeatureResponseData,
  FeatureUsageResponseData,
  InvoiceResponseData,
  Keys,
  PlanDetailResponseData,
  PlanEntitlementResponseData,
  PublicPlansResponseData,
  ResourceOptions,
  ResourceState,
  ScheduledDowngradeResponseData,
  SchematicContext,
  SchematicCustomerApi,
  SchematicCustomerClientOptions,
  SchematicOptions,
  StoragePersister,
  Traits,
} from "@schematichq/schematic-js";
