import {
  useSchematic,
  SchematicProvider,
  type SchematicProviderProps,
} from "./context";
import {
  useSchematicContext,
  useSchematicCreditBalance,
  useSchematicEntitlement,
  useSchematicEvents,
  useSchematicFlag,
  useSchematicIsPending,
  useSchematicPlan,
  type SchematicCreditBalance,
  type SchematicHookOpts,
  type UseSchematicPlanOpts,
  type UseSchematicFlagOpts,
} from "./hooks";

export {
  useSchematic,
  useSchematicContext,
  useSchematicCreditBalance,
  useSchematicEntitlement,
  useSchematicEvents,
  useSchematicFlag,
  useSchematicIsPending,
  useSchematicPlan,
  SchematicProvider,
};

export type {
  SchematicCreditBalance,
  SchematicHookOpts,
  SchematicProviderProps,
  UseSchematicFlagOpts,
  UseSchematicPlanOpts,
};

export {
  RuleType,
  Schematic,
  TrialStatus,
  UsagePeriod,
} from "@schematichq/schematic-js";

export type {
  CheckFlagReturn,
  CheckPlanReturn,
  CompanyCreditBalance,
  CreditBalance,
  CreditBalances,
  Event,
  EventBody,
  EventBodyIdentify,
  EventBodyTrack,
  EventType,
  Keys,
  SchematicContext,
  SchematicOptions,
  StoragePersister,
  Traits,
} from "@schematichq/schematic-js";

// Customer data hooks for catalog-API consumer surfaces (pricing tables,
// plan managers, usage meters). See hooks/customer.ts.
export {
  useCatalog,
  useCompany,
  useCreditBalances,
  useFeatureUsage,
  useInvoices,
  useSchematicCustomerClient,
  useSchematicLocale,
  type UseInvoicesResult,
  useUpcomingInvoice,
  type UseCustomerResourceOpts,
  type UseCustomerResourceResult,
} from "./hooks";

export {
  deriveCreditBalances,
  derivePeriod,
  PricePeriod,
  deriveEntitlement,
  deriveInvoiceList,
  derivePlanSummary,
  derivePriceDisplay,
  derivePlanOfferings,
  fetchCatalog,
  fetchCompany,
  fetchCreditBalances,
  fetchFeatureUsage,
  fetchInvoices,
  fetchUpcomingInvoice,
  type CatalogMode,
  type CatalogParams,
  type CustomerInitialData,
  type DisplayToggles,
  type InvoicePage,
  type PlanSummaryInput,
  deriveUpcomingInvoice,
  deriveUsage,
  formatCurrency,
  formatCurrencyMajorUnits,
  formatDate,
  formatNumber,
  amountFromMinorUnits,
  featureNameForCount,
  formatConsumptionRate,
  MONTHS_PER_PERIOD,
  offeredPeriods,
  PERIOD_ORDER,
  periodFromCadence,
  pricePeriod,
  priceValue,
  resolvePrice,
  Resource,
  SchematicApiError,
  SchematicCustomerClient,
  customerApi,
  publicApi,
} from "@schematichq/schematic-js";

export type {
  AccessTokenInput,
  AccessTokenProvider,
  AccessTokenResult,
  CreditBalanceSummary,
  CreditBundleOffering,
  CreditGrantEntry,
  CreditGrantSource,
  CustomerCatalog,
  CustomerFetchOptions,
  CustomPlanCta,
  EntitlementCredit,
  EntitlementDisplayOptions,
  EntitlementFeature,
  EntitlementKind,
  EntitlementOptions,
  EntitlementSummary,
  FormatOptions,
  InvoiceRow,
  ListInvoicesParams,
  PlanOffering,
  PlanOfferingPrice,
  PlanOfferingsInput,
  PlanOfferingsSelection,
  PlanSummaryNotice,
  PlanSummary,
  PlanSummaryPlan,
  PlanOfferings,
  PriceDisplay,
  PriceTier,
  SchematicCustomerClientOptions,
  ResourceState,
  UpcomingInvoiceDiscount,
  UpcomingInvoiceSummary,
  UsageOptions,
  UsageState,
  UsageSummary,
} from "@schematichq/schematic-js";
