/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const BillingStrategy = {
  SchematicManaged: "schematic_managed",
  ProviderManaged: "provider_managed",
  NoBilling: "no_billing",
} as const;
export type BillingStrategy =
  (typeof BillingStrategy)[keyof typeof BillingStrategy];

export function instanceOfBillingStrategy(value: any): boolean {
  for (const key in BillingStrategy) {
    if (Object.prototype.hasOwnProperty.call(BillingStrategy, key)) {
      if (BillingStrategy[key as keyof typeof BillingStrategy] === value) {
        return true;
      }
    }
  }
  return false;
}

export function BillingStrategyFromJSON(json: any): BillingStrategy {
  return BillingStrategyFromJSONTyped(json, false);
}

export function BillingStrategyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BillingStrategy {
  return json as BillingStrategy;
}

export function BillingStrategyToJSON(value?: BillingStrategy | null): any {
  return value as any;
}

export function BillingStrategyToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean,
): BillingStrategy {
  return value as BillingStrategy;
}
