export const TEXT_BASE_SIZE = 16;

export const VISIBLE_ENTITLEMENT_COUNT = 4;

export const MAX_VISIBLE_INVOICE_COUNT = 12;

export const EVENT_DEBOUNCE_TIMEOUT = 250;

export const DEFAULT_CURRENCY = "USD";

export const MAXIMUM_SIGNIFICANT_DIGITS = 6;

export const FETCH_DEBOUNCE_TIMEOUT = 500;
