/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { InvoiceStatus } from "./InvoiceStatus";
import {
  InvoiceStatusFromJSON,
  InvoiceStatusFromJSONTyped,
  InvoiceStatusToJSON,
  InvoiceStatusToJSONTyped,
} from "./InvoiceStatus";

/**
 *
 * @export
 * @interface CompanyInvoiceResponseData
 */
export interface CompanyInvoiceResponseData {
  /**
   *
   * @type {number}
   * @memberof CompanyInvoiceResponseData
   */
  amountDue: number;
  /**
   *
   * @type {Date}
   * @memberof CompanyInvoiceResponseData
   */
  createdAt: Date;
  /**
   *
   * @type {string}
   * @memberof CompanyInvoiceResponseData
   */
  currency: string;
  /**
   *
   * @type {Date}
   * @memberof CompanyInvoiceResponseData
   */
  dueDate?: Date | null;
  /**
   *
   * @type {string}
   * @memberof CompanyInvoiceResponseData
   */
  id: string;
  /**
   *
   * @type {InvoiceStatus}
   * @memberof CompanyInvoiceResponseData
   */
  status?: InvoiceStatus | null;
  /**
   *
   * @type {string}
   * @memberof CompanyInvoiceResponseData
   */
  url?: string | null;
}

/**
 * Check if a given object implements the CompanyInvoiceResponseData interface.
 */
export function instanceOfCompanyInvoiceResponseData(
  value: object,
): value is CompanyInvoiceResponseData {
  if (!("amountDue" in value) || value["amountDue"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("currency" in value) || value["currency"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  return true;
}

export function CompanyInvoiceResponseDataFromJSON(
  json: any,
): CompanyInvoiceResponseData {
  return CompanyInvoiceResponseDataFromJSONTyped(json, false);
}

export function CompanyInvoiceResponseDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CompanyInvoiceResponseData {
  if (json == null) {
    return json;
  }
  return {
    amountDue: json["amount_due"],
    createdAt: new Date(json["created_at"]),
    currency: json["currency"],
    dueDate: json["due_date"] == null ? undefined : new Date(json["due_date"]),
    id: json["id"],
    status:
      json["status"] == null
        ? undefined
        : InvoiceStatusFromJSON(json["status"]),
    url: json["url"] == null ? undefined : json["url"],
  };
}

export function CompanyInvoiceResponseDataToJSON(
  json: any,
): CompanyInvoiceResponseData {
  return CompanyInvoiceResponseDataToJSONTyped(json, false);
}

export function CompanyInvoiceResponseDataToJSONTyped(
  value?: CompanyInvoiceResponseData | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    amount_due: value["amountDue"],
    created_at: value["createdAt"].toISOString(),
    currency: value["currency"],
    due_date:
      value["dueDate"] == null
        ? undefined
        : (value["dueDate"] as any).toISOString(),
    id: value["id"],
    status: InvoiceStatusToJSON(value["status"]),
    url: value["url"],
  };
}
