/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CompanyDiscountResponseData } from "./CompanyDiscountResponseData";
import {
  CompanyDiscountResponseDataFromJSON,
  CompanyDiscountResponseDataFromJSONTyped,
  CompanyDiscountResponseDataToJSON,
  CompanyDiscountResponseDataToJSONTyped,
} from "./CompanyDiscountResponseData";

/**
 *
 * @export
 * @interface CompanyUpcomingInvoiceResponseData
 */
export interface CompanyUpcomingInvoiceResponseData {
  /**
   *
   * @type {number}
   * @memberof CompanyUpcomingInvoiceResponseData
   */
  amountDue: number;
  /**
   *
   * @type {string}
   * @memberof CompanyUpcomingInvoiceResponseData
   */
  currency: string;
  /**
   * How much of the company's existing balance this invoice consumes.
   * @type {number}
   * @memberof CompanyUpcomingInvoiceResponseData
   */
  customerBalanceApplied: number;
  /**
   * Balance left over after this invoice.
   * @type {number}
   * @memberof CompanyUpcomingInvoiceResponseData
   */
  customerBalanceRemaining: number;
  /**
   *
   * @type {Array<CompanyDiscountResponseData>}
   * @memberof CompanyUpcomingInvoiceResponseData
   */
  discounts: Array<CompanyDiscountResponseData>;
  /**
   *
   * @type {Date}
   * @memberof CompanyUpcomingInvoiceResponseData
   */
  dueDate?: Date | null;
  /**
   * Amount before discounts and tax.
   * @type {number}
   * @memberof CompanyUpcomingInvoiceResponseData
   */
  subtotal: number;
}

/**
 * Check if a given object implements the CompanyUpcomingInvoiceResponseData interface.
 */
export function instanceOfCompanyUpcomingInvoiceResponseData(
  value: object,
): value is CompanyUpcomingInvoiceResponseData {
  if (!("amountDue" in value) || value["amountDue"] === undefined) return false;
  if (!("currency" in value) || value["currency"] === undefined) return false;
  if (
    !("customerBalanceApplied" in value) ||
    value["customerBalanceApplied"] === undefined
  )
    return false;
  if (
    !("customerBalanceRemaining" in value) ||
    value["customerBalanceRemaining"] === undefined
  )
    return false;
  if (!("discounts" in value) || value["discounts"] === undefined) return false;
  if (!("subtotal" in value) || value["subtotal"] === undefined) return false;
  return true;
}

export function CompanyUpcomingInvoiceResponseDataFromJSON(
  json: any,
): CompanyUpcomingInvoiceResponseData {
  return CompanyUpcomingInvoiceResponseDataFromJSONTyped(json, false);
}

export function CompanyUpcomingInvoiceResponseDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CompanyUpcomingInvoiceResponseData {
  if (json == null) {
    return json;
  }
  return {
    amountDue: json["amount_due"],
    currency: json["currency"],
    customerBalanceApplied: json["customer_balance_applied"],
    customerBalanceRemaining: json["customer_balance_remaining"],
    discounts: (json["discounts"] as Array<any>).map(
      CompanyDiscountResponseDataFromJSON,
    ),
    dueDate: json["due_date"] == null ? undefined : new Date(json["due_date"]),
    subtotal: json["subtotal"],
  };
}

export function CompanyUpcomingInvoiceResponseDataToJSON(
  json: any,
): CompanyUpcomingInvoiceResponseData {
  return CompanyUpcomingInvoiceResponseDataToJSONTyped(json, false);
}

export function CompanyUpcomingInvoiceResponseDataToJSONTyped(
  value?: CompanyUpcomingInvoiceResponseData | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    amount_due: value["amountDue"],
    currency: value["currency"],
    customer_balance_applied: value["customerBalanceApplied"],
    customer_balance_remaining: value["customerBalanceRemaining"],
    discounts: (value["discounts"] as Array<any>).map(
      CompanyDiscountResponseDataToJSON,
    ),
    due_date:
      value["dueDate"] == null
        ? undefined
        : (value["dueDate"] as any).toISOString(),
    subtotal: value["subtotal"],
  };
}
