/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Input parameters
 * @export
 * @interface GetCompanyInvoicesParams
 */
export interface GetCompanyInvoicesParams {
  /**
   *
   * @type {boolean}
   * @memberof GetCompanyInvoicesParams
   */
  includePending?: boolean;
  /**
   * Page limit (default 100)
   * @type {number}
   * @memberof GetCompanyInvoicesParams
   */
  limit?: number;
  /**
   * Page offset (default 0)
   * @type {number}
   * @memberof GetCompanyInvoicesParams
   */
  offset?: number;
}

/**
 * Check if a given object implements the GetCompanyInvoicesParams interface.
 */
export function instanceOfGetCompanyInvoicesParams(
  value: object,
): value is GetCompanyInvoicesParams {
  return true;
}

export function GetCompanyInvoicesParamsFromJSON(
  json: any,
): GetCompanyInvoicesParams {
  return GetCompanyInvoicesParamsFromJSONTyped(json, false);
}

export function GetCompanyInvoicesParamsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetCompanyInvoicesParams {
  if (json == null) {
    return json;
  }
  return {
    includePending:
      json["include_pending"] == null ? undefined : json["include_pending"],
    limit: json["limit"] == null ? undefined : json["limit"],
    offset: json["offset"] == null ? undefined : json["offset"],
  };
}

export function GetCompanyInvoicesParamsToJSON(
  json: any,
): GetCompanyInvoicesParams {
  return GetCompanyInvoicesParamsToJSONTyped(json, false);
}

export function GetCompanyInvoicesParamsToJSONTyped(
  value?: GetCompanyInvoicesParams | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    include_pending: value["includePending"],
    limit: value["limit"],
    offset: value["offset"],
  };
}
