/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { PreflightRequestBody } from "./PreflightRequestBody";
import {
  PreflightRequestBodyFromJSON,
  PreflightRequestBodyFromJSONTyped,
  PreflightRequestBodyToJSON,
  PreflightRequestBodyToJSONTyped,
} from "./PreflightRequestBody";

/**
 *
 * @export
 * @interface CheckFlagRequestBody
 */
export interface CheckFlagRequestBody {
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof CheckFlagRequestBody
   */
  company?: { [key: string]: string } | null;
  /**
   * Hypothetical usage to evaluate the flag against, for answering "would this action be allowed?" before performing it. Only supported when checking a single flag. Values are caller-asserted and can widen a verdict as well as narrow it, so do not forward untrusted input here when the result gates access. Only the flag value reflects the preflight; the entitlement and usage figures in the response are the company's current, unsimulated ones
   * @type {PreflightRequestBody}
   * @memberof CheckFlagRequestBody
   */
  preflight?: PreflightRequestBody;
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof CheckFlagRequestBody
   */
  user?: { [key: string]: string } | null;
}

/**
 * Check if a given object implements the CheckFlagRequestBody interface.
 */
export function instanceOfCheckFlagRequestBody(
  value: object,
): value is CheckFlagRequestBody {
  return true;
}

export function CheckFlagRequestBodyFromJSON(json: any): CheckFlagRequestBody {
  return CheckFlagRequestBodyFromJSONTyped(json, false);
}

export function CheckFlagRequestBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CheckFlagRequestBody {
  if (json == null) {
    return json;
  }
  return {
    company: json["company"] == null ? undefined : json["company"],
    preflight:
      json["preflight"] == null
        ? undefined
        : PreflightRequestBodyFromJSON(json["preflight"]),
    user: json["user"] == null ? undefined : json["user"],
  };
}

export function CheckFlagRequestBodyToJSON(json: any): CheckFlagRequestBody {
  return CheckFlagRequestBodyToJSONTyped(json, false);
}

export function CheckFlagRequestBodyToJSONTyped(
  value?: CheckFlagRequestBody | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    company: value["company"],
    preflight: PreflightRequestBodyToJSON(value["preflight"]),
    user: value["user"],
  };
}
