/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const Currency = {
  Aed: "aed",
  Afn: "afn",
  All: "all",
  Amd: "amd",
  Ang: "ang",
  Aoa: "aoa",
  Ars: "ars",
  Aud: "aud",
  Awg: "awg",
  Azn: "azn",
  Bam: "bam",
  Bbd: "bbd",
  Bdt: "bdt",
  Bif: "bif",
  Bmd: "bmd",
  Bnd: "bnd",
  Bob: "bob",
  Brl: "brl",
  Bsd: "bsd",
  Bwp: "bwp",
  Byn: "byn",
  Bzd: "bzd",
  Cad: "cad",
  Cdf: "cdf",
  Chf: "chf",
  Clp: "clp",
  Cny: "cny",
  Cop: "cop",
  Crc: "crc",
  Cve: "cve",
  Czk: "czk",
  Djf: "djf",
  Dkk: "dkk",
  Dop: "dop",
  Dzd: "dzd",
  Egp: "egp",
  Etb: "etb",
  Eur: "eur",
  Fjd: "fjd",
  Fkp: "fkp",
  Gbp: "gbp",
  Gel: "gel",
  Gip: "gip",
  Gmd: "gmd",
  Gnf: "gnf",
  Gtq: "gtq",
  Gyd: "gyd",
  Hkd: "hkd",
  Hnl: "hnl",
  Htg: "htg",
  Huf: "huf",
  Idr: "idr",
  Ils: "ils",
  Inr: "inr",
  Isk: "isk",
  Jmd: "jmd",
  Jpy: "jpy",
  Kes: "kes",
  Kgs: "kgs",
  Khr: "khr",
  Kmf: "kmf",
  Krw: "krw",
  Kyd: "kyd",
  Kzt: "kzt",
  Lak: "lak",
  Lbp: "lbp",
  Lkr: "lkr",
  Lrd: "lrd",
  Lsl: "lsl",
  Mad: "mad",
  Mdl: "mdl",
  Mga: "mga",
  Mkd: "mkd",
  Mmk: "mmk",
  Mnt: "mnt",
  Mop: "mop",
  Mur: "mur",
  Mvr: "mvr",
  Mwk: "mwk",
  Mxn: "mxn",
  Myr: "myr",
  Mzn: "mzn",
  Nad: "nad",
  Ngn: "ngn",
  Nio: "nio",
  Nok: "nok",
  Npr: "npr",
  Nzd: "nzd",
  Pab: "pab",
  Pen: "pen",
  Pgk: "pgk",
  Php: "php",
  Pkr: "pkr",
  Pln: "pln",
  Pyg: "pyg",
  Qar: "qar",
  Ron: "ron",
  Rsd: "rsd",
  Rub: "rub",
  Rwf: "rwf",
  Sar: "sar",
  Sbd: "sbd",
  Scr: "scr",
  Sek: "sek",
  Sgd: "sgd",
  Shp: "shp",
  Sle: "sle",
  Sos: "sos",
  Srd: "srd",
  Std: "std",
  Szl: "szl",
  Thb: "thb",
  Tjs: "tjs",
  Top: "top",
  Try: "try",
  Ttd: "ttd",
  Twd: "twd",
  Tzs: "tzs",
  Uah: "uah",
  Ugx: "ugx",
  Usd: "usd",
  Uyu: "uyu",
  Uzs: "uzs",
  Vnd: "vnd",
  Vuv: "vuv",
  Wst: "wst",
  Xaf: "xaf",
  Xcd: "xcd",
  Xcg: "xcg",
  Xof: "xof",
  Xpf: "xpf",
  Yer: "yer",
  Zar: "zar",
  Zmw: "zmw",
} as const;
export type Currency = (typeof Currency)[keyof typeof Currency];

export function instanceOfCurrency(value: any): boolean {
  for (const key in Currency) {
    if (Object.prototype.hasOwnProperty.call(Currency, key)) {
      if (Currency[key as keyof typeof Currency] === value) {
        return true;
      }
    }
  }
  return false;
}

export function CurrencyFromJSON(json: any): Currency {
  return CurrencyFromJSONTyped(json, false);
}

export function CurrencyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Currency {
  return json as Currency;
}

export function CurrencyToJSON(value?: Currency | null): any {
  return value as any;
}

export function CurrencyToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean,
): Currency {
  return value as Currency;
}
