/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CompanyPlanInvalidReason } from "./CompanyPlanInvalidReason";
import {
  CompanyPlanInvalidReasonFromJSON,
  CompanyPlanInvalidReasonFromJSONTyped,
  CompanyPlanInvalidReasonToJSON,
  CompanyPlanInvalidReasonToJSONTyped,
} from "./CompanyPlanInvalidReason";
import type { CatalogUsageViolationResponseData } from "./CatalogUsageViolationResponseData";
import {
  CatalogUsageViolationResponseDataFromJSON,
  CatalogUsageViolationResponseDataFromJSONTyped,
  CatalogUsageViolationResponseDataToJSON,
  CatalogUsageViolationResponseDataToJSONTyped,
} from "./CatalogUsageViolationResponseData";
import type { CatalogPlanEntitlementResponseData } from "./CatalogPlanEntitlementResponseData";
import {
  CatalogPlanEntitlementResponseDataFromJSON,
  CatalogPlanEntitlementResponseDataFromJSONTyped,
  CatalogPlanEntitlementResponseDataToJSON,
  CatalogPlanEntitlementResponseDataToJSONTyped,
} from "./CatalogPlanEntitlementResponseData";
import type { ChargeType } from "./ChargeType";
import {
  ChargeTypeFromJSON,
  ChargeTypeFromJSONTyped,
  ChargeTypeToJSON,
  ChargeTypeToJSONTyped,
} from "./ChargeType";
import type { CatalogCurrencyPricesResponseData } from "./CatalogCurrencyPricesResponseData";
import {
  CatalogCurrencyPricesResponseDataFromJSON,
  CatalogCurrencyPricesResponseDataFromJSONTyped,
  CatalogCurrencyPricesResponseDataToJSON,
  CatalogCurrencyPricesResponseDataToJSONTyped,
} from "./CatalogCurrencyPricesResponseData";
import type { CatalogCreditGrantResponseData } from "./CatalogCreditGrantResponseData";
import {
  CatalogCreditGrantResponseDataFromJSON,
  CatalogCreditGrantResponseDataFromJSONTyped,
  CatalogCreditGrantResponseDataToJSON,
  CatalogCreditGrantResponseDataToJSONTyped,
} from "./CatalogCreditGrantResponseData";
import type { PlanPriceCadence } from "./PlanPriceCadence";
import {
  PlanPriceCadenceFromJSON,
  PlanPriceCadenceFromJSONTyped,
  PlanPriceCadenceToJSON,
  PlanPriceCadenceToJSONTyped,
} from "./PlanPriceCadence";
import type { BillingStrategy } from "./BillingStrategy";
import {
  BillingStrategyFromJSON,
  BillingStrategyFromJSONTyped,
  BillingStrategyToJSON,
  BillingStrategyToJSONTyped,
} from "./BillingStrategy";
import type { CatalogPriceResponseData } from "./CatalogPriceResponseData";
import {
  CatalogPriceResponseDataFromJSON,
  CatalogPriceResponseDataFromJSONTyped,
  CatalogPriceResponseDataToJSON,
  CatalogPriceResponseDataToJSONTyped,
} from "./CatalogPriceResponseData";

/**
 *
 * @export
 * @interface CatalogCompanyPlanResponseData
 */
export interface CatalogCompanyPlanResponseData {
  /**
   *
   * @type {Array<PlanPriceCadence>}
   * @memberof CatalogCompanyPlanResponseData
   */
  availablePeriods: Array<PlanPriceCadence>;
  /**
   *
   * @type {BillingStrategy}
   * @memberof CatalogCompanyPlanResponseData
   */
  billingStrategy: BillingStrategy;
  /**
   *
   * @type {ChargeType}
   * @memberof CatalogCompanyPlanResponseData
   */
  chargeType: ChargeType;
  /**
   *
   * @type {boolean}
   * @memberof CatalogCompanyPlanResponseData
   */
  companyCanTrial: boolean;
  /**
   * For add-ons, the plans this add-on may be purchased with. Null means compatible with every plan.
   * @type {Array<string>}
   * @memberof CatalogCompanyPlanResponseData
   */
  compatiblePlanIds?: Array<string> | null;
  /**
   *
   * @type {Array<CatalogCurrencyPricesResponseData>}
   * @memberof CatalogCompanyPlanResponseData
   */
  currencyPrices: Array<CatalogCurrencyPricesResponseData>;
  /**
   *
   * @type {boolean}
   * @memberof CatalogCompanyPlanResponseData
   */
  current: boolean;
  /**
   *
   * @type {string}
   * @memberof CatalogCompanyPlanResponseData
   */
  description: string;
  /**
   *
   * @type {Array<CatalogPlanEntitlementResponseData>}
   * @memberof CatalogCompanyPlanResponseData
   */
  entitlements: Array<CatalogPlanEntitlementResponseData>;
  /**
   *
   * @type {string}
   * @memberof CatalogCompanyPlanResponseData
   */
  icon: string;
  /**
   *
   * @type {string}
   * @memberof CatalogCompanyPlanResponseData
   */
  id: string;
  /**
   *
   * @type {Array<CatalogCreditGrantResponseData>}
   * @memberof CatalogCompanyPlanResponseData
   */
  includedCreditGrants: Array<CatalogCreditGrantResponseData>;
  /**
   *
   * @type {CompanyPlanInvalidReason}
   * @memberof CatalogCompanyPlanResponseData
   */
  invalidReason?: CompanyPlanInvalidReason | null;
  /**
   *
   * @type {boolean}
   * @memberof CatalogCompanyPlanResponseData
   */
  isTrialable: boolean;
  /**
   *
   * @type {CatalogPriceResponseData}
   * @memberof CatalogCompanyPlanResponseData
   */
  monthlyPrice?: CatalogPriceResponseData;
  /**
   *
   * @type {string}
   * @memberof CatalogCompanyPlanResponseData
   */
  name: string;
  /**
   *
   * @type {CatalogPriceResponseData}
   * @memberof CatalogCompanyPlanResponseData
   */
  oneTimePrice?: CatalogPriceResponseData;
  /**
   *
   * @type {CatalogPriceResponseData}
   * @memberof CatalogCompanyPlanResponseData
   */
  quarterlyPrice?: CatalogPriceResponseData;
  /**
   *
   * @type {number}
   * @memberof CatalogCompanyPlanResponseData
   */
  trialDays?: number | null;
  /**
   *
   * @type {Array<CatalogUsageViolationResponseData>}
   * @memberof CatalogCompanyPlanResponseData
   */
  usageViolations: Array<CatalogUsageViolationResponseData>;
  /**
   *
   * @type {boolean}
   * @memberof CatalogCompanyPlanResponseData
   */
  valid: boolean;
  /**
   *
   * @type {CatalogPriceResponseData}
   * @memberof CatalogCompanyPlanResponseData
   */
  yearlyPrice?: CatalogPriceResponseData;
}

/**
 * Check if a given object implements the CatalogCompanyPlanResponseData interface.
 */
export function instanceOfCatalogCompanyPlanResponseData(
  value: object,
): value is CatalogCompanyPlanResponseData {
  if (!("availablePeriods" in value) || value["availablePeriods"] === undefined)
    return false;
  if (!("billingStrategy" in value) || value["billingStrategy"] === undefined)
    return false;
  if (!("chargeType" in value) || value["chargeType"] === undefined)
    return false;
  if (!("companyCanTrial" in value) || value["companyCanTrial"] === undefined)
    return false;
  if (!("currencyPrices" in value) || value["currencyPrices"] === undefined)
    return false;
  if (!("current" in value) || value["current"] === undefined) return false;
  if (!("description" in value) || value["description"] === undefined)
    return false;
  if (!("entitlements" in value) || value["entitlements"] === undefined)
    return false;
  if (!("icon" in value) || value["icon"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (
    !("includedCreditGrants" in value) ||
    value["includedCreditGrants"] === undefined
  )
    return false;
  if (!("isTrialable" in value) || value["isTrialable"] === undefined)
    return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("usageViolations" in value) || value["usageViolations"] === undefined)
    return false;
  if (!("valid" in value) || value["valid"] === undefined) return false;
  return true;
}

export function CatalogCompanyPlanResponseDataFromJSON(
  json: any,
): CatalogCompanyPlanResponseData {
  return CatalogCompanyPlanResponseDataFromJSONTyped(json, false);
}

export function CatalogCompanyPlanResponseDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CatalogCompanyPlanResponseData {
  if (json == null) {
    return json;
  }
  return {
    availablePeriods: (json["available_periods"] as Array<any>).map(
      PlanPriceCadenceFromJSON,
    ),
    billingStrategy: BillingStrategyFromJSON(json["billing_strategy"]),
    chargeType: ChargeTypeFromJSON(json["charge_type"]),
    companyCanTrial: json["company_can_trial"],
    compatiblePlanIds:
      json["compatible_plan_ids"] == null
        ? undefined
        : json["compatible_plan_ids"],
    currencyPrices: (json["currency_prices"] as Array<any>).map(
      CatalogCurrencyPricesResponseDataFromJSON,
    ),
    current: json["current"],
    description: json["description"],
    entitlements: (json["entitlements"] as Array<any>).map(
      CatalogPlanEntitlementResponseDataFromJSON,
    ),
    icon: json["icon"],
    id: json["id"],
    includedCreditGrants: (json["included_credit_grants"] as Array<any>).map(
      CatalogCreditGrantResponseDataFromJSON,
    ),
    invalidReason:
      json["invalid_reason"] == null
        ? undefined
        : CompanyPlanInvalidReasonFromJSON(json["invalid_reason"]),
    isTrialable: json["is_trialable"],
    monthlyPrice:
      json["monthly_price"] == null
        ? undefined
        : CatalogPriceResponseDataFromJSON(json["monthly_price"]),
    name: json["name"],
    oneTimePrice:
      json["one_time_price"] == null
        ? undefined
        : CatalogPriceResponseDataFromJSON(json["one_time_price"]),
    quarterlyPrice:
      json["quarterly_price"] == null
        ? undefined
        : CatalogPriceResponseDataFromJSON(json["quarterly_price"]),
    trialDays: json["trial_days"] == null ? undefined : json["trial_days"],
    usageViolations: (json["usage_violations"] as Array<any>).map(
      CatalogUsageViolationResponseDataFromJSON,
    ),
    valid: json["valid"],
    yearlyPrice:
      json["yearly_price"] == null
        ? undefined
        : CatalogPriceResponseDataFromJSON(json["yearly_price"]),
  };
}

export function CatalogCompanyPlanResponseDataToJSON(
  json: any,
): CatalogCompanyPlanResponseData {
  return CatalogCompanyPlanResponseDataToJSONTyped(json, false);
}

export function CatalogCompanyPlanResponseDataToJSONTyped(
  value?: CatalogCompanyPlanResponseData | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    available_periods: (value["availablePeriods"] as Array<any>).map(
      PlanPriceCadenceToJSON,
    ),
    billing_strategy: BillingStrategyToJSON(value["billingStrategy"]),
    charge_type: ChargeTypeToJSON(value["chargeType"]),
    company_can_trial: value["companyCanTrial"],
    compatible_plan_ids: value["compatiblePlanIds"],
    currency_prices: (value["currencyPrices"] as Array<any>).map(
      CatalogCurrencyPricesResponseDataToJSON,
    ),
    current: value["current"],
    description: value["description"],
    entitlements: (value["entitlements"] as Array<any>).map(
      CatalogPlanEntitlementResponseDataToJSON,
    ),
    icon: value["icon"],
    id: value["id"],
    included_credit_grants: (value["includedCreditGrants"] as Array<any>).map(
      CatalogCreditGrantResponseDataToJSON,
    ),
    invalid_reason: CompanyPlanInvalidReasonToJSON(value["invalidReason"]),
    is_trialable: value["isTrialable"],
    monthly_price: CatalogPriceResponseDataToJSON(value["monthlyPrice"]),
    name: value["name"],
    one_time_price: CatalogPriceResponseDataToJSON(value["oneTimePrice"]),
    quarterly_price: CatalogPriceResponseDataToJSON(value["quarterlyPrice"]),
    trial_days: value["trialDays"],
    usage_violations: (value["usageViolations"] as Array<any>).map(
      CatalogUsageViolationResponseDataToJSON,
    ),
    valid: value["valid"],
    yearly_price: CatalogPriceResponseDataToJSON(value["yearlyPrice"]),
  };
}
