/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CatalogPriceTierResponseData
 */
export interface CatalogPriceTierResponseData {
  /**
   *
   * @type {number}
   * @memberof CatalogPriceTierResponseData
   */
  flatPrice?: number | null;
  /**
   * Lower bound of the tier (inclusive).
   * @type {number}
   * @memberof CatalogPriceTierResponseData
   */
  from: number;
  /**
   *
   * @type {number}
   * @memberof CatalogPriceTierResponseData
   */
  perUnitPrice?: number | null;
  /**
   *
   * @type {string}
   * @memberof CatalogPriceTierResponseData
   */
  perUnitPriceDecimal?: string | null;
  /**
   * Upper bound of the tier (inclusive); null means unbounded.
   * @type {number}
   * @memberof CatalogPriceTierResponseData
   */
  to?: number | null;
}

/**
 * Check if a given object implements the CatalogPriceTierResponseData interface.
 */
export function instanceOfCatalogPriceTierResponseData(
  value: object,
): value is CatalogPriceTierResponseData {
  if (!("from" in value) || value["from"] === undefined) return false;
  return true;
}

export function CatalogPriceTierResponseDataFromJSON(
  json: any,
): CatalogPriceTierResponseData {
  return CatalogPriceTierResponseDataFromJSONTyped(json, false);
}

export function CatalogPriceTierResponseDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CatalogPriceTierResponseData {
  if (json == null) {
    return json;
  }
  return {
    flatPrice: json["flat_price"] == null ? undefined : json["flat_price"],
    from: json["from"],
    perUnitPrice:
      json["per_unit_price"] == null ? undefined : json["per_unit_price"],
    perUnitPriceDecimal:
      json["per_unit_price_decimal"] == null
        ? undefined
        : json["per_unit_price_decimal"],
    to: json["to"] == null ? undefined : json["to"],
  };
}

export function CatalogPriceTierResponseDataToJSON(
  json: any,
): CatalogPriceTierResponseData {
  return CatalogPriceTierResponseDataToJSONTyped(json, false);
}

export function CatalogPriceTierResponseDataToJSONTyped(
  value?: CatalogPriceTierResponseData | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    flat_price: value["flatPrice"],
    from: value["from"],
    per_unit_price: value["perUnitPrice"],
    per_unit_price_decimal: value["perUnitPriceDecimal"],
    to: value["to"],
  };
}
