/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CatalogPriceResponseData } from "./CatalogPriceResponseData";
import {
  CatalogPriceResponseDataFromJSON,
  CatalogPriceResponseDataFromJSONTyped,
  CatalogPriceResponseDataToJSON,
  CatalogPriceResponseDataToJSONTyped,
} from "./CatalogPriceResponseData";

/**
 *
 * @export
 * @interface CompanyPlanResponseData
 */
export interface CompanyPlanResponseData {
  /**
   * The catalog this plan belongs to; null for add-ons held outside any catalog.
   * @type {string}
   * @memberof CompanyPlanResponseData
   */
  catalogId?: string | null;
  /**
   *
   * @type {string}
   * @memberof CompanyPlanResponseData
   */
  description: string;
  /**
   *
   * @type {string}
   * @memberof CompanyPlanResponseData
   */
  icon: string;
  /**
   *
   * @type {string}
   * @memberof CompanyPlanResponseData
   */
  id: string;
  /**
   *
   * @type {boolean}
   * @memberof CompanyPlanResponseData
   */
  isAddOn: boolean;
  /**
   * Billed through the custom-plan billing record in custom_billing rather than a catalog price.
   * @type {boolean}
   * @memberof CompanyPlanResponseData
   */
  isCustom: boolean;
  /**
   *
   * @type {string}
   * @memberof CompanyPlanResponseData
   */
  name: string;
  /**
   * The company's subscription price for this plan; null for free or custom-billed plans.
   * @type {CatalogPriceResponseData}
   * @memberof CompanyPlanResponseData
   */
  price?: CatalogPriceResponseData;
  /**
   * Seats for per-seat plans, when more than one.
   * @type {number}
   * @memberof CompanyPlanResponseData
   */
  quantity?: number | null;
}

/**
 * Check if a given object implements the CompanyPlanResponseData interface.
 */
export function instanceOfCompanyPlanResponseData(
  value: object,
): value is CompanyPlanResponseData {
  if (!("description" in value) || value["description"] === undefined)
    return false;
  if (!("icon" in value) || value["icon"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("isAddOn" in value) || value["isAddOn"] === undefined) return false;
  if (!("isCustom" in value) || value["isCustom"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  return true;
}

export function CompanyPlanResponseDataFromJSON(
  json: any,
): CompanyPlanResponseData {
  return CompanyPlanResponseDataFromJSONTyped(json, false);
}

export function CompanyPlanResponseDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CompanyPlanResponseData {
  if (json == null) {
    return json;
  }
  return {
    catalogId: json["catalog_id"] == null ? undefined : json["catalog_id"],
    description: json["description"],
    icon: json["icon"],
    id: json["id"],
    isAddOn: json["is_add_on"],
    isCustom: json["is_custom"],
    name: json["name"],
    price:
      json["price"] == null
        ? undefined
        : CatalogPriceResponseDataFromJSON(json["price"]),
    quantity: json["quantity"] == null ? undefined : json["quantity"],
  };
}

export function CompanyPlanResponseDataToJSON(
  json: any,
): CompanyPlanResponseData {
  return CompanyPlanResponseDataToJSONTyped(json, false);
}

export function CompanyPlanResponseDataToJSONTyped(
  value?: CompanyPlanResponseData | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    catalog_id: value["catalogId"],
    description: value["description"],
    icon: value["icon"],
    id: value["id"],
    is_add_on: value["isAddOn"],
    is_custom: value["isCustom"],
    name: value["name"],
    price: CatalogPriceResponseDataToJSON(value["price"]),
    quantity: value["quantity"],
  };
}
