/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CompanyCreditBalanceEntryResponseData } from "./CompanyCreditBalanceEntryResponseData";
import {
  CompanyCreditBalanceEntryResponseDataFromJSON,
  CompanyCreditBalanceEntryResponseDataFromJSONTyped,
  CompanyCreditBalanceEntryResponseDataToJSON,
  CompanyCreditBalanceEntryResponseDataToJSONTyped,
} from "./CompanyCreditBalanceEntryResponseData";

/**
 *
 * @export
 * @interface CompanyCreditBalancesResponseData
 */
export interface CompanyCreditBalancesResponseData {
  /**
   *
   * @type {Array<CompanyCreditBalanceEntryResponseData>}
   * @memberof CompanyCreditBalancesResponseData
   */
  balances: Array<CompanyCreditBalanceEntryResponseData>;
}

/**
 * Check if a given object implements the CompanyCreditBalancesResponseData interface.
 */
export function instanceOfCompanyCreditBalancesResponseData(
  value: object,
): value is CompanyCreditBalancesResponseData {
  if (!("balances" in value) || value["balances"] === undefined) return false;
  return true;
}

export function CompanyCreditBalancesResponseDataFromJSON(
  json: any,
): CompanyCreditBalancesResponseData {
  return CompanyCreditBalancesResponseDataFromJSONTyped(json, false);
}

export function CompanyCreditBalancesResponseDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CompanyCreditBalancesResponseData {
  if (json == null) {
    return json;
  }
  return {
    balances: (json["balances"] as Array<any>).map(
      CompanyCreditBalanceEntryResponseDataFromJSON,
    ),
  };
}

export function CompanyCreditBalancesResponseDataToJSON(
  json: any,
): CompanyCreditBalancesResponseData {
  return CompanyCreditBalancesResponseDataToJSONTyped(json, false);
}

export function CompanyCreditBalancesResponseDataToJSONTyped(
  value?: CompanyCreditBalancesResponseData | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    balances: (value["balances"] as Array<any>).map(
      CompanyCreditBalanceEntryResponseDataToJSON,
    ),
  };
}
