/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { RuleDetailResponseData } from "./RuleDetailResponseData";
import {
  RuleDetailResponseDataFromJSON,
  RuleDetailResponseDataFromJSONTyped,
  RuleDetailResponseDataToJSON,
} from "./RuleDetailResponseData";
import type { FeatureResponseData } from "./FeatureResponseData";
import {
  FeatureResponseDataFromJSON,
  FeatureResponseDataFromJSONTyped,
  FeatureResponseDataToJSON,
} from "./FeatureResponseData";

/**
 *
 * @export
 * @interface FlagDetailResponseData
 */
export interface FlagDetailResponseData {
  /**
   *
   * @type {Date}
   * @memberof FlagDetailResponseData
   */
  createdAt: Date;
  /**
   *
   * @type {boolean}
   * @memberof FlagDetailResponseData
   */
  defaultValue: boolean;
  /**
   *
   * @type {string}
   * @memberof FlagDetailResponseData
   */
  description: string;
  /**
   *
   * @type {FeatureResponseData}
   * @memberof FlagDetailResponseData
   */
  feature?: FeatureResponseData;
  /**
   *
   * @type {string}
   * @memberof FlagDetailResponseData
   */
  featureId?: string | null;
  /**
   *
   * @type {string}
   * @memberof FlagDetailResponseData
   */
  flagType: string;
  /**
   *
   * @type {string}
   * @memberof FlagDetailResponseData
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof FlagDetailResponseData
   */
  key: string;
  /**
   *
   * @type {Date}
   * @memberof FlagDetailResponseData
   */
  lastCheckedAt?: Date | null;
  /**
   *
   * @type {string}
   * @memberof FlagDetailResponseData
   */
  maintainerId?: string | null;
  /**
   *
   * @type {string}
   * @memberof FlagDetailResponseData
   */
  name: string;
  /**
   *
   * @type {Array<RuleDetailResponseData>}
   * @memberof FlagDetailResponseData
   */
  rules: Array<RuleDetailResponseData>;
  /**
   *
   * @type {Date}
   * @memberof FlagDetailResponseData
   */
  updatedAt: Date;
}

/**
 * Check if a given object implements the FlagDetailResponseData interface.
 */
export function instanceOfFlagDetailResponseData(
  value: object,
): value is FlagDetailResponseData {
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("defaultValue" in value) || value["defaultValue"] === undefined)
    return false;
  if (!("description" in value) || value["description"] === undefined)
    return false;
  if (!("flagType" in value) || value["flagType"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("key" in value) || value["key"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("rules" in value) || value["rules"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  return true;
}

export function FlagDetailResponseDataFromJSON(
  json: any,
): FlagDetailResponseData {
  return FlagDetailResponseDataFromJSONTyped(json, false);
}

export function FlagDetailResponseDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FlagDetailResponseData {
  if (json == null) {
    return json;
  }
  return {
    createdAt: new Date(json["created_at"]),
    defaultValue: json["default_value"],
    description: json["description"],
    feature:
      json["feature"] == null
        ? undefined
        : FeatureResponseDataFromJSON(json["feature"]),
    featureId: json["feature_id"] == null ? undefined : json["feature_id"],
    flagType: json["flag_type"],
    id: json["id"],
    key: json["key"],
    lastCheckedAt:
      json["last_checked_at"] == null
        ? undefined
        : new Date(json["last_checked_at"]),
    maintainerId:
      json["maintainer_id"] == null ? undefined : json["maintainer_id"],
    name: json["name"],
    rules: (json["rules"] as Array<any>).map(RuleDetailResponseDataFromJSON),
    updatedAt: new Date(json["updated_at"]),
  };
}

export function FlagDetailResponseDataToJSON(
  value?: FlagDetailResponseData | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    created_at: value["createdAt"].toISOString(),
    default_value: value["defaultValue"],
    description: value["description"],
    feature: FeatureResponseDataToJSON(value["feature"]),
    feature_id: value["featureId"],
    flag_type: value["flagType"],
    id: value["id"],
    key: value["key"],
    last_checked_at:
      value["lastCheckedAt"] == null
        ? undefined
        : (value["lastCheckedAt"] as any).toISOString(),
    maintainer_id: value["maintainerId"],
    name: value["name"],
    rules: (value["rules"] as Array<any>).map(RuleDetailResponseDataToJSON),
    updated_at: value["updatedAt"].toISOString(),
  };
}
