/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface BillingPlan
 */
export interface BillingPlan {
  /**
   *
   * @type {string}
   * @memberof BillingPlan
   */
  description?: string | null;
  /**
   *
   * @type {string}
   * @memberof BillingPlan
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof BillingPlan
   */
  imageUrl?: string | null;
  /**
   *
   * @type {string}
   * @memberof BillingPlan
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof BillingPlan
   */
  planPeriod?: string | null;
  /**
   *
   * @type {number}
   * @memberof BillingPlan
   */
  planPrice?: number | null;
}

/**
 * Check if a given object implements the BillingPlan interface.
 */
export function instanceOfBillingPlan(value: object): value is BillingPlan {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  return true;
}

export function BillingPlanFromJSON(json: any): BillingPlan {
  return BillingPlanFromJSONTyped(json, false);
}

export function BillingPlanFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BillingPlan {
  if (json == null) {
    return json;
  }
  return {
    description: json["description"] == null ? undefined : json["description"],
    id: json["id"],
    imageUrl: json["image_url"] == null ? undefined : json["image_url"],
    name: json["name"],
    planPeriod: json["plan_period"] == null ? undefined : json["plan_period"],
    planPrice: json["plan_price"] == null ? undefined : json["plan_price"],
  };
}

export function BillingPlanToJSON(value?: BillingPlan | null): any {
  if (value == null) {
    return value;
  }
  return {
    description: value["description"],
    id: value["id"],
    image_url: value["imageUrl"],
    name: value["name"],
    plan_period: value["planPeriod"],
    plan_price: value["planPrice"],
  };
}
