/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface BillingPriceResponseData
 */
export interface BillingPriceResponseData {
  /**
   *
   * @type {string}
   * @memberof BillingPriceResponseData
   */
  externalPriceId: string;
  /**
   *
   * @type {string}
   * @memberof BillingPriceResponseData
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof BillingPriceResponseData
   */
  interval: string;
  /**
   *
   * @type {number}
   * @memberof BillingPriceResponseData
   */
  price: number;
}

/**
 * Check if a given object implements the BillingPriceResponseData interface.
 */
export function instanceOfBillingPriceResponseData(
  value: object,
): value is BillingPriceResponseData {
  if (!("externalPriceId" in value) || value["externalPriceId"] === undefined)
    return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("interval" in value) || value["interval"] === undefined) return false;
  if (!("price" in value) || value["price"] === undefined) return false;
  return true;
}

export function BillingPriceResponseDataFromJSON(
  json: any,
): BillingPriceResponseData {
  return BillingPriceResponseDataFromJSONTyped(json, false);
}

export function BillingPriceResponseDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BillingPriceResponseData {
  if (json == null) {
    return json;
  }
  return {
    externalPriceId: json["external_price_id"],
    id: json["id"],
    interval: json["interval"],
    price: json["price"],
  };
}

export function BillingPriceResponseDataToJSON(
  value?: BillingPriceResponseData | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    external_price_id: value["externalPriceId"],
    id: value["id"],
    interval: value["interval"],
    price: value["price"],
  };
}
