/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface EntityTraitResponseData
 */
export interface EntityTraitResponseData {
  /**
   *
   * @type {Date}
   * @memberof EntityTraitResponseData
   */
  createdAt: Date;
  /**
   *
   * @type {string}
   * @memberof EntityTraitResponseData
   */
  definitionId: string;
  /**
   *
   * @type {string}
   * @memberof EntityTraitResponseData
   */
  environmentId: string;
  /**
   *
   * @type {string}
   * @memberof EntityTraitResponseData
   */
  id: string;
  /**
   *
   * @type {Date}
   * @memberof EntityTraitResponseData
   */
  updatedAt: Date;
  /**
   *
   * @type {string}
   * @memberof EntityTraitResponseData
   */
  value: string;
}

/**
 * Check if a given object implements the EntityTraitResponseData interface.
 */
export function instanceOfEntityTraitResponseData(
  value: object,
): value is EntityTraitResponseData {
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("definitionId" in value) || value["definitionId"] === undefined)
    return false;
  if (!("environmentId" in value) || value["environmentId"] === undefined)
    return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  if (!("value" in value) || value["value"] === undefined) return false;
  return true;
}

export function EntityTraitResponseDataFromJSON(
  json: any,
): EntityTraitResponseData {
  return EntityTraitResponseDataFromJSONTyped(json, false);
}

export function EntityTraitResponseDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): EntityTraitResponseData {
  if (json == null) {
    return json;
  }
  return {
    createdAt: new Date(json["created_at"]),
    definitionId: json["definition_id"],
    environmentId: json["environment_id"],
    id: json["id"],
    updatedAt: new Date(json["updated_at"]),
    value: json["value"],
  };
}

export function EntityTraitResponseDataToJSON(
  value?: EntityTraitResponseData | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    created_at: value["createdAt"].toISOString(),
    definition_id: value["definitionId"],
    environment_id: value["environmentId"],
    id: value["id"],
    updated_at: value["updatedAt"].toISOString(),
    value: value["value"],
  };
}
