/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const ComparableOperator = {
  Eq: "eq",
  Gt: "gt",
  Gte: "gte",
  IsEmpty: "is_empty",
  Lt: "lt",
  Lte: "lte",
  NotEmpty: "not_empty",
  Ne: "ne",
} as const;
export type ComparableOperator =
  (typeof ComparableOperator)[keyof typeof ComparableOperator];

export function instanceOfComparableOperator(value: any): boolean {
  for (const key in ComparableOperator) {
    if (Object.prototype.hasOwnProperty.call(ComparableOperator, key)) {
      if (
        ComparableOperator[key as keyof typeof ComparableOperator] === value
      ) {
        return true;
      }
    }
  }
  return false;
}

export function ComparableOperatorFromJSON(json: any): ComparableOperator {
  return ComparableOperatorFromJSONTyped(json, false);
}

export function ComparableOperatorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ComparableOperator {
  return json as ComparableOperator;
}

export function ComparableOperatorToJSON(
  value?: ComparableOperator | null,
): any {
  return value as any;
}

export function ComparableOperatorToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean,
): ComparableOperator {
  return value as ComparableOperator;
}
