/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const MetricPeriod = {
  AllTime: "all_time",
  CurrentDay: "current_day",
  CurrentMonth: "current_month",
  CurrentWeek: "current_week",
} as const;
export type MetricPeriod = (typeof MetricPeriod)[keyof typeof MetricPeriod];

export function instanceOfMetricPeriod(value: any): boolean {
  for (const key in MetricPeriod) {
    if (Object.prototype.hasOwnProperty.call(MetricPeriod, key)) {
      if (MetricPeriod[key as keyof typeof MetricPeriod] === value) {
        return true;
      }
    }
  }
  return false;
}

export function MetricPeriodFromJSON(json: any): MetricPeriod {
  return MetricPeriodFromJSONTyped(json, false);
}

export function MetricPeriodFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MetricPeriod {
  return json as MetricPeriod;
}

export function MetricPeriodToJSON(value?: MetricPeriod | null): any {
  return value as any;
}

export function MetricPeriodToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean,
): MetricPeriod {
  return value as MetricPeriod;
}
