/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const PlanIcon = {
  Amber: "amber",
  Blue: "blue",
  BlueGray: "blueGray",
  BlueGreen: "blueGreen",
  Cyan: "cyan",
  Emerald: "emerald",
  Fuchsia: "fuchsia",
  Gray: "gray",
  Green: "green",
  Indigo: "indigo",
  LightBlue: "lightBlue",
  Lime: "lime",
  Orange: "orange",
  Pink: "pink",
  Purple: "purple",
  Red: "red",
  RedOrange: "redOrange",
  Rose: "rose",
  Sky: "sky",
  Slate: "slate",
  Teal: "teal",
  TrueGray: "trueGray",
  Violet: "violet",
  WarmGray: "warmGray",
  Yellow: "yellow",
} as const;
export type PlanIcon = (typeof PlanIcon)[keyof typeof PlanIcon];

export function instanceOfPlanIcon(value: any): boolean {
  for (const key in PlanIcon) {
    if (Object.prototype.hasOwnProperty.call(PlanIcon, key)) {
      if (PlanIcon[key as keyof typeof PlanIcon] === value) {
        return true;
      }
    }
  }
  return false;
}

export function PlanIconFromJSON(json: any): PlanIcon {
  return PlanIconFromJSONTyped(json, false);
}

export function PlanIconFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PlanIcon {
  return json as PlanIcon;
}

export function PlanIconToJSON(value?: PlanIcon | null): any {
  return value as any;
}

export function PlanIconToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean,
): PlanIcon {
  return value as PlanIcon;
}
