/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  ApiError,
  IssueTemporaryAccessTokenRequestBody,
  IssueTemporaryAccessTokenResponse,
} from "../models/index";
import {
  ApiErrorFromJSON,
  ApiErrorToJSON,
  IssueTemporaryAccessTokenRequestBodyFromJSON,
  IssueTemporaryAccessTokenRequestBodyToJSON,
  IssueTemporaryAccessTokenResponseFromJSON,
  IssueTemporaryAccessTokenResponseToJSON,
} from "../models/index";

export interface IssueTemporaryAccessTokenRequest {
  issueTemporaryAccessTokenRequestBody: IssueTemporaryAccessTokenRequestBody;
}

/**
 *
 */
export class AccesstokensApi extends runtime.BaseAPI {
  /**
   * Issue temporary access token
   */
  async issueTemporaryAccessTokenRaw(
    requestParameters: IssueTemporaryAccessTokenRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<IssueTemporaryAccessTokenResponse>> {
    if (requestParameters["issueTemporaryAccessTokenRequestBody"] == null) {
      throw new runtime.RequiredError(
        "issueTemporaryAccessTokenRequestBody",
        'Required parameter "issueTemporaryAccessTokenRequestBody" was null or undefined when calling issueTemporaryAccessToken().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["X-Schematic-Api-Key"] = await this.configuration.apiKey(
        "X-Schematic-Api-Key",
      ); // ApiKeyAuth authentication
    }

    const response = await this.request(
      {
        path: `/temporary-access-tokens`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: IssueTemporaryAccessTokenRequestBodyToJSON(
          requestParameters["issueTemporaryAccessTokenRequestBody"],
        ),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      IssueTemporaryAccessTokenResponseFromJSON(jsonValue),
    );
  }

  /**
   * Issue temporary access token
   */
  async issueTemporaryAccessToken(
    requestParameters: IssueTemporaryAccessTokenRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<IssueTemporaryAccessTokenResponse> {
    const response = await this.issueTemporaryAccessTokenRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
