/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CheckFlagResponseData } from "./CheckFlagResponseData";
import {
  CheckFlagResponseDataFromJSON,
  CheckFlagResponseDataFromJSONTyped,
  CheckFlagResponseDataToJSON,
  CheckFlagResponseDataToJSONTyped,
} from "./CheckFlagResponseData";

/**
 *
 * @export
 * @interface CheckFlagsResponseData
 */
export interface CheckFlagsResponseData {
  /**
   *
   * @type {Array<CheckFlagResponseData>}
   * @memberof CheckFlagsResponseData
   */
  flags: Array<CheckFlagResponseData>;
}

/**
 * Check if a given object implements the CheckFlagsResponseData interface.
 */
export function instanceOfCheckFlagsResponseData(
  value: object,
): value is CheckFlagsResponseData {
  if (!("flags" in value) || value["flags"] === undefined) return false;
  return true;
}

export function CheckFlagsResponseDataFromJSON(
  json: any,
): CheckFlagsResponseData {
  return CheckFlagsResponseDataFromJSONTyped(json, false);
}

export function CheckFlagsResponseDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CheckFlagsResponseData {
  if (json == null) {
    return json;
  }
  return {
    flags: (json["flags"] as Array<any>).map(CheckFlagResponseDataFromJSON),
  };
}

export function CheckFlagsResponseDataToJSON(
  json: any,
): CheckFlagsResponseData {
  return CheckFlagsResponseDataToJSONTyped(json, false);
}

export function CheckFlagsResponseDataToJSONTyped(
  value?: CheckFlagsResponseData | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    flags: (value["flags"] as Array<any>).map(CheckFlagResponseDataToJSON),
  };
}
