/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreditSpendWindow
 */
export interface CreditSpendWindow {
  /**
   * How many units make up one period
   * @type {number}
   * @memberof CreditSpendWindow
   */
  count: number;
  /**
   * The period the limit accumulates over
   * @type {string}
   * @memberof CreditSpendWindow
   */
  unit: string;
}

/**
 * Check if a given object implements the CreditSpendWindow interface.
 */
export function instanceOfCreditSpendWindow(
  value: object,
): value is CreditSpendWindow {
  if (!("count" in value) || value["count"] === undefined) return false;
  if (!("unit" in value) || value["unit"] === undefined) return false;
  return true;
}

export function CreditSpendWindowFromJSON(json: any): CreditSpendWindow {
  return CreditSpendWindowFromJSONTyped(json, false);
}

export function CreditSpendWindowFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreditSpendWindow {
  if (json == null) {
    return json;
  }
  return {
    count: json["count"],
    unit: json["unit"],
  };
}

export function CreditSpendWindowToJSON(json: any): CreditSpendWindow {
  return CreditSpendWindowToJSONTyped(json, false);
}

export function CreditSpendWindowToJSONTyped(
  value?: CreditSpendWindow | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    count: value["count"],
    unit: value["unit"],
  };
}
