/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GenericPreviewObject
 */
export interface GenericPreviewObject {
  /**
   *
   * @type {string}
   * @memberof GenericPreviewObject
   */
  description?: string | null;
  /**
   *
   * @type {string}
   * @memberof GenericPreviewObject
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof GenericPreviewObject
   */
  imageUrl?: string | null;
  /**
   *
   * @type {string}
   * @memberof GenericPreviewObject
   */
  name: string;
}

/**
 * Check if a given object implements the GenericPreviewObject interface.
 */
export function instanceOfGenericPreviewObject(
  value: object,
): value is GenericPreviewObject {
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  return true;
}

export function GenericPreviewObjectFromJSON(json: any): GenericPreviewObject {
  return GenericPreviewObjectFromJSONTyped(json, false);
}

export function GenericPreviewObjectFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GenericPreviewObject {
  if (json == null) {
    return json;
  }
  return {
    description: json["description"] == null ? undefined : json["description"],
    id: json["id"],
    imageUrl: json["image_url"] == null ? undefined : json["image_url"],
    name: json["name"],
  };
}

export function GenericPreviewObjectToJSON(
  value?: GenericPreviewObject | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    description: value["description"],
    id: value["id"],
    image_url: value["imageUrl"],
    name: value["name"],
  };
}
