/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const PlanPriceCadence = {
  Monthly: "monthly",
  Quarterly: "quarterly",
  Yearly: "yearly",
} as const;
export type PlanPriceCadence =
  (typeof PlanPriceCadence)[keyof typeof PlanPriceCadence];

export function instanceOfPlanPriceCadence(value: any): boolean {
  for (const key in PlanPriceCadence) {
    if (Object.prototype.hasOwnProperty.call(PlanPriceCadence, key)) {
      if (PlanPriceCadence[key as keyof typeof PlanPriceCadence] === value) {
        return true;
      }
    }
  }
  return false;
}

export function PlanPriceCadenceFromJSON(json: any): PlanPriceCadence {
  return PlanPriceCadenceFromJSONTyped(json, false);
}

export function PlanPriceCadenceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PlanPriceCadence {
  return json as PlanPriceCadence;
}

export function PlanPriceCadenceToJSON(value?: PlanPriceCadence | null): any {
  return value as any;
}

export function PlanPriceCadenceToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean,
): PlanPriceCadence {
  return value as PlanPriceCadence;
}
