/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { FeatureDetailResponseData } from "./FeatureDetailResponseData";
import {
  FeatureDetailResponseDataFromJSON,
  FeatureDetailResponseDataFromJSONTyped,
  FeatureDetailResponseDataToJSON,
} from "./FeatureDetailResponseData";
import type { PlanEntitlementResponseData } from "./PlanEntitlementResponseData";
import {
  PlanEntitlementResponseDataFromJSON,
  PlanEntitlementResponseDataFromJSONTyped,
  PlanEntitlementResponseDataToJSON,
} from "./PlanEntitlementResponseData";
import type { BillingPriceResponseData } from "./BillingPriceResponseData";
import {
  BillingPriceResponseDataFromJSON,
  BillingPriceResponseDataFromJSONTyped,
  BillingPriceResponseDataToJSON,
} from "./BillingPriceResponseData";
import type { CustomPlanConfig } from "./CustomPlanConfig";
import {
  CustomPlanConfigFromJSON,
  CustomPlanConfigFromJSONTyped,
  CustomPlanConfigToJSON,
} from "./CustomPlanConfig";
import type { BillingProductDetailResponseData } from "./BillingProductDetailResponseData";
import {
  BillingProductDetailResponseDataFromJSON,
  BillingProductDetailResponseDataFromJSONTyped,
  BillingProductDetailResponseDataToJSON,
} from "./BillingProductDetailResponseData";

/**
 *
 * @export
 * @interface PlanViewPublicResponseData
 */
export interface PlanViewPublicResponseData {
  /**
   *
   * @type {string}
   * @memberof PlanViewPublicResponseData
   */
  audienceType?: string | null;
  /**
   *
   * @type {BillingProductDetailResponseData}
   * @memberof PlanViewPublicResponseData
   */
  billingProduct?: BillingProductDetailResponseData;
  /**
   *
   * @type {string}
   * @memberof PlanViewPublicResponseData
   */
  chargeType: string;
  /**
   *
   * @type {number}
   * @memberof PlanViewPublicResponseData
   */
  companyCount: number;
  /**
   *
   * @type {Date}
   * @memberof PlanViewPublicResponseData
   */
  createdAt: Date;
  /**
   *
   * @type {boolean}
   * @memberof PlanViewPublicResponseData
   */
  custom: boolean;
  /**
   *
   * @type {CustomPlanConfig}
   * @memberof PlanViewPublicResponseData
   */
  customPlanConfig?: CustomPlanConfig;
  /**
   *
   * @type {string}
   * @memberof PlanViewPublicResponseData
   */
  description: string;
  /**
   *
   * @type {Array<PlanEntitlementResponseData>}
   * @memberof PlanViewPublicResponseData
   */
  entitlements: Array<PlanEntitlementResponseData>;
  /**
   *
   * @type {Array<FeatureDetailResponseData>}
   * @memberof PlanViewPublicResponseData
   */
  features: Array<FeatureDetailResponseData>;
  /**
   *
   * @type {string}
   * @memberof PlanViewPublicResponseData
   */
  icon: string;
  /**
   *
   * @type {string}
   * @memberof PlanViewPublicResponseData
   */
  id: string;
  /**
   *
   * @type {boolean}
   * @memberof PlanViewPublicResponseData
   */
  isCustom: boolean;
  /**
   *
   * @type {boolean}
   * @memberof PlanViewPublicResponseData
   */
  isDefault: boolean;
  /**
   *
   * @type {boolean}
   * @memberof PlanViewPublicResponseData
   */
  isFree: boolean;
  /**
   *
   * @type {boolean}
   * @memberof PlanViewPublicResponseData
   */
  isTrialable: boolean;
  /**
   *
   * @type {BillingPriceResponseData}
   * @memberof PlanViewPublicResponseData
   */
  monthlyPrice?: BillingPriceResponseData;
  /**
   *
   * @type {string}
   * @memberof PlanViewPublicResponseData
   */
  name: string;
  /**
   *
   * @type {BillingPriceResponseData}
   * @memberof PlanViewPublicResponseData
   */
  oneTimePrice?: BillingPriceResponseData;
  /**
   *
   * @type {string}
   * @memberof PlanViewPublicResponseData
   */
  planType: string;
  /**
   *
   * @type {number}
   * @memberof PlanViewPublicResponseData
   */
  trialDays?: number | null;
  /**
   *
   * @type {Date}
   * @memberof PlanViewPublicResponseData
   */
  updatedAt: Date;
  /**
   *
   * @type {BillingPriceResponseData}
   * @memberof PlanViewPublicResponseData
   */
  yearlyPrice?: BillingPriceResponseData;
}

/**
 * Check if a given object implements the PlanViewPublicResponseData interface.
 */
export function instanceOfPlanViewPublicResponseData(
  value: object,
): value is PlanViewPublicResponseData {
  if (!("chargeType" in value) || value["chargeType"] === undefined)
    return false;
  if (!("companyCount" in value) || value["companyCount"] === undefined)
    return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("custom" in value) || value["custom"] === undefined) return false;
  if (!("description" in value) || value["description"] === undefined)
    return false;
  if (!("entitlements" in value) || value["entitlements"] === undefined)
    return false;
  if (!("features" in value) || value["features"] === undefined) return false;
  if (!("icon" in value) || value["icon"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("isCustom" in value) || value["isCustom"] === undefined) return false;
  if (!("isDefault" in value) || value["isDefault"] === undefined) return false;
  if (!("isFree" in value) || value["isFree"] === undefined) return false;
  if (!("isTrialable" in value) || value["isTrialable"] === undefined)
    return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("planType" in value) || value["planType"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  return true;
}

export function PlanViewPublicResponseDataFromJSON(
  json: any,
): PlanViewPublicResponseData {
  return PlanViewPublicResponseDataFromJSONTyped(json, false);
}

export function PlanViewPublicResponseDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PlanViewPublicResponseData {
  if (json == null) {
    return json;
  }
  return {
    audienceType:
      json["audience_type"] == null ? undefined : json["audience_type"],
    billingProduct:
      json["billing_product"] == null
        ? undefined
        : BillingProductDetailResponseDataFromJSON(json["billing_product"]),
    chargeType: json["charge_type"],
    companyCount: json["company_count"],
    createdAt: new Date(json["created_at"]),
    custom: json["custom"],
    customPlanConfig:
      json["custom_plan_config"] == null
        ? undefined
        : CustomPlanConfigFromJSON(json["custom_plan_config"]),
    description: json["description"],
    entitlements: (json["entitlements"] as Array<any>).map(
      PlanEntitlementResponseDataFromJSON,
    ),
    features: (json["features"] as Array<any>).map(
      FeatureDetailResponseDataFromJSON,
    ),
    icon: json["icon"],
    id: json["id"],
    isCustom: json["is_custom"],
    isDefault: json["is_default"],
    isFree: json["is_free"],
    isTrialable: json["is_trialable"],
    monthlyPrice:
      json["monthly_price"] == null
        ? undefined
        : BillingPriceResponseDataFromJSON(json["monthly_price"]),
    name: json["name"],
    oneTimePrice:
      json["one_time_price"] == null
        ? undefined
        : BillingPriceResponseDataFromJSON(json["one_time_price"]),
    planType: json["plan_type"],
    trialDays: json["trial_days"] == null ? undefined : json["trial_days"],
    updatedAt: new Date(json["updated_at"]),
    yearlyPrice:
      json["yearly_price"] == null
        ? undefined
        : BillingPriceResponseDataFromJSON(json["yearly_price"]),
  };
}

export function PlanViewPublicResponseDataToJSON(
  value?: PlanViewPublicResponseData | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    audience_type: value["audienceType"],
    billing_product: BillingProductDetailResponseDataToJSON(
      value["billingProduct"],
    ),
    charge_type: value["chargeType"],
    company_count: value["companyCount"],
    created_at: value["createdAt"].toISOString(),
    custom: value["custom"],
    custom_plan_config: CustomPlanConfigToJSON(value["customPlanConfig"]),
    description: value["description"],
    entitlements: (value["entitlements"] as Array<any>).map(
      PlanEntitlementResponseDataToJSON,
    ),
    features: (value["features"] as Array<any>).map(
      FeatureDetailResponseDataToJSON,
    ),
    icon: value["icon"],
    id: value["id"],
    is_custom: value["isCustom"],
    is_default: value["isDefault"],
    is_free: value["isFree"],
    is_trialable: value["isTrialable"],
    monthly_price: BillingPriceResponseDataToJSON(value["monthlyPrice"]),
    name: value["name"],
    one_time_price: BillingPriceResponseDataToJSON(value["oneTimePrice"]),
    plan_type: value["planType"],
    trial_days: value["trialDays"],
    updated_at: value["updatedAt"].toISOString(),
    yearly_price: BillingPriceResponseDataToJSON(value["yearlyPrice"]),
  };
}
