/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { PreflightEventUsageRequestBody } from "./PreflightEventUsageRequestBody";
import {
  PreflightEventUsageRequestBodyFromJSON,
  PreflightEventUsageRequestBodyFromJSONTyped,
  PreflightEventUsageRequestBodyToJSON,
  PreflightEventUsageRequestBodyToJSONTyped,
} from "./PreflightEventUsageRequestBody";

/**
 *
 * @export
 * @interface PreflightRequestBody
 */
export interface PreflightRequestBody {
  /**
   * Cost in credits of the action, keyed by credit ID, for callers that have already computed it. Takes precedence over usage and event_usage on credit balance conditions for the same credit. A cost of zero means the action is free, not that the input is absent
   * @type {{ [key: string]: number; }}
   * @memberof PreflightRequestBody
   */
  creditCost?: { [key: string]: number };
  /**
   * Usage of a specific event subtype. Preferred over usage when the subtype is known, since it only affects conditions measuring that subtype
   * @type {PreflightEventUsageRequestBody}
   * @memberof PreflightRequestBody
   */
  eventUsage?: PreflightEventUsageRequestBody;
  /**
   * Quantity of usage to simulate against any numeric condition encountered while evaluating the flag. Zero has no effect
   * @type {number}
   * @memberof PreflightRequestBody
   */
  usage?: number | null;
}

/**
 * Check if a given object implements the PreflightRequestBody interface.
 */
export function instanceOfPreflightRequestBody(
  value: object,
): value is PreflightRequestBody {
  return true;
}

export function PreflightRequestBodyFromJSON(json: any): PreflightRequestBody {
  return PreflightRequestBodyFromJSONTyped(json, false);
}

export function PreflightRequestBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PreflightRequestBody {
  if (json == null) {
    return json;
  }
  return {
    creditCost: json["credit_cost"] == null ? undefined : json["credit_cost"],
    eventUsage:
      json["event_usage"] == null
        ? undefined
        : PreflightEventUsageRequestBodyFromJSON(json["event_usage"]),
    usage: json["usage"] == null ? undefined : json["usage"],
  };
}

export function PreflightRequestBodyToJSON(json: any): PreflightRequestBody {
  return PreflightRequestBodyToJSONTyped(json, false);
}

export function PreflightRequestBodyToJSONTyped(
  value?: PreflightRequestBody | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    credit_cost: value["creditCost"],
    event_usage: PreflightEventUsageRequestBodyToJSON(value["eventUsage"]),
    usage: value["usage"],
  };
}
