#!/usr/bin/env node
/**
 * Inlines the schematic-icons font into the elements stylesheet.
 *
 * Reads the installed `@schematichq/schematic-icons` CSS and writes
 * `src/elements/styles/icons.ts`: the `@font-face` as shipped (plus
 * `font-display: block`), a `.schematic-icon` base rule, and one
 * `.schematic-icon--<name>::before` per glyph. The package's own selectors
 * (`i[class^="icon-"]`, `.icon-*`) are not reused: they are global, carry
 * `!important`, and would collide with a host that loads the package itself.
 *
 *   pnpm run icons
 */
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);

// `styles.css` is the only file path the package exports; the manifest and
// the glyph map sit beside it.
const cssPath = require.resolve("@schematichq/schematic-icons/styles.css");
const distDir = dirname(cssPath);
const { version } = JSON.parse(
  readFileSync(join(distDir, "..", "package.json"), "utf8"),
);
const css = readFileSync(cssPath, "utf8");

const fontFaceMatch = css.match(/@font-face\s*\{[^}]*\}/);
if (fontFaceMatch === null) {
  throw new Error(`No @font-face in ${cssPath}`);
}
if (fontFaceMatch[0].includes("font-display")) {
  throw new Error("The package now sets font-display; drop the injection.");
}
const fontFace = fontFaceMatch[0]
  .replace(/\n\s+/g, "\n  ")
  .replace(/\n\}$/, "\n  font-display: block;\n}");

const glyphs = [];
for (const [, name, codepoint] of css.matchAll(
  /\.icon-([a-z0-9-]+):before\s*\{\s*content:\s*"(\\[0-9a-f]+)";?\s*\}/g,
)) {
  glyphs.push([name, codepoint]);
}
if (glyphs.length === 0) {
  throw new Error(`No .icon-* rules in ${cssPath}`);
}

const rules = [
  fontFace,
  "",
  `.schematic-icon {
  display: inline-block;
  font-family: "schematic-icons";
  font-style: normal;
  font-variant: normal;
  font-weight: normal;
  line-height: 1;
  speak: never;
  text-transform: none;
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
}`,
  "",
  ...glyphs.map(
    ([name, codepoint]) =>
      `.schematic-icon--${name}::before {\n  content: "${codepoint}";\n}`,
  ),
].join("\n");

// The rules go into a raw template literal, so a backslash survives as
// written; the only characters that could still break out are checked.
if (/`|\$\{/.test(rules) || rules.endsWith("\\")) {
  throw new Error("The CSS cannot be embedded in a template literal as is.");
}

const header = `/* eslint-disable */
/**
 * GENERATED by scripts/inline-icons.mjs from @schematichq/schematic-icons@${version}.
 * Do not edit; run \`pnpm run icons\` after bumping the package.
 *
 * The icon font and its glyph rules, appended to the elements stylesheet by
 * \`<SchematicStyles />\`. Glyphs render on \`.schematic-icon
 * .schematic-icon--<name>\`.
 */

// prettier-ignore
export const iconsCss: string = String.raw\`
`;

const out = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "src",
  "elements",
  "styles",
  "icons.ts",
);
writeFileSync(out, `${header}${rules}\n\`;\n`);
console.log(
  `Wrote ${out}: ${glyphs.length} glyphs from @schematichq/schematic-icons@${version}`,
);
