/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { ApiError, GetCompanyInvoicesResponse } from "../models/index";
import {
  ApiErrorFromJSON,
  ApiErrorToJSON,
  GetCompanyInvoicesResponseFromJSON,
  GetCompanyInvoicesResponseToJSON,
} from "../models/index";

export interface GetCompanyInvoicesRequest {
  includePending?: boolean;
  limit?: number;
  offset?: number;
}

/**
 *
 */
export class CheckoutexternalApi extends runtime.BaseAPI {
  /**
   * Get company invoices
   */
  async getCompanyInvoicesRaw(
    requestParameters: GetCompanyInvoicesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetCompanyInvoicesResponse>> {
    const queryParameters: any = {};

    if (requestParameters["includePending"] != null) {
      queryParameters["include_pending"] = requestParameters["includePending"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["X-Schematic-Api-Key"] = await this.configuration.apiKey(
        "X-Schematic-Api-Key",
      ); // ApiKeyAuth authentication
    }

    const response = await this.request(
      {
        path: `/company/invoices`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetCompanyInvoicesResponseFromJSON(jsonValue),
    );
  }

  /**
   * Get company invoices
   */
  async getCompanyInvoices(
    requestParameters: GetCompanyInvoicesRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetCompanyInvoicesResponse> {
    const response = await this.getCompanyInvoicesRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
