/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CountComponentsParams } from "./CountComponentsParams";
import {
  CountComponentsParamsFromJSON,
  CountComponentsParamsFromJSONTyped,
  CountComponentsParamsToJSON,
  CountComponentsParamsToJSONTyped,
} from "./CountComponentsParams";
import type { CountResponse } from "./CountResponse";
import {
  CountResponseFromJSON,
  CountResponseFromJSONTyped,
  CountResponseToJSON,
  CountResponseToJSONTyped,
} from "./CountResponse";

/**
 *
 * @export
 * @interface CountComponentsResponse
 */
export interface CountComponentsResponse {
  /**
   *
   * @type {CountResponse}
   * @memberof CountComponentsResponse
   */
  data: CountResponse;
  /**
   *
   * @type {CountComponentsParams}
   * @memberof CountComponentsResponse
   */
  params: CountComponentsParams;
}

/**
 * Check if a given object implements the CountComponentsResponse interface.
 */
export function instanceOfCountComponentsResponse(
  value: object,
): value is CountComponentsResponse {
  if (!("data" in value) || value["data"] === undefined) return false;
  if (!("params" in value) || value["params"] === undefined) return false;
  return true;
}

export function CountComponentsResponseFromJSON(
  json: any,
): CountComponentsResponse {
  return CountComponentsResponseFromJSONTyped(json, false);
}

export function CountComponentsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CountComponentsResponse {
  if (json == null) {
    return json;
  }
  return {
    data: CountResponseFromJSON(json["data"]),
    params: CountComponentsParamsFromJSON(json["params"]),
  };
}

export function CountComponentsResponseToJSON(
  json: any,
): CountComponentsResponse {
  return CountComponentsResponseToJSONTyped(json, false);
}

export function CountComponentsResponseToJSONTyped(
  value?: CountComponentsResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data: CountResponseToJSON(value["data"]),
    params: CountComponentsParamsToJSON(value["params"]),
  };
}
