/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CountFeatureCompaniesParams } from "./CountFeatureCompaniesParams";
import {
  CountFeatureCompaniesParamsFromJSON,
  CountFeatureCompaniesParamsFromJSONTyped,
  CountFeatureCompaniesParamsToJSON,
  CountFeatureCompaniesParamsToJSONTyped,
} from "./CountFeatureCompaniesParams";
import type { CountResponse } from "./CountResponse";
import {
  CountResponseFromJSON,
  CountResponseFromJSONTyped,
  CountResponseToJSON,
  CountResponseToJSONTyped,
} from "./CountResponse";

/**
 *
 * @export
 * @interface CountFeatureCompaniesResponse
 */
export interface CountFeatureCompaniesResponse {
  /**
   *
   * @type {CountResponse}
   * @memberof CountFeatureCompaniesResponse
   */
  data: CountResponse;
  /**
   *
   * @type {CountFeatureCompaniesParams}
   * @memberof CountFeatureCompaniesResponse
   */
  params: CountFeatureCompaniesParams;
}

/**
 * Check if a given object implements the CountFeatureCompaniesResponse interface.
 */
export function instanceOfCountFeatureCompaniesResponse(
  value: object,
): value is CountFeatureCompaniesResponse {
  if (!("data" in value) || value["data"] === undefined) return false;
  if (!("params" in value) || value["params"] === undefined) return false;
  return true;
}

export function CountFeatureCompaniesResponseFromJSON(
  json: any,
): CountFeatureCompaniesResponse {
  return CountFeatureCompaniesResponseFromJSONTyped(json, false);
}

export function CountFeatureCompaniesResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CountFeatureCompaniesResponse {
  if (json == null) {
    return json;
  }
  return {
    data: CountResponseFromJSON(json["data"]),
    params: CountFeatureCompaniesParamsFromJSON(json["params"]),
  };
}

export function CountFeatureCompaniesResponseToJSON(
  json: any,
): CountFeatureCompaniesResponse {
  return CountFeatureCompaniesResponseToJSONTyped(json, false);
}

export function CountFeatureCompaniesResponseToJSONTyped(
  value?: CountFeatureCompaniesResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data: CountResponseToJSON(value["data"]),
    params: CountFeatureCompaniesParamsToJSON(value["params"]),
  };
}
