/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Input parameters
 * @export
 * @interface CountUsersParams
 */
export interface CountUsersParams {
  /**
   * Filter users by company ID (starts with comp_)
   * @type {string}
   * @memberof CountUsersParams
   */
  companyId?: string;
  /**
   * Filter users by multiple user IDs (starts with user_)
   * @type {Array<string>}
   * @memberof CountUsersParams
   */
  ids?: Array<string>;
  /**
   * Page limit (default 100)
   * @type {number}
   * @memberof CountUsersParams
   */
  limit?: number;
  /**
   * Page offset (default 0)
   * @type {number}
   * @memberof CountUsersParams
   */
  offset?: number;
  /**
   * Filter users by plan ID (starts with plan_)
   * @type {string}
   * @memberof CountUsersParams
   */
  planId?: string;
  /**
   * Search for users by name, keys or string traits
   * @type {string}
   * @memberof CountUsersParams
   */
  q?: string;
}

/**
 * Check if a given object implements the CountUsersParams interface.
 */
export function instanceOfCountUsersParams(
  value: object,
): value is CountUsersParams {
  return true;
}

export function CountUsersParamsFromJSON(json: any): CountUsersParams {
  return CountUsersParamsFromJSONTyped(json, false);
}

export function CountUsersParamsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CountUsersParams {
  if (json == null) {
    return json;
  }
  return {
    companyId: json["company_id"] == null ? undefined : json["company_id"],
    ids: json["ids"] == null ? undefined : json["ids"],
    limit: json["limit"] == null ? undefined : json["limit"],
    offset: json["offset"] == null ? undefined : json["offset"],
    planId: json["plan_id"] == null ? undefined : json["plan_id"],
    q: json["q"] == null ? undefined : json["q"],
  };
}

export function CountUsersParamsToJSON(json: any): CountUsersParams {
  return CountUsersParamsToJSONTyped(json, false);
}

export function CountUsersParamsToJSONTyped(
  value?: CountUsersParams | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    company_id: value["companyId"],
    ids: value["ids"],
    limit: value["limit"],
    offset: value["offset"],
    plan_id: value["planId"],
    q: value["q"],
  };
}
