/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Input parameters
 * @export
 * @interface CountPlansParams
 */
export interface CountPlansParams {
  /**
   *
   * @type {string}
   * @memberof CountPlansParams
   */
  companyId?: string;
  /**
   * Filter out plans that do not have a billing product ID
   * @type {boolean}
   * @memberof CountPlansParams
   */
  hasProductId?: boolean;
  /**
   *
   * @type {Array<string>}
   * @memberof CountPlansParams
   */
  ids?: Array<string>;
  /**
   * Page limit (default 100)
   * @type {number}
   * @memberof CountPlansParams
   */
  limit?: number;
  /**
   * Page offset (default 0)
   * @type {number}
   * @memberof CountPlansParams
   */
  offset?: number;
  /**
   * Filter by plan type
   * @type {string}
   * @memberof CountPlansParams
   */
  planType?: CountPlansParamsPlanTypeEnum;
  /**
   *
   * @type {string}
   * @memberof CountPlansParams
   */
  q?: string;
  /**
   * Filter out plans that already have a plan entitlement for the specified feature ID
   * @type {string}
   * @memberof CountPlansParams
   */
  withoutEntitlementFor?: string;
  /**
   * Filter out plans that have a billing product ID
   * @type {boolean}
   * @memberof CountPlansParams
   */
  withoutProductId?: boolean;
}

/**
 * @export
 */
export const CountPlansParamsPlanTypeEnum = {
  Plan: "plan",
  AddOn: "add_on",
} as const;
export type CountPlansParamsPlanTypeEnum =
  (typeof CountPlansParamsPlanTypeEnum)[keyof typeof CountPlansParamsPlanTypeEnum];

/**
 * Check if a given object implements the CountPlansParams interface.
 */
export function instanceOfCountPlansParams(
  value: object,
): value is CountPlansParams {
  return true;
}

export function CountPlansParamsFromJSON(json: any): CountPlansParams {
  return CountPlansParamsFromJSONTyped(json, false);
}

export function CountPlansParamsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CountPlansParams {
  if (json == null) {
    return json;
  }
  return {
    companyId: json["company_id"] == null ? undefined : json["company_id"],
    hasProductId:
      json["has_product_id"] == null ? undefined : json["has_product_id"],
    ids: json["ids"] == null ? undefined : json["ids"],
    limit: json["limit"] == null ? undefined : json["limit"],
    offset: json["offset"] == null ? undefined : json["offset"],
    planType: json["plan_type"] == null ? undefined : json["plan_type"],
    q: json["q"] == null ? undefined : json["q"],
    withoutEntitlementFor:
      json["without_entitlement_for"] == null
        ? undefined
        : json["without_entitlement_for"],
    withoutProductId:
      json["without_product_id"] == null
        ? undefined
        : json["without_product_id"],
  };
}

export function CountPlansParamsToJSON(json: any): CountPlansParams {
  return CountPlansParamsToJSONTyped(json, false);
}

export function CountPlansParamsToJSONTyped(
  value?: CountPlansParams | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    company_id: value["companyId"],
    has_product_id: value["hasProductId"],
    ids: value["ids"],
    limit: value["limit"],
    offset: value["offset"],
    plan_type: value["planType"],
    q: value["q"],
    without_entitlement_for: value["withoutEntitlementFor"],
    without_product_id: value["withoutProductId"],
  };
}
