/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateCrmLineItemRequestBody
 */
export interface CreateCrmLineItemRequestBody {
  /**
   *
   * @type {string}
   * @memberof CreateCrmLineItemRequestBody
   */
  amount: string;
  /**
   *
   * @type {string}
   * @memberof CreateCrmLineItemRequestBody
   */
  discountPercentage?: string | null;
  /**
   *
   * @type {string}
   * @memberof CreateCrmLineItemRequestBody
   */
  interval: string;
  /**
   *
   * @type {string}
   * @memberof CreateCrmLineItemRequestBody
   */
  lineItemExternalId: string;
  /**
   *
   * @type {string}
   * @memberof CreateCrmLineItemRequestBody
   */
  productExternalId: string;
  /**
   *
   * @type {number}
   * @memberof CreateCrmLineItemRequestBody
   */
  quantity: number;
  /**
   *
   * @type {number}
   * @memberof CreateCrmLineItemRequestBody
   */
  termMonth?: number | null;
  /**
   *
   * @type {string}
   * @memberof CreateCrmLineItemRequestBody
   */
  totalDiscount?: string | null;
}

/**
 * Check if a given object implements the CreateCrmLineItemRequestBody interface.
 */
export function instanceOfCreateCrmLineItemRequestBody(
  value: object,
): value is CreateCrmLineItemRequestBody {
  if (!("amount" in value) || value["amount"] === undefined) return false;
  if (!("interval" in value) || value["interval"] === undefined) return false;
  if (
    !("lineItemExternalId" in value) ||
    value["lineItemExternalId"] === undefined
  )
    return false;
  if (
    !("productExternalId" in value) ||
    value["productExternalId"] === undefined
  )
    return false;
  if (!("quantity" in value) || value["quantity"] === undefined) return false;
  return true;
}

export function CreateCrmLineItemRequestBodyFromJSON(
  json: any,
): CreateCrmLineItemRequestBody {
  return CreateCrmLineItemRequestBodyFromJSONTyped(json, false);
}

export function CreateCrmLineItemRequestBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateCrmLineItemRequestBody {
  if (json == null) {
    return json;
  }
  return {
    amount: json["amount"],
    discountPercentage:
      json["discount_percentage"] == null
        ? undefined
        : json["discount_percentage"],
    interval: json["interval"],
    lineItemExternalId: json["line_item_external_id"],
    productExternalId: json["product_external_id"],
    quantity: json["quantity"],
    termMonth: json["term_month"] == null ? undefined : json["term_month"],
    totalDiscount:
      json["total_discount"] == null ? undefined : json["total_discount"],
  };
}

export function CreateCrmLineItemRequestBodyToJSON(
  json: any,
): CreateCrmLineItemRequestBody {
  return CreateCrmLineItemRequestBodyToJSONTyped(json, false);
}

export function CreateCrmLineItemRequestBodyToJSONTyped(
  value?: CreateCrmLineItemRequestBody | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    amount: value["amount"],
    discount_percentage: value["discountPercentage"],
    interval: value["interval"],
    line_item_external_id: value["lineItemExternalId"],
    product_external_id: value["productExternalId"],
    quantity: value["quantity"],
    term_month: value["termMonth"],
    total_discount: value["totalDiscount"],
  };
}
