/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateCrmDealLineItemAssociationRequestBody
 */
export interface CreateCrmDealLineItemAssociationRequestBody {
  /**
   *
   * @type {string}
   * @memberof CreateCrmDealLineItemAssociationRequestBody
   */
  dealExternalId: string;
  /**
   *
   * @type {string}
   * @memberof CreateCrmDealLineItemAssociationRequestBody
   */
  lineItemExternalId: string;
}

/**
 * Check if a given object implements the CreateCrmDealLineItemAssociationRequestBody interface.
 */
export function instanceOfCreateCrmDealLineItemAssociationRequestBody(
  value: object,
): value is CreateCrmDealLineItemAssociationRequestBody {
  if (!("dealExternalId" in value) || value["dealExternalId"] === undefined)
    return false;
  if (
    !("lineItemExternalId" in value) ||
    value["lineItemExternalId"] === undefined
  )
    return false;
  return true;
}

export function CreateCrmDealLineItemAssociationRequestBodyFromJSON(
  json: any,
): CreateCrmDealLineItemAssociationRequestBody {
  return CreateCrmDealLineItemAssociationRequestBodyFromJSONTyped(json, false);
}

export function CreateCrmDealLineItemAssociationRequestBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateCrmDealLineItemAssociationRequestBody {
  if (json == null) {
    return json;
  }
  return {
    dealExternalId: json["deal_external_id"],
    lineItemExternalId: json["line_item_external_id"],
  };
}

export function CreateCrmDealLineItemAssociationRequestBodyToJSON(
  json: any,
): CreateCrmDealLineItemAssociationRequestBody {
  return CreateCrmDealLineItemAssociationRequestBodyToJSONTyped(json, false);
}

export function CreateCrmDealLineItemAssociationRequestBodyToJSONTyped(
  value?: CreateCrmDealLineItemAssociationRequestBody | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    deal_external_id: value["dealExternalId"],
    line_item_external_id: value["lineItemExternalId"],
  };
}
