/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * The created resource
 * @export
 * @interface CrmDealResponseData
 */
export interface CrmDealResponseData {
  /**
   *
   * @type {string}
   * @memberof CrmDealResponseData
   */
  accountId: string;
  /**
   *
   * @type {string}
   * @memberof CrmDealResponseData
   */
  arr: string;
  /**
   *
   * @type {string}
   * @memberof CrmDealResponseData
   */
  companyExternalId?: string | null;
  /**
   *
   * @type {Date}
   * @memberof CrmDealResponseData
   */
  createdAt: Date;
  /**
   *
   * @type {string}
   * @memberof CrmDealResponseData
   */
  dealExternalId: string;
  /**
   *
   * @type {string}
   * @memberof CrmDealResponseData
   */
  dealId: string;
  /**
   *
   * @type {string}
   * @memberof CrmDealResponseData
   */
  environmentId: string;
  /**
   *
   * @type {string}
   * @memberof CrmDealResponseData
   */
  mrr: string;
  /**
   *
   * @type {string}
   * @memberof CrmDealResponseData
   */
  name?: string | null;
  /**
   *
   * @type {string}
   * @memberof CrmDealResponseData
   */
  productExternalId?: string | null;
  /**
   *
   * @type {Date}
   * @memberof CrmDealResponseData
   */
  updatedAt: Date;
}

/**
 * Check if a given object implements the CrmDealResponseData interface.
 */
export function instanceOfCrmDealResponseData(
  value: object,
): value is CrmDealResponseData {
  if (!("accountId" in value) || value["accountId"] === undefined) return false;
  if (!("arr" in value) || value["arr"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("dealExternalId" in value) || value["dealExternalId"] === undefined)
    return false;
  if (!("dealId" in value) || value["dealId"] === undefined) return false;
  if (!("environmentId" in value) || value["environmentId"] === undefined)
    return false;
  if (!("mrr" in value) || value["mrr"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  return true;
}

export function CrmDealResponseDataFromJSON(json: any): CrmDealResponseData {
  return CrmDealResponseDataFromJSONTyped(json, false);
}

export function CrmDealResponseDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CrmDealResponseData {
  if (json == null) {
    return json;
  }
  return {
    accountId: json["account_id"],
    arr: json["arr"],
    companyExternalId:
      json["company_external_id"] == null
        ? undefined
        : json["company_external_id"],
    createdAt: new Date(json["created_at"]),
    dealExternalId: json["deal_external_id"],
    dealId: json["deal_id"],
    environmentId: json["environment_id"],
    mrr: json["mrr"],
    name: json["name"] == null ? undefined : json["name"],
    productExternalId:
      json["product_external_id"] == null
        ? undefined
        : json["product_external_id"],
    updatedAt: new Date(json["updated_at"]),
  };
}

export function CrmDealResponseDataToJSON(json: any): CrmDealResponseData {
  return CrmDealResponseDataToJSONTyped(json, false);
}

export function CrmDealResponseDataToJSONTyped(
  value?: CrmDealResponseData | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    account_id: value["accountId"],
    arr: value["arr"],
    company_external_id: value["companyExternalId"],
    created_at: value["createdAt"].toISOString(),
    deal_external_id: value["dealExternalId"],
    deal_id: value["dealId"],
    environment_id: value["environmentId"],
    mrr: value["mrr"],
    name: value["name"],
    product_external_id: value["productExternalId"],
    updated_at: value["updatedAt"].toISOString(),
  };
}
