/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { DeleteResponse } from "./DeleteResponse";
import {
  DeleteResponseFromJSON,
  DeleteResponseFromJSONTyped,
  DeleteResponseToJSON,
  DeleteResponseToJSONTyped,
} from "./DeleteResponse";

/**
 *
 * @export
 * @interface DeleteWebhookResponse
 */
export interface DeleteWebhookResponse {
  /**
   *
   * @type {DeleteResponse}
   * @memberof DeleteWebhookResponse
   */
  data: DeleteResponse;
  /**
   * Input parameters
   * @type {object}
   * @memberof DeleteWebhookResponse
   */
  params: object;
}

/**
 * Check if a given object implements the DeleteWebhookResponse interface.
 */
export function instanceOfDeleteWebhookResponse(
  value: object,
): value is DeleteWebhookResponse {
  if (!("data" in value) || value["data"] === undefined) return false;
  if (!("params" in value) || value["params"] === undefined) return false;
  return true;
}

export function DeleteWebhookResponseFromJSON(
  json: any,
): DeleteWebhookResponse {
  return DeleteWebhookResponseFromJSONTyped(json, false);
}

export function DeleteWebhookResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DeleteWebhookResponse {
  if (json == null) {
    return json;
  }
  return {
    data: DeleteResponseFromJSON(json["data"]),
    params: json["params"],
  };
}

export function DeleteWebhookResponseToJSON(json: any): DeleteWebhookResponse {
  return DeleteWebhookResponseToJSONTyped(json, false);
}

export function DeleteWebhookResponseToJSONTyped(
  value?: DeleteWebhookResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data: DeleteResponseToJSON(value["data"]),
    params: value["params"],
  };
}
