/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Input parameters
 * @export
 * @interface GetActiveDealsParams
 */
export interface GetActiveDealsParams {
  /**
   *
   * @type {string}
   * @memberof GetActiveDealsParams
   */
  companyId?: string;
  /**
   *
   * @type {string}
   * @memberof GetActiveDealsParams
   */
  dealStage?: string;
  /**
   * Page limit (default 100)
   * @type {number}
   * @memberof GetActiveDealsParams
   */
  limit?: number;
  /**
   * Page offset (default 0)
   * @type {number}
   * @memberof GetActiveDealsParams
   */
  offset?: number;
}

/**
 * Check if a given object implements the GetActiveDealsParams interface.
 */
export function instanceOfGetActiveDealsParams(
  value: object,
): value is GetActiveDealsParams {
  return true;
}

export function GetActiveDealsParamsFromJSON(json: any): GetActiveDealsParams {
  return GetActiveDealsParamsFromJSONTyped(json, false);
}

export function GetActiveDealsParamsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetActiveDealsParams {
  if (json == null) {
    return json;
  }
  return {
    companyId: json["company_id"] == null ? undefined : json["company_id"],
    dealStage: json["deal_stage"] == null ? undefined : json["deal_stage"],
    limit: json["limit"] == null ? undefined : json["limit"],
    offset: json["offset"] == null ? undefined : json["offset"],
  };
}

export function GetActiveDealsParamsToJSON(json: any): GetActiveDealsParams {
  return GetActiveDealsParamsToJSONTyped(json, false);
}

export function GetActiveDealsParamsToJSONTyped(
  value?: GetActiveDealsParams | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    company_id: value["companyId"],
    deal_stage: value["dealStage"],
    limit: value["limit"],
    offset: value["offset"],
  };
}
