/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Input parameters
 * @export
 * @interface GetActiveCompanySubscriptionParams
 */
export interface GetActiveCompanySubscriptionParams {
  /**
   *
   * @type {string}
   * @memberof GetActiveCompanySubscriptionParams
   */
  companyId?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof GetActiveCompanySubscriptionParams
   */
  companyIds?: Array<string>;
  /**
   * Page limit (default 100)
   * @type {number}
   * @memberof GetActiveCompanySubscriptionParams
   */
  limit?: number;
  /**
   * Page offset (default 0)
   * @type {number}
   * @memberof GetActiveCompanySubscriptionParams
   */
  offset?: number;
}

/**
 * Check if a given object implements the GetActiveCompanySubscriptionParams interface.
 */
export function instanceOfGetActiveCompanySubscriptionParams(
  value: object,
): value is GetActiveCompanySubscriptionParams {
  return true;
}

export function GetActiveCompanySubscriptionParamsFromJSON(
  json: any,
): GetActiveCompanySubscriptionParams {
  return GetActiveCompanySubscriptionParamsFromJSONTyped(json, false);
}

export function GetActiveCompanySubscriptionParamsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetActiveCompanySubscriptionParams {
  if (json == null) {
    return json;
  }
  return {
    companyId: json["company_id"] == null ? undefined : json["company_id"],
    companyIds: json["company_ids"] == null ? undefined : json["company_ids"],
    limit: json["limit"] == null ? undefined : json["limit"],
    offset: json["offset"] == null ? undefined : json["offset"],
  };
}

export function GetActiveCompanySubscriptionParamsToJSON(
  json: any,
): GetActiveCompanySubscriptionParams {
  return GetActiveCompanySubscriptionParamsToJSONTyped(json, false);
}

export function GetActiveCompanySubscriptionParamsToJSONTyped(
  value?: GetActiveCompanySubscriptionParams | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    company_id: value["companyId"],
    company_ids: value["companyIds"],
    limit: value["limit"],
    offset: value["offset"],
  };
}
