/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { WebhookResponseData } from "./WebhookResponseData";
import {
  WebhookResponseDataFromJSON,
  WebhookResponseDataFromJSONTyped,
  WebhookResponseDataToJSON,
  WebhookResponseDataToJSONTyped,
} from "./WebhookResponseData";

/**
 *
 * @export
 * @interface GetWebhookResponse
 */
export interface GetWebhookResponse {
  /**
   *
   * @type {WebhookResponseData}
   * @memberof GetWebhookResponse
   */
  data: WebhookResponseData;
  /**
   * Input parameters
   * @type {object}
   * @memberof GetWebhookResponse
   */
  params: object;
}

/**
 * Check if a given object implements the GetWebhookResponse interface.
 */
export function instanceOfGetWebhookResponse(
  value: object,
): value is GetWebhookResponse {
  if (!("data" in value) || value["data"] === undefined) return false;
  if (!("params" in value) || value["params"] === undefined) return false;
  return true;
}

export function GetWebhookResponseFromJSON(json: any): GetWebhookResponse {
  return GetWebhookResponseFromJSONTyped(json, false);
}

export function GetWebhookResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetWebhookResponse {
  if (json == null) {
    return json;
  }
  return {
    data: WebhookResponseDataFromJSON(json["data"]),
    params: json["params"],
  };
}

export function GetWebhookResponseToJSON(json: any): GetWebhookResponse {
  return GetWebhookResponseToJSONTyped(json, false);
}

export function GetWebhookResponseToJSONTyped(
  value?: GetWebhookResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data: WebhookResponseDataToJSON(value["data"]),
    params: value["params"],
  };
}
