/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * The created resource
 * @export
 * @interface IssueTemporaryAccessTokenResponseData
 */
export interface IssueTemporaryAccessTokenResponseData {
  /**
   *
   * @type {string}
   * @memberof IssueTemporaryAccessTokenResponseData
   */
  apiKeyId: string;
  /**
   *
   * @type {Date}
   * @memberof IssueTemporaryAccessTokenResponseData
   */
  createdAt: Date;
  /**
   *
   * @type {string}
   * @memberof IssueTemporaryAccessTokenResponseData
   */
  environmentId: string;
  /**
   *
   * @type {Date}
   * @memberof IssueTemporaryAccessTokenResponseData
   */
  expiredAt: Date;
  /**
   *
   * @type {string}
   * @memberof IssueTemporaryAccessTokenResponseData
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof IssueTemporaryAccessTokenResponseData
   */
  resourceType: string;
  /**
   *
   * @type {string}
   * @memberof IssueTemporaryAccessTokenResponseData
   */
  token: string;
  /**
   *
   * @type {Date}
   * @memberof IssueTemporaryAccessTokenResponseData
   */
  updatedAt: Date;
}

/**
 * Check if a given object implements the IssueTemporaryAccessTokenResponseData interface.
 */
export function instanceOfIssueTemporaryAccessTokenResponseData(
  value: object,
): value is IssueTemporaryAccessTokenResponseData {
  if (!("apiKeyId" in value) || value["apiKeyId"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("environmentId" in value) || value["environmentId"] === undefined)
    return false;
  if (!("expiredAt" in value) || value["expiredAt"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("resourceType" in value) || value["resourceType"] === undefined)
    return false;
  if (!("token" in value) || value["token"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  return true;
}

export function IssueTemporaryAccessTokenResponseDataFromJSON(
  json: any,
): IssueTemporaryAccessTokenResponseData {
  return IssueTemporaryAccessTokenResponseDataFromJSONTyped(json, false);
}

export function IssueTemporaryAccessTokenResponseDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): IssueTemporaryAccessTokenResponseData {
  if (json == null) {
    return json;
  }
  return {
    apiKeyId: json["api_key_id"],
    createdAt: new Date(json["created_at"]),
    environmentId: json["environment_id"],
    expiredAt: new Date(json["expired_at"]),
    id: json["id"],
    resourceType: json["resource_type"],
    token: json["token"],
    updatedAt: new Date(json["updated_at"]),
  };
}

export function IssueTemporaryAccessTokenResponseDataToJSON(
  json: any,
): IssueTemporaryAccessTokenResponseData {
  return IssueTemporaryAccessTokenResponseDataToJSONTyped(json, false);
}

export function IssueTemporaryAccessTokenResponseDataToJSONTyped(
  value?: IssueTemporaryAccessTokenResponseData | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    api_key_id: value["apiKeyId"],
    created_at: value["createdAt"].toISOString(),
    environment_id: value["environmentId"],
    expired_at: value["expiredAt"].toISOString(),
    id: value["id"],
    resource_type: value["resourceType"],
    token: value["token"],
    updated_at: value["updatedAt"].toISOString(),
  };
}
