/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface KeysRequestBody
 */
export interface KeysRequestBody {
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof KeysRequestBody
   */
  keys: { [key: string]: string };
}

/**
 * Check if a given object implements the KeysRequestBody interface.
 */
export function instanceOfKeysRequestBody(
  value: object,
): value is KeysRequestBody {
  if (!("keys" in value) || value["keys"] === undefined) return false;
  return true;
}

export function KeysRequestBodyFromJSON(json: any): KeysRequestBody {
  return KeysRequestBodyFromJSONTyped(json, false);
}

export function KeysRequestBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): KeysRequestBody {
  if (json == null) {
    return json;
  }
  return {
    keys: json["keys"],
  };
}

export function KeysRequestBodyToJSON(json: any): KeysRequestBody {
  return KeysRequestBodyToJSONTyped(json, false);
}

export function KeysRequestBodyToJSONTyped(
  value?: KeysRequestBody | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    keys: value["keys"],
  };
}
