/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Input parameters
 * @export
 * @interface ListEntityTraitDefinitionsParams
 */
export interface ListEntityTraitDefinitionsParams {
  /**
   *
   * @type {string}
   * @memberof ListEntityTraitDefinitionsParams
   */
  entityType?: ListEntityTraitDefinitionsParamsEntityTypeEnum;
  /**
   *
   * @type {Array<string>}
   * @memberof ListEntityTraitDefinitionsParams
   */
  ids?: Array<string>;
  /**
   * Page limit (default 100)
   * @type {number}
   * @memberof ListEntityTraitDefinitionsParams
   */
  limit?: number;
  /**
   * Page offset (default 0)
   * @type {number}
   * @memberof ListEntityTraitDefinitionsParams
   */
  offset?: number;
  /**
   *
   * @type {string}
   * @memberof ListEntityTraitDefinitionsParams
   */
  q?: string;
  /**
   *
   * @type {string}
   * @memberof ListEntityTraitDefinitionsParams
   */
  traitType?: ListEntityTraitDefinitionsParamsTraitTypeEnum;
}

/**
 * @export
 */
export const ListEntityTraitDefinitionsParamsEntityTypeEnum = {
  Company: "company",
  User: "user",
} as const;
export type ListEntityTraitDefinitionsParamsEntityTypeEnum =
  (typeof ListEntityTraitDefinitionsParamsEntityTypeEnum)[keyof typeof ListEntityTraitDefinitionsParamsEntityTypeEnum];

/**
 * @export
 */
export const ListEntityTraitDefinitionsParamsTraitTypeEnum = {
  Boolean: "boolean",
  Currency: "currency",
  Date: "date",
  Number: "number",
  String: "string",
  Url: "url",
} as const;
export type ListEntityTraitDefinitionsParamsTraitTypeEnum =
  (typeof ListEntityTraitDefinitionsParamsTraitTypeEnum)[keyof typeof ListEntityTraitDefinitionsParamsTraitTypeEnum];

/**
 * Check if a given object implements the ListEntityTraitDefinitionsParams interface.
 */
export function instanceOfListEntityTraitDefinitionsParams(
  value: object,
): value is ListEntityTraitDefinitionsParams {
  return true;
}

export function ListEntityTraitDefinitionsParamsFromJSON(
  json: any,
): ListEntityTraitDefinitionsParams {
  return ListEntityTraitDefinitionsParamsFromJSONTyped(json, false);
}

export function ListEntityTraitDefinitionsParamsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListEntityTraitDefinitionsParams {
  if (json == null) {
    return json;
  }
  return {
    entityType: json["entity_type"] == null ? undefined : json["entity_type"],
    ids: json["ids"] == null ? undefined : json["ids"],
    limit: json["limit"] == null ? undefined : json["limit"],
    offset: json["offset"] == null ? undefined : json["offset"],
    q: json["q"] == null ? undefined : json["q"],
    traitType: json["trait_type"] == null ? undefined : json["trait_type"],
  };
}

export function ListEntityTraitDefinitionsParamsToJSON(
  json: any,
): ListEntityTraitDefinitionsParams {
  return ListEntityTraitDefinitionsParamsToJSONTyped(json, false);
}

export function ListEntityTraitDefinitionsParamsToJSONTyped(
  value?: ListEntityTraitDefinitionsParams | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    entity_type: value["entityType"],
    ids: value["ids"],
    limit: value["limit"],
    offset: value["offset"],
    q: value["q"],
    trait_type: value["traitType"],
  };
}
