/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { UserDetailResponseData } from "./UserDetailResponseData";
import {
  UserDetailResponseDataFromJSON,
  UserDetailResponseDataFromJSONTyped,
  UserDetailResponseDataToJSON,
  UserDetailResponseDataToJSONTyped,
} from "./UserDetailResponseData";

/**
 *
 * @export
 * @interface ListAudienceUsersResponse
 */
export interface ListAudienceUsersResponse {
  /**
   * The returned resources
   * @type {Array<UserDetailResponseData>}
   * @memberof ListAudienceUsersResponse
   */
  data: Array<UserDetailResponseData>;
  /**
   * Input parameters
   * @type {object}
   * @memberof ListAudienceUsersResponse
   */
  params: object;
}

/**
 * Check if a given object implements the ListAudienceUsersResponse interface.
 */
export function instanceOfListAudienceUsersResponse(
  value: object,
): value is ListAudienceUsersResponse {
  if (!("data" in value) || value["data"] === undefined) return false;
  if (!("params" in value) || value["params"] === undefined) return false;
  return true;
}

export function ListAudienceUsersResponseFromJSON(
  json: any,
): ListAudienceUsersResponse {
  return ListAudienceUsersResponseFromJSONTyped(json, false);
}

export function ListAudienceUsersResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListAudienceUsersResponse {
  if (json == null) {
    return json;
  }
  return {
    data: (json["data"] as Array<any>).map(UserDetailResponseDataFromJSON),
    params: json["params"],
  };
}

export function ListAudienceUsersResponseToJSON(
  json: any,
): ListAudienceUsersResponse {
  return ListAudienceUsersResponseToJSONTyped(json, false);
}

export function ListAudienceUsersResponseToJSONTyped(
  value?: ListAudienceUsersResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data: (value["data"] as Array<any>).map(UserDetailResponseDataToJSON),
    params: value["params"],
  };
}
