/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ListBillingProductsParams } from "./ListBillingProductsParams";
import {
  ListBillingProductsParamsFromJSON,
  ListBillingProductsParamsFromJSONTyped,
  ListBillingProductsParamsToJSON,
  ListBillingProductsParamsToJSONTyped,
} from "./ListBillingProductsParams";
import type { BillingProductDetailResponseData } from "./BillingProductDetailResponseData";
import {
  BillingProductDetailResponseDataFromJSON,
  BillingProductDetailResponseDataFromJSONTyped,
  BillingProductDetailResponseDataToJSON,
  BillingProductDetailResponseDataToJSONTyped,
} from "./BillingProductDetailResponseData";

/**
 *
 * @export
 * @interface ListBillingProductsResponse
 */
export interface ListBillingProductsResponse {
  /**
   * The returned resources
   * @type {Array<BillingProductDetailResponseData>}
   * @memberof ListBillingProductsResponse
   */
  data: Array<BillingProductDetailResponseData>;
  /**
   *
   * @type {ListBillingProductsParams}
   * @memberof ListBillingProductsResponse
   */
  params: ListBillingProductsParams;
}

/**
 * Check if a given object implements the ListBillingProductsResponse interface.
 */
export function instanceOfListBillingProductsResponse(
  value: object,
): value is ListBillingProductsResponse {
  if (!("data" in value) || value["data"] === undefined) return false;
  if (!("params" in value) || value["params"] === undefined) return false;
  return true;
}

export function ListBillingProductsResponseFromJSON(
  json: any,
): ListBillingProductsResponse {
  return ListBillingProductsResponseFromJSONTyped(json, false);
}

export function ListBillingProductsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListBillingProductsResponse {
  if (json == null) {
    return json;
  }
  return {
    data: (json["data"] as Array<any>).map(
      BillingProductDetailResponseDataFromJSON,
    ),
    params: ListBillingProductsParamsFromJSON(json["params"]),
  };
}

export function ListBillingProductsResponseToJSON(
  json: any,
): ListBillingProductsResponse {
  return ListBillingProductsResponseToJSONTyped(json, false);
}

export function ListBillingProductsResponseToJSONTyped(
  value?: ListBillingProductsResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data: (value["data"] as Array<any>).map(
      BillingProductDetailResponseDataToJSON,
    ),
    params: ListBillingProductsParamsToJSON(value["params"]),
  };
}
