/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { PlanEntitlementResponseData } from "./PlanEntitlementResponseData";
import {
  PlanEntitlementResponseDataFromJSON,
  PlanEntitlementResponseDataFromJSONTyped,
  PlanEntitlementResponseDataToJSON,
  PlanEntitlementResponseDataToJSONTyped,
} from "./PlanEntitlementResponseData";
import type { ListPlanEntitlementsParams } from "./ListPlanEntitlementsParams";
import {
  ListPlanEntitlementsParamsFromJSON,
  ListPlanEntitlementsParamsFromJSONTyped,
  ListPlanEntitlementsParamsToJSON,
  ListPlanEntitlementsParamsToJSONTyped,
} from "./ListPlanEntitlementsParams";

/**
 *
 * @export
 * @interface ListPlanEntitlementsResponse
 */
export interface ListPlanEntitlementsResponse {
  /**
   * The returned resources
   * @type {Array<PlanEntitlementResponseData>}
   * @memberof ListPlanEntitlementsResponse
   */
  data: Array<PlanEntitlementResponseData>;
  /**
   *
   * @type {ListPlanEntitlementsParams}
   * @memberof ListPlanEntitlementsResponse
   */
  params: ListPlanEntitlementsParams;
}

/**
 * Check if a given object implements the ListPlanEntitlementsResponse interface.
 */
export function instanceOfListPlanEntitlementsResponse(
  value: object,
): value is ListPlanEntitlementsResponse {
  if (!("data" in value) || value["data"] === undefined) return false;
  if (!("params" in value) || value["params"] === undefined) return false;
  return true;
}

export function ListPlanEntitlementsResponseFromJSON(
  json: any,
): ListPlanEntitlementsResponse {
  return ListPlanEntitlementsResponseFromJSONTyped(json, false);
}

export function ListPlanEntitlementsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListPlanEntitlementsResponse {
  if (json == null) {
    return json;
  }
  return {
    data: (json["data"] as Array<any>).map(PlanEntitlementResponseDataFromJSON),
    params: ListPlanEntitlementsParamsFromJSON(json["params"]),
  };
}

export function ListPlanEntitlementsResponseToJSON(
  json: any,
): ListPlanEntitlementsResponse {
  return ListPlanEntitlementsResponseToJSONTyped(json, false);
}

export function ListPlanEntitlementsResponseToJSONTyped(
  value?: ListPlanEntitlementsResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data: (value["data"] as Array<any>).map(PlanEntitlementResponseDataToJSON),
    params: ListPlanEntitlementsParamsToJSON(value["params"]),
  };
}
