/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CompanyMembershipDetailResponseData } from "./CompanyMembershipDetailResponseData";
import {
  CompanyMembershipDetailResponseDataFromJSON,
  CompanyMembershipDetailResponseDataFromJSONTyped,
  CompanyMembershipDetailResponseDataToJSON,
  CompanyMembershipDetailResponseDataToJSONTyped,
} from "./CompanyMembershipDetailResponseData";
import type { ListCompanyMembershipsParams } from "./ListCompanyMembershipsParams";
import {
  ListCompanyMembershipsParamsFromJSON,
  ListCompanyMembershipsParamsFromJSONTyped,
  ListCompanyMembershipsParamsToJSON,
  ListCompanyMembershipsParamsToJSONTyped,
} from "./ListCompanyMembershipsParams";

/**
 *
 * @export
 * @interface ListCompanyMembershipsResponse
 */
export interface ListCompanyMembershipsResponse {
  /**
   * The returned resources
   * @type {Array<CompanyMembershipDetailResponseData>}
   * @memberof ListCompanyMembershipsResponse
   */
  data: Array<CompanyMembershipDetailResponseData>;
  /**
   *
   * @type {ListCompanyMembershipsParams}
   * @memberof ListCompanyMembershipsResponse
   */
  params: ListCompanyMembershipsParams;
}

/**
 * Check if a given object implements the ListCompanyMembershipsResponse interface.
 */
export function instanceOfListCompanyMembershipsResponse(
  value: object,
): value is ListCompanyMembershipsResponse {
  if (!("data" in value) || value["data"] === undefined) return false;
  if (!("params" in value) || value["params"] === undefined) return false;
  return true;
}

export function ListCompanyMembershipsResponseFromJSON(
  json: any,
): ListCompanyMembershipsResponse {
  return ListCompanyMembershipsResponseFromJSONTyped(json, false);
}

export function ListCompanyMembershipsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ListCompanyMembershipsResponse {
  if (json == null) {
    return json;
  }
  return {
    data: (json["data"] as Array<any>).map(
      CompanyMembershipDetailResponseDataFromJSON,
    ),
    params: ListCompanyMembershipsParamsFromJSON(json["params"]),
  };
}

export function ListCompanyMembershipsResponseToJSON(
  json: any,
): ListCompanyMembershipsResponse {
  return ListCompanyMembershipsResponseToJSONTyped(json, false);
}

export function ListCompanyMembershipsResponseToJSONTyped(
  value?: ListCompanyMembershipsResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data: (value["data"] as Array<any>).map(
      CompanyMembershipDetailResponseDataToJSON,
    ),
    params: ListCompanyMembershipsParamsToJSON(value["params"]),
  };
}
