/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Input parameters
 * @export
 * @interface LookupUserParams
 */
export interface LookupUserParams {
  /**
   *
   * @type {object}
   * @memberof LookupUserParams
   */
  keys?: object;
}

/**
 * Check if a given object implements the LookupUserParams interface.
 */
export function instanceOfLookupUserParams(
  value: object,
): value is LookupUserParams {
  return true;
}

export function LookupUserParamsFromJSON(json: any): LookupUserParams {
  return LookupUserParamsFromJSONTyped(json, false);
}

export function LookupUserParamsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LookupUserParams {
  if (json == null) {
    return json;
  }
  return {
    keys: json["keys"] == null ? undefined : json["keys"],
  };
}

export function LookupUserParamsToJSON(json: any): LookupUserParams {
  return LookupUserParamsToJSONTyped(json, false);
}

export function LookupUserParamsToJSONTyped(
  value?: LookupUserParams | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    keys: value["keys"],
  };
}
