/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface MeterRequestBody
 */
export interface MeterRequestBody {
  /**
   *
   * @type {string}
   * @memberof MeterRequestBody
   */
  displayName: string;
  /**
   *
   * @type {string}
   * @memberof MeterRequestBody
   */
  eventName: string;
  /**
   *
   * @type {string}
   * @memberof MeterRequestBody
   */
  eventPayloadKey: string;
}

/**
 * Check if a given object implements the MeterRequestBody interface.
 */
export function instanceOfMeterRequestBody(
  value: object,
): value is MeterRequestBody {
  if (!("displayName" in value) || value["displayName"] === undefined)
    return false;
  if (!("eventName" in value) || value["eventName"] === undefined) return false;
  if (!("eventPayloadKey" in value) || value["eventPayloadKey"] === undefined)
    return false;
  return true;
}

export function MeterRequestBodyFromJSON(json: any): MeterRequestBody {
  return MeterRequestBodyFromJSONTyped(json, false);
}

export function MeterRequestBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MeterRequestBody {
  if (json == null) {
    return json;
  }
  return {
    displayName: json["display_name"],
    eventName: json["event_name"],
    eventPayloadKey: json["event_payload_key"],
  };
}

export function MeterRequestBodyToJSON(json: any): MeterRequestBody {
  return MeterRequestBodyToJSONTyped(json, false);
}

export function MeterRequestBodyToJSONTyped(
  value?: MeterRequestBody | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    display_name: value["displayName"],
    event_name: value["eventName"],
    event_payload_key: value["eventPayloadKey"],
  };
}
