/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * The updated resource
 * @export
 * @interface PlanGroupResponseData
 */
export interface PlanGroupResponseData {
  /**
   *
   * @type {Array<string>}
   * @memberof PlanGroupResponseData
   */
  addOnIds: Array<string>;
  /**
   *
   * @type {string}
   * @memberof PlanGroupResponseData
   */
  defaultPlanId?: string | null;
  /**
   *
   * @type {string}
   * @memberof PlanGroupResponseData
   */
  id: string;
  /**
   *
   * @type {Array<string>}
   * @memberof PlanGroupResponseData
   */
  planIds: Array<string>;
  /**
   *
   * @type {number}
   * @memberof PlanGroupResponseData
   */
  trialDays?: number | null;
  /**
   *
   * @type {boolean}
   * @memberof PlanGroupResponseData
   */
  trialPaymentMethodRequired?: boolean | null;
}

/**
 * Check if a given object implements the PlanGroupResponseData interface.
 */
export function instanceOfPlanGroupResponseData(
  value: object,
): value is PlanGroupResponseData {
  if (!("addOnIds" in value) || value["addOnIds"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("planIds" in value) || value["planIds"] === undefined) return false;
  return true;
}

export function PlanGroupResponseDataFromJSON(
  json: any,
): PlanGroupResponseData {
  return PlanGroupResponseDataFromJSONTyped(json, false);
}

export function PlanGroupResponseDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PlanGroupResponseData {
  if (json == null) {
    return json;
  }
  return {
    addOnIds: json["add_on_ids"],
    defaultPlanId:
      json["default_plan_id"] == null ? undefined : json["default_plan_id"],
    id: json["id"],
    planIds: json["plan_ids"],
    trialDays: json["trial_days"] == null ? undefined : json["trial_days"],
    trialPaymentMethodRequired:
      json["trial_payment_method_required"] == null
        ? undefined
        : json["trial_payment_method_required"],
  };
}

export function PlanGroupResponseDataToJSON(json: any): PlanGroupResponseData {
  return PlanGroupResponseDataToJSONTyped(json, false);
}

export function PlanGroupResponseDataToJSONTyped(
  value?: PlanGroupResponseData | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    add_on_ids: value["addOnIds"],
    default_plan_id: value["defaultPlanId"],
    id: value["id"],
    plan_ids: value["planIds"],
    trial_days: value["trialDays"],
    trial_payment_method_required: value["trialPaymentMethodRequired"],
  };
}
