/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface StripeEmbedInfo
 */
export interface StripeEmbedInfo {
  /**
   *
   * @type {string}
   * @memberof StripeEmbedInfo
   */
  publishableKey: string;
  /**
   *
   * @type {string}
   * @memberof StripeEmbedInfo
   */
  setupIntentClientSecret?: string | null;
}

/**
 * Check if a given object implements the StripeEmbedInfo interface.
 */
export function instanceOfStripeEmbedInfo(
  value: object,
): value is StripeEmbedInfo {
  if (!("publishableKey" in value) || value["publishableKey"] === undefined)
    return false;
  return true;
}

export function StripeEmbedInfoFromJSON(json: any): StripeEmbedInfo {
  return StripeEmbedInfoFromJSONTyped(json, false);
}

export function StripeEmbedInfoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): StripeEmbedInfo {
  if (json == null) {
    return json;
  }
  return {
    publishableKey: json["publishable_key"],
    setupIntentClientSecret:
      json["setup_intent_client_secret"] == null
        ? undefined
        : json["setup_intent_client_secret"],
  };
}

export function StripeEmbedInfoToJSON(json: any): StripeEmbedInfo {
  return StripeEmbedInfoToJSONTyped(json, false);
}

export function StripeEmbedInfoToJSONTyped(
  value?: StripeEmbedInfo | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    publishable_key: value["publishableKey"],
    setup_intent_client_secret: value["setupIntentClientSecret"],
  };
}
