/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface TemporaryAccessTokenResponseData
 */
export interface TemporaryAccessTokenResponseData {
  /**
   *
   * @type {string}
   * @memberof TemporaryAccessTokenResponseData
   */
  apiKeyId: string;
  /**
   *
   * @type {Date}
   * @memberof TemporaryAccessTokenResponseData
   */
  createdAt: Date;
  /**
   *
   * @type {string}
   * @memberof TemporaryAccessTokenResponseData
   */
  environmentId: string;
  /**
   *
   * @type {Date}
   * @memberof TemporaryAccessTokenResponseData
   */
  expiredAt: Date;
  /**
   *
   * @type {string}
   * @memberof TemporaryAccessTokenResponseData
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof TemporaryAccessTokenResponseData
   */
  resourceType: string;
  /**
   *
   * @type {Date}
   * @memberof TemporaryAccessTokenResponseData
   */
  updatedAt: Date;
}

/**
 * Check if a given object implements the TemporaryAccessTokenResponseData interface.
 */
export function instanceOfTemporaryAccessTokenResponseData(
  value: object,
): value is TemporaryAccessTokenResponseData {
  if (!("apiKeyId" in value) || value["apiKeyId"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("environmentId" in value) || value["environmentId"] === undefined)
    return false;
  if (!("expiredAt" in value) || value["expiredAt"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("resourceType" in value) || value["resourceType"] === undefined)
    return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  return true;
}

export function TemporaryAccessTokenResponseDataFromJSON(
  json: any,
): TemporaryAccessTokenResponseData {
  return TemporaryAccessTokenResponseDataFromJSONTyped(json, false);
}

export function TemporaryAccessTokenResponseDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TemporaryAccessTokenResponseData {
  if (json == null) {
    return json;
  }
  return {
    apiKeyId: json["api_key_id"],
    createdAt: new Date(json["created_at"]),
    environmentId: json["environment_id"],
    expiredAt: new Date(json["expired_at"]),
    id: json["id"],
    resourceType: json["resource_type"],
    updatedAt: new Date(json["updated_at"]),
  };
}

export function TemporaryAccessTokenResponseDataToJSON(
  json: any,
): TemporaryAccessTokenResponseData {
  return TemporaryAccessTokenResponseDataToJSONTyped(json, false);
}

export function TemporaryAccessTokenResponseDataToJSONTyped(
  value?: TemporaryAccessTokenResponseData | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    api_key_id: value["apiKeyId"],
    created_at: value["createdAt"].toISOString(),
    environment_id: value["environmentId"],
    expired_at: value["expiredAt"].toISOString(),
    id: value["id"],
    resource_type: value["resourceType"],
    updated_at: value["updatedAt"].toISOString(),
  };
}
