/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { FlagDetailResponseData } from "./FlagDetailResponseData";
import {
  FlagDetailResponseDataFromJSON,
  FlagDetailResponseDataFromJSONTyped,
  FlagDetailResponseDataToJSON,
  FlagDetailResponseDataToJSONTyped,
} from "./FlagDetailResponseData";

/**
 *
 * @export
 * @interface UpdateFlagResponse
 */
export interface UpdateFlagResponse {
  /**
   *
   * @type {FlagDetailResponseData}
   * @memberof UpdateFlagResponse
   */
  data: FlagDetailResponseData;
  /**
   * Input parameters
   * @type {object}
   * @memberof UpdateFlagResponse
   */
  params: object;
}

/**
 * Check if a given object implements the UpdateFlagResponse interface.
 */
export function instanceOfUpdateFlagResponse(
  value: object,
): value is UpdateFlagResponse {
  if (!("data" in value) || value["data"] === undefined) return false;
  if (!("params" in value) || value["params"] === undefined) return false;
  return true;
}

export function UpdateFlagResponseFromJSON(json: any): UpdateFlagResponse {
  return UpdateFlagResponseFromJSONTyped(json, false);
}

export function UpdateFlagResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateFlagResponse {
  if (json == null) {
    return json;
  }
  return {
    data: FlagDetailResponseDataFromJSON(json["data"]),
    params: json["params"],
  };
}

export function UpdateFlagResponseToJSON(json: any): UpdateFlagResponse {
  return UpdateFlagResponseToJSONTyped(json, false);
}

export function UpdateFlagResponseToJSONTyped(
  value?: UpdateFlagResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data: FlagDetailResponseDataToJSON(value["data"]),
    params: value["params"],
  };
}
