/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CreateOrUpdateConditionRequestBody } from "./CreateOrUpdateConditionRequestBody";
import {
  CreateOrUpdateConditionRequestBodyFromJSON,
  CreateOrUpdateConditionRequestBodyFromJSONTyped,
  CreateOrUpdateConditionRequestBodyToJSON,
  CreateOrUpdateConditionRequestBodyToJSONTyped,
} from "./CreateOrUpdateConditionRequestBody";
import type { CreateOrUpdateConditionGroupRequestBody } from "./CreateOrUpdateConditionGroupRequestBody";
import {
  CreateOrUpdateConditionGroupRequestBodyFromJSON,
  CreateOrUpdateConditionGroupRequestBodyFromJSONTyped,
  CreateOrUpdateConditionGroupRequestBodyToJSON,
  CreateOrUpdateConditionGroupRequestBodyToJSONTyped,
} from "./CreateOrUpdateConditionGroupRequestBody";

/**
 *
 * @export
 * @interface UpdateAudienceRequestBody
 */
export interface UpdateAudienceRequestBody {
  /**
   *
   * @type {Array<CreateOrUpdateConditionGroupRequestBody>}
   * @memberof UpdateAudienceRequestBody
   */
  conditionGroups: Array<CreateOrUpdateConditionGroupRequestBody>;
  /**
   *
   * @type {Array<CreateOrUpdateConditionRequestBody>}
   * @memberof UpdateAudienceRequestBody
   */
  conditions: Array<CreateOrUpdateConditionRequestBody>;
}

/**
 * Check if a given object implements the UpdateAudienceRequestBody interface.
 */
export function instanceOfUpdateAudienceRequestBody(
  value: object,
): value is UpdateAudienceRequestBody {
  if (!("conditionGroups" in value) || value["conditionGroups"] === undefined)
    return false;
  if (!("conditions" in value) || value["conditions"] === undefined)
    return false;
  return true;
}

export function UpdateAudienceRequestBodyFromJSON(
  json: any,
): UpdateAudienceRequestBody {
  return UpdateAudienceRequestBodyFromJSONTyped(json, false);
}

export function UpdateAudienceRequestBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateAudienceRequestBody {
  if (json == null) {
    return json;
  }
  return {
    conditionGroups: (json["condition_groups"] as Array<any>).map(
      CreateOrUpdateConditionGroupRequestBodyFromJSON,
    ),
    conditions: (json["conditions"] as Array<any>).map(
      CreateOrUpdateConditionRequestBodyFromJSON,
    ),
  };
}

export function UpdateAudienceRequestBodyToJSON(
  json: any,
): UpdateAudienceRequestBody {
  return UpdateAudienceRequestBodyToJSONTyped(json, false);
}

export function UpdateAudienceRequestBodyToJSONTyped(
  value?: UpdateAudienceRequestBody | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    condition_groups: (value["conditionGroups"] as Array<any>).map(
      CreateOrUpdateConditionGroupRequestBodyToJSON,
    ),
    conditions: (value["conditions"] as Array<any>).map(
      CreateOrUpdateConditionRequestBodyToJSON,
    ),
  };
}
