/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CompanyOverrideResponseData } from "./CompanyOverrideResponseData";
import {
  CompanyOverrideResponseDataFromJSON,
  CompanyOverrideResponseDataFromJSONTyped,
  CompanyOverrideResponseDataToJSON,
  CompanyOverrideResponseDataToJSONTyped,
} from "./CompanyOverrideResponseData";

/**
 *
 * @export
 * @interface UpdateCompanyOverrideResponse
 */
export interface UpdateCompanyOverrideResponse {
  /**
   *
   * @type {CompanyOverrideResponseData}
   * @memberof UpdateCompanyOverrideResponse
   */
  data: CompanyOverrideResponseData;
  /**
   * Input parameters
   * @type {object}
   * @memberof UpdateCompanyOverrideResponse
   */
  params: object;
}

/**
 * Check if a given object implements the UpdateCompanyOverrideResponse interface.
 */
export function instanceOfUpdateCompanyOverrideResponse(
  value: object,
): value is UpdateCompanyOverrideResponse {
  if (!("data" in value) || value["data"] === undefined) return false;
  if (!("params" in value) || value["params"] === undefined) return false;
  return true;
}

export function UpdateCompanyOverrideResponseFromJSON(
  json: any,
): UpdateCompanyOverrideResponse {
  return UpdateCompanyOverrideResponseFromJSONTyped(json, false);
}

export function UpdateCompanyOverrideResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateCompanyOverrideResponse {
  if (json == null) {
    return json;
  }
  return {
    data: CompanyOverrideResponseDataFromJSON(json["data"]),
    params: json["params"],
  };
}

export function UpdateCompanyOverrideResponseToJSON(
  json: any,
): UpdateCompanyOverrideResponse {
  return UpdateCompanyOverrideResponseToJSONTyped(json, false);
}

export function UpdateCompanyOverrideResponseToJSONTyped(
  value?: UpdateCompanyOverrideResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data: CompanyOverrideResponseDataToJSON(value["data"]),
    params: value["params"],
  };
}
