/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { BillingMeterResponseData } from "./BillingMeterResponseData";
import {
  BillingMeterResponseDataFromJSON,
  BillingMeterResponseDataFromJSONTyped,
  BillingMeterResponseDataToJSON,
  BillingMeterResponseDataToJSONTyped,
} from "./BillingMeterResponseData";

/**
 *
 * @export
 * @interface UpsertBillingMeterResponse
 */
export interface UpsertBillingMeterResponse {
  /**
   *
   * @type {BillingMeterResponseData}
   * @memberof UpsertBillingMeterResponse
   */
  data: BillingMeterResponseData;
  /**
   * Input parameters
   * @type {object}
   * @memberof UpsertBillingMeterResponse
   */
  params: object;
}

/**
 * Check if a given object implements the UpsertBillingMeterResponse interface.
 */
export function instanceOfUpsertBillingMeterResponse(
  value: object,
): value is UpsertBillingMeterResponse {
  if (!("data" in value) || value["data"] === undefined) return false;
  if (!("params" in value) || value["params"] === undefined) return false;
  return true;
}

export function UpsertBillingMeterResponseFromJSON(
  json: any,
): UpsertBillingMeterResponse {
  return UpsertBillingMeterResponseFromJSONTyped(json, false);
}

export function UpsertBillingMeterResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpsertBillingMeterResponse {
  if (json == null) {
    return json;
  }
  return {
    data: BillingMeterResponseDataFromJSON(json["data"]),
    params: json["params"],
  };
}

export function UpsertBillingMeterResponseToJSON(
  json: any,
): UpsertBillingMeterResponse {
  return UpsertBillingMeterResponseToJSONTyped(json, false);
}

export function UpsertBillingMeterResponseToJSONTyped(
  value?: UpsertBillingMeterResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data: BillingMeterResponseDataToJSON(value["data"]),
    params: value["params"],
  };
}
