/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { PaymentMethodResponseData } from "./PaymentMethodResponseData";
import {
  PaymentMethodResponseDataFromJSON,
  PaymentMethodResponseDataFromJSONTyped,
  PaymentMethodResponseDataToJSON,
  PaymentMethodResponseDataToJSONTyped,
} from "./PaymentMethodResponseData";

/**
 *
 * @export
 * @interface UpsertPaymentMethodResponse
 */
export interface UpsertPaymentMethodResponse {
  /**
   *
   * @type {PaymentMethodResponseData}
   * @memberof UpsertPaymentMethodResponse
   */
  data: PaymentMethodResponseData;
  /**
   * Input parameters
   * @type {object}
   * @memberof UpsertPaymentMethodResponse
   */
  params: object;
}

/**
 * Check if a given object implements the UpsertPaymentMethodResponse interface.
 */
export function instanceOfUpsertPaymentMethodResponse(
  value: object,
): value is UpsertPaymentMethodResponse {
  if (!("data" in value) || value["data"] === undefined) return false;
  if (!("params" in value) || value["params"] === undefined) return false;
  return true;
}

export function UpsertPaymentMethodResponseFromJSON(
  json: any,
): UpsertPaymentMethodResponse {
  return UpsertPaymentMethodResponseFromJSONTyped(json, false);
}

export function UpsertPaymentMethodResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpsertPaymentMethodResponse {
  if (json == null) {
    return json;
  }
  return {
    data: PaymentMethodResponseDataFromJSON(json["data"]),
    params: json["params"],
  };
}

export function UpsertPaymentMethodResponseToJSON(
  json: any,
): UpsertPaymentMethodResponse {
  return UpsertPaymentMethodResponseToJSONTyped(json, false);
}

export function UpsertPaymentMethodResponseToJSONTyped(
  value?: UpsertPaymentMethodResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data: PaymentMethodResponseDataToJSON(value["data"]),
    params: value["params"],
  };
}
