/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CrmLineItemResponseData } from "./CrmLineItemResponseData";
import {
  CrmLineItemResponseDataFromJSON,
  CrmLineItemResponseDataFromJSONTyped,
  CrmLineItemResponseDataToJSON,
  CrmLineItemResponseDataToJSONTyped,
} from "./CrmLineItemResponseData";

/**
 *
 * @export
 * @interface UpsertDealLineItemAssociationResponse
 */
export interface UpsertDealLineItemAssociationResponse {
  /**
   *
   * @type {CrmLineItemResponseData}
   * @memberof UpsertDealLineItemAssociationResponse
   */
  data: CrmLineItemResponseData;
  /**
   * Input parameters
   * @type {object}
   * @memberof UpsertDealLineItemAssociationResponse
   */
  params: object;
}

/**
 * Check if a given object implements the UpsertDealLineItemAssociationResponse interface.
 */
export function instanceOfUpsertDealLineItemAssociationResponse(
  value: object,
): value is UpsertDealLineItemAssociationResponse {
  if (!("data" in value) || value["data"] === undefined) return false;
  if (!("params" in value) || value["params"] === undefined) return false;
  return true;
}

export function UpsertDealLineItemAssociationResponseFromJSON(
  json: any,
): UpsertDealLineItemAssociationResponse {
  return UpsertDealLineItemAssociationResponseFromJSONTyped(json, false);
}

export function UpsertDealLineItemAssociationResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpsertDealLineItemAssociationResponse {
  if (json == null) {
    return json;
  }
  return {
    data: CrmLineItemResponseDataFromJSON(json["data"]),
    params: json["params"],
  };
}

export function UpsertDealLineItemAssociationResponseToJSON(
  json: any,
): UpsertDealLineItemAssociationResponse {
  return UpsertDealLineItemAssociationResponseToJSONTyped(json, false);
}

export function UpsertDealLineItemAssociationResponseToJSONTyped(
  value?: UpsertDealLineItemAssociationResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data: CrmLineItemResponseDataToJSON(value["data"]),
    params: value["params"],
  };
}
