/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpsertBillingProductRequestBody
 */
export interface UpsertBillingProductRequestBody {
  /**
   *
   * @type {string}
   * @memberof UpsertBillingProductRequestBody
   */
  billingProductId?: string | null;
  /**
   *
   * @type {boolean}
   * @memberof UpsertBillingProductRequestBody
   */
  isFreePlan: boolean;
  /**
   *
   * @type {boolean}
   * @memberof UpsertBillingProductRequestBody
   */
  isTrialable: boolean;
  /**
   *
   * @type {string}
   * @memberof UpsertBillingProductRequestBody
   */
  monthlyPriceId?: string | null;
  /**
   *
   * @type {number}
   * @memberof UpsertBillingProductRequestBody
   */
  trialDays?: number | null;
  /**
   *
   * @type {string}
   * @memberof UpsertBillingProductRequestBody
   */
  yearlyPriceId?: string | null;
}

/**
 * Check if a given object implements the UpsertBillingProductRequestBody interface.
 */
export function instanceOfUpsertBillingProductRequestBody(
  value: object,
): value is UpsertBillingProductRequestBody {
  if (!("isFreePlan" in value) || value["isFreePlan"] === undefined)
    return false;
  if (!("isTrialable" in value) || value["isTrialable"] === undefined)
    return false;
  return true;
}

export function UpsertBillingProductRequestBodyFromJSON(
  json: any,
): UpsertBillingProductRequestBody {
  return UpsertBillingProductRequestBodyFromJSONTyped(json, false);
}

export function UpsertBillingProductRequestBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpsertBillingProductRequestBody {
  if (json == null) {
    return json;
  }
  return {
    billingProductId:
      json["billing_product_id"] == null
        ? undefined
        : json["billing_product_id"],
    isFreePlan: json["is_free_plan"],
    isTrialable: json["is_trialable"],
    monthlyPriceId:
      json["monthly_price_id"] == null ? undefined : json["monthly_price_id"],
    trialDays: json["trial_days"] == null ? undefined : json["trial_days"],
    yearlyPriceId:
      json["yearly_price_id"] == null ? undefined : json["yearly_price_id"],
  };
}

export function UpsertBillingProductRequestBodyToJSON(
  json: any,
): UpsertBillingProductRequestBody {
  return UpsertBillingProductRequestBodyToJSONTyped(json, false);
}

export function UpsertBillingProductRequestBodyToJSONTyped(
  value?: UpsertBillingProductRequestBody | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    billing_product_id: value["billingProductId"],
    is_free_plan: value["isFreePlan"],
    is_trialable: value["isTrialable"],
    monthly_price_id: value["monthlyPriceId"],
    trial_days: value["trialDays"],
    yearly_price_id: value["yearlyPriceId"],
  };
}
