/* tslint:disable */
/* eslint-disable */
/**
 * Schematic API
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CrmDealResponseData } from "./CrmDealResponseData";
import {
  CrmDealResponseDataFromJSON,
  CrmDealResponseDataFromJSONTyped,
  CrmDealResponseDataToJSON,
  CrmDealResponseDataToJSONTyped,
} from "./CrmDealResponseData";

/**
 *
 * @export
 * @interface UpsertCrmDealResponse
 */
export interface UpsertCrmDealResponse {
  /**
   *
   * @type {CrmDealResponseData}
   * @memberof UpsertCrmDealResponse
   */
  data: CrmDealResponseData;
  /**
   * Input parameters
   * @type {object}
   * @memberof UpsertCrmDealResponse
   */
  params: object;
}

/**
 * Check if a given object implements the UpsertCrmDealResponse interface.
 */
export function instanceOfUpsertCrmDealResponse(
  value: object,
): value is UpsertCrmDealResponse {
  if (!("data" in value) || value["data"] === undefined) return false;
  if (!("params" in value) || value["params"] === undefined) return false;
  return true;
}

export function UpsertCrmDealResponseFromJSON(
  json: any,
): UpsertCrmDealResponse {
  return UpsertCrmDealResponseFromJSONTyped(json, false);
}

export function UpsertCrmDealResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpsertCrmDealResponse {
  if (json == null) {
    return json;
  }
  return {
    data: CrmDealResponseDataFromJSON(json["data"]),
    params: json["params"],
  };
}

export function UpsertCrmDealResponseToJSON(json: any): UpsertCrmDealResponse {
  return UpsertCrmDealResponseToJSONTyped(json, false);
}

export function UpsertCrmDealResponseToJSONTyped(
  value?: UpsertCrmDealResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data: CrmDealResponseDataToJSON(value["data"]),
    params: value["params"],
  };
}
