name: Test
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build

  notify_slack: # Notify only on failure
    name: Notify Slack
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: drilonrecica/action-slack-notify@0.0.3
        if: ${{ needs.build.result != 'success' }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: Failed to build schematic-js
          SLACK_COLOR: "#FF0000"
          SLACK_ICON: https://schematic-public-assets.s3.amazonaws.com/logos/logo-transparent.png
