name: dependabot-metadata
description: "Dependabot Metadata and Linear Integration"

on:
  pull_request:

jobs:
  dependabot:
    name: Dependabot Metadata
    runs-on: runs-on=${{ github.run_id }}/runner=1cpu-linux-arm64
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
      issues: write
      security-events: write
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:

      - name: Checkout
        uses: actions/checkout@v5.0.0

      # This is not working from Public repos.
      # - name: Dependabot Metadata
      #   uses: SchematicHQ/actions/dependabot@main
      #   id: dependabot
      #   with:
      #     LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     GH_TOKEN: ${{ secrets.GH_TOKEN }}
