name: dependabot-metadata

on:
  pull_request:

jobs:
  dependabot:
    name: Dependabot Metadata
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions: write-all
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Dependabot Metadata
        uses: SchematicHQ/actions/dependabot@main
        id: dependabot
        with:
          LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
