name: Deploy schematic-dev-toolbar

permissions:
  id-token: write
  contents: read

on:
  push:
    tags:
      - "schematic-dev-toolbar@*"
      - "!schematic-dev-toolbar@*-rc*"
  workflow_dispatch:

jobs:
  lint_test:
    name: Lint and Test
    uses: ./.github/workflows/lint_test.yml
    with:
      package: schematic-dev-toolbar
      working_dir: toolbar

  publish:
    name: NPM Publish
    runs-on: runs-on=${{ github.run_id }}/runner=4cpu-linux-x64/extras=s3-cache
    permissions:
      packages: write
      contents: read
    needs: [lint_test]
    steps:
      - uses: runs-on/action@v2.0.3
      - uses: actions/checkout@v6
      - name: Set Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - name: Publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: ./scripts/publish-package.sh "${{ github.ref_name }}"

  notify_slack:
    name: Notify Slack
    runs-on: runs-on=${{ github.run_id }}/runner=1cpu-linux-arm64
    needs: [publish]
    steps:
      - uses: rtCamp/action-slack-notify@v2.3.3
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: Updated schematic-dev-toolbar
          SLACK_ICON: https://schematic-public-assets.s3.amazonaws.com/logos/logo-transparent.png
