name: Deploy schematic-angular

on:
  push:
    tags:
      - 'schematic-angular@*'
      - '!schematic-angular@*-rc*'
  workflow_dispatch:

jobs:
  lint_test:
    name: Lint and Test
    uses: ./.github/workflows/lint_test.yml
    with:
      package: schematic-angular
      working_dir: angular

  publish:
    name: NPM Publish
    needs: [lint_test]
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/npm_publish.yml
    with:
      tag: ${{ github.ref_name }}
