name: Deploy schematic-vue

on:
  push:
    tags:
      - 'schematic-vue@*'
  workflow_dispatch:

jobs:
  lint_test:
    name: Lint and Test
    uses: ./.github/workflows/lint_test.yml
    with:
      package: schematic-vue
      working_dir: vue

  publish:
    name: NPM Publish
    needs: [lint_test]
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/npm_publish.yml
    with:
      tag: ${{ github.ref_name }}
