name: Main

on:
  push:
    branches:
      - main

jobs:
  notify_slack:
    name: Notify Slack
    runs-on: ubuntu-latest
    steps:
      - uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: Updated schematic-js
          SLACK_ICON: https://schematic-public-assets.s3.amazonaws.com/logos/logo-transparent.png
