name: Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Browser Deploy
    runs-on: ubuntu-latest
    env:
      AWS_REGION: "us-east-1"
      CDN_DISTRIBUTION_ID: "EIY5G2ECS6996"
      S3_BUCKET: "schematic-cdn"
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build browser bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build:browser

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get package version
        id: package
        run: |
          echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Deploy browser build
        run: |
          aws s3 cp --acl=public-read dist/schematic.browser.js s3://$S3_BUCKET/js/schematic.js
          aws s3 cp --acl=public-read dist/schematic.browser.js s3://$S3_BUCKET/js/schematic.${{ steps.package.outputs.version }}.js
          aws configure set preview.cloudfront true
          aws cloudfront create-invalidation --distribution-id ${{ env.CDN_DISTRIBUTION_ID }} --paths "/js/schematic.js" "/js/schematic.${{ steps.package.outputs.version }}.js"

  publish:
    name: NPM Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@schematichq'
      - name: Yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Build CJS
        uses: borales/actions-yarn@v4
        with:
          cmd: build:cjs
      - name: Build ESM
        uses: borales/actions-yarn@v4
        with:
          cmd: build:esm
      - name: Build types
        uses: borales/actions-yarn@v4
        with:
          cmd: build:types
      - name: Set up .npmrc
        run: touch .npmrc && echo "//npm.pkg.github.com/:_authToken=$AUTH_TOKEN" > .npmrc
        env:
          AUTH_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.CH_PERSONAL_ACCESS_TOKEN }}

  notify_slack:
    name: Notify Slack
    runs-on: ubuntu-latest
    needs: [deploy, publish]
    steps:
      - uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: Updated schematic-js
          SLACK_ICON: https://schematic-public-assets.s3.amazonaws.com/logos/logo-transparent.png
