name: Main

on:
  push:
    branches:
      - main

jobs:
  notify_slack:
    name: Notify Slack
    runs-on: ubuntu-latest
    steps:
      - uses: drilonrecica/action-slack-notify@0.0.3
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: Updated schematic-js
