name: Pull request - schematic-js

on:
  pull_request:
    paths:
      - js/**
      - .github/workflows/**
      - scripts/**

jobs:
  build:
    name: Build
    runs-on: runs-on=${{ github.run_id }}/runner=4cpu-linux-x64/extras=s3-cache
    steps:
      - uses: runs-on/action@v2.3.0
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24.x
      - name: Enable corepack
        run: corepack enable pnpm
      - name: Install dependencies
        working-directory: ./js
        run: pnpm install --frozen-lockfile
      - name: Build
        working-directory: ./js
        run: pnpm run build

  lint:
    name: Lint
    runs-on: runs-on=${{ github.run_id }}/runner=4cpu-linux-x64/extras=s3-cache
    steps:
      - uses: runs-on/action@v2.3.0
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24.x
      - name: Enable corepack
        run: corepack enable pnpm
      - name: Install dependencies
        working-directory: ./js
        run: pnpm install --frozen-lockfile
      - name: Lint
        working-directory: ./js
        run: pnpm run lint

  test:
    name: Test (Node ${{ matrix.node-version }})
    runs-on: runs-on=${{ github.run_id }}/runner=4cpu-linux-x64/extras=s3-cache
    strategy:
      matrix:
        node-version: [24.18.0, 26.5.0]
    steps:
      - uses: runs-on/action@v2.3.0
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
      - name: Enable corepack
        run: corepack enable pnpm
      - name: Install dependencies
        working-directory: ./js
        run: pnpm install --frozen-lockfile
      - name: Test
        working-directory: ./js
        run: pnpm run test
      - name: Test (React Native)
        working-directory: ./js
        run: pnpm run test:reactnative
