name: Pull request - schematic-components

on:
  pull_request:
    paths:
      - components/**

jobs:
  build:
    name: Build
    runs-on: runs-on=${{ github.run_id }}/runner=4cpu-linux-x64/extras=s3-cache
    steps:
      - uses: runs-on/action@v2.0.3
      - uses: actions/checkout@v5.0.0
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Bun install
        working-directory: ./components
        run: bun install
      - name: Build
        working-directory: ./components
        run: bun runbuild

  lint:
    name: Lint
    runs-on: runs-on=${{ github.run_id }}/runner=4cpu-linux-x64/extras=s3-cache
    steps:
      - uses: runs-on/action@v2.0.3
      - uses: actions/checkout@v5.0.0
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Bun install
        working-directory: ./components
        run: bun install
      - name: Lint
        working-directory: ./components
        run: bun runlint

  test:
    name: Test
    runs-on: runs-on=${{ github.run_id }}/runner=4cpu-linux-x64/extras=s3-cache
    steps:
      - uses: runs-on/action@v2
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Yarn install
        working-directory: ./components
        run: bun runinstall
      - name: Test
        working-directory: ./components
        run: bun runtest

