name: Pull request - schematic-react

on:
  pull_request:
    paths:
      - react/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - uses: borales/actions-yarn@v4
        with:
          cmd: install
        working-directory: ./react
      - uses: borales/actions-yarn@v4
        with:
          cmd: build
        working-directory: ./react

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - uses: borales/actions-yarn@v4
        with:
          cmd: install
        working-directory: ./react
      - uses: borales/actions-yarn@v4
        with:
          cmd: lint
        working-directory: ./react
