name: Pull request - schematic-components

on:
  pull_request:
    paths:
      - components/**

jobs:
  build:
    name: Build
    runs-on: runs-on=${{ github.run_id }}/runner=4cpu-linux-x64/extras=s3-cache
    steps:
      - uses: runs-on/action@v2.0.3
      - uses: actions/checkout@v5.0.0
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - name: Yarn install
        working-directory: ./components
        run: yarn install
      - name: Build
        working-directory: ./components
        run: yarn build

  lint:
    name: Lint
    runs-on: runs-on=${{ github.run_id }}/runner=4cpu-linux-x64/extras=s3-cache
    steps:
      - uses: runs-on/action@v2.0.3
      - uses: actions/checkout@v5.0.0
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - name: Yarn install
        working-directory: ./components
        run: yarn install
      - name: Lint
        working-directory: ./components
        run: yarn lint

  test:
    name: Test (Node ${{ matrix.node-version }})
    runs-on: runs-on=${{ github.run_id }}/runner=4cpu-linux-x64/extras=s3-cache
    strategy:
      matrix:
        node-version: [24.11.0, 25.1.0]
    steps:
      - uses: runs-on/action@v2
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn install
        working-directory: ./components
        run: yarn install
      - name: Test
        working-directory: ./components
        env:
          # Node v25 requires --no-webstorage flag to disable native Web Storage API
          # which conflicts with jsdom's localStorage implementation
          NODE_OPTIONS: ${{ matrix.node-version == '25.1.0' && '--no-webstorage' || '' }}
        run: yarn test

