name: Pull request - schematic-react

on:
  pull_request:
    paths:
      - react/**

jobs:
  build:
    name: Build
    runs-on: runs-on=${{ github.run_id }}/runner=4cpu-linux-x64/extras=s3-cache
    steps:
      - uses: runs-on/action@v2.0.3
      - uses: actions/checkout@v5.0.0
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - name: Yarn install
        working-directory: ./react
        run: yarn install
      - name: Build
        working-directory: ./react
        run: yarn build

  lint:
    name: Lint
    runs-on: runs-on=${{ github.run_id }}/runner=4cpu-linux-x64/extras=s3-cache
    steps:
      - uses: runs-on/action@v2.0.3
      - uses: actions/checkout@v5.0.0
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - name: Yarn install
        working-directory: ./react
        run: yarn install
      - name: Lint
        working-directory: ./react
        run: yarn lint

  test:
    name: Test (Node ${{ matrix.node-version }})
    runs-on: runs-on=${{ github.run_id }}/runner=4cpu-linux-x64/extras=s3-cache
    strategy:
      matrix:
        node-version: [24.11.0, 25.1.0]
    steps:
      - uses: runs-on/action@v2.0.3
      - uses: actions/checkout@v5.0.0
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn install
        working-directory: ./react
        run: yarn install
      - name: Test
        working-directory: ./react
        run: yarn test
      - name: Test (React Native)
        working-directory: ./react
        run: yarn test:reactnative
