name: Pull request - schematic-react

on:
  pull_request:
    paths:
      - react/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Yarn install
        working-directory: ./react
        run: yarn install
      - name: Build
        working-directory: ./react
        run: yarn build

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Yarn install
        working-directory: ./react
        run: yarn install
      - name: Lint
        working-directory: ./react
        run: yarn lint
