name: Pull request - schematic-react

on:
  pull_request:
    paths:
      - react/**

jobs:
  build:
    name: Build
    runs-on: runs-on=${{ github.run_id }}/runner=4cpu-linux-x64/extras=s3-cache
    steps:
      - uses: runs-on/action@v2
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 20.x
      - name: Yarn install
        working-directory: ./react
        run: yarn install
      - name: Build
        working-directory: ./react
        run: yarn build

  lint:
    name: Lint
    runs-on: runs-on=${{ github.run_id }}/runner=4cpu-linux-x64/extras=s3-cache
    steps:
      - uses: runs-on/action@v2
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 20.x
      - name: Yarn install
        working-directory: ./react
        run: yarn install
      - name: Lint
        working-directory: ./react
        run: yarn lint
